#!/usr/bin/env python3
"""DCC translation reviewer — Claude Haiku via CLI (subscription).

After the translator produces an English artifact, this reviewer reads the
source Vietnamese visible text and the translated English visible text in
parallel, then asks Claude Haiku 4.5 to produce a JSON report flagging
defects (Vietnamese residue, word-salad, expanded acronyms, broken HTML,
wrong terminology, ...).

Designed to be invoked from PHP DocumentLocaleAutomationService AFTER the
translation artifact is written. Output JSON is stored in the
`translation_review_run` table; if `outcome == "fail"`, the variant is
flipped back to `blocked` so the admin sees the issue.

Stdin (JSON):
{
  "doc_code": "AUTHORITY-MATRIX",
  "vi_html_path": "/absolute/path/to/source.html",   // OR
  "vi_html": "<!doctype html>...",                   // inline
  "en_html_path": "/absolute/path/to/_translated.en.html",  // OR
  "en_html": "<!doctype html>...",                   // inline
  "max_paragraphs": 80          (optional, default 80)
}

Provide either *_html_path OR *_html for each side. Inline takes precedence.

Stdout (JSON):
{
  "ok": true|false,
  "doc_code": "...",
  "review": { ...the JSON the model emitted... },
  "model": "haiku-4-5",
  "usage": { "input_tokens": N, "output_tokens": N, "cached_input_tokens": N },
  "elapsed_seconds": 1.23
}

Exits non-zero only on infrastructure failure (CLI missing, timeout, JSON
parse fail). A "fail" review outcome is still exit 0.

Env vars:
    DCC_REVIEWER_MODEL          default "haiku-4-5"
    DCC_CLI_BINARY              path to `claude` CLI
    DCC_CLI_AUTH_HOME           HOME dir for credentials
    DCC_REVIEWER_TIMEOUT        seconds (default 120)
    DCC_REVIEWER_PROMPT_PATH    override path to reviewer system prompt
"""

from __future__ import annotations

import html as html_mod
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional


REPO_ROOT = Path(__file__).resolve().parents[2]

# Resolve CLI binary at startup. DCC_CLI_BINARY env (set by PHP from the
# translation_credentials.cli_binary_path column) wins. Otherwise fall back
# to common Linux/macOS install paths so dev workstations work too.
def _resolve_cli_binary() -> str:
    env = (os.environ.get("DCC_CLI_BINARY") or "").strip()
    if env and Path(env).is_file():
        return env
    for candidate in ("/usr/local/bin/claude", "/opt/homebrew/bin/claude", "/usr/bin/claude"):
        if Path(candidate).is_file():
            return candidate
    return env or "/usr/local/bin/claude"


CLI_BINARY = _resolve_cli_binary()
MODEL = os.environ.get("DCC_REVIEWER_MODEL", "haiku-4-5").strip() or "haiku-4-5"
TIMEOUT = int(os.environ.get("DCC_REVIEWER_TIMEOUT", "120") or 120)

DEFAULT_PROMPT_PATH = REPO_ROOT / "mom" / "data" / "config" / "translation-reviewer-system-prompt.md"
PROMPT_PATH = Path(os.environ.get("DCC_REVIEWER_PROMPT_PATH") or DEFAULT_PROMPT_PATH)
LEARNING_BLOCK_PATH = REPO_ROOT / "mom" / "data" / "cache" / "translation-learning-block.md"


def load_learning_block() -> str:
    """Approved-only anti-pattern memory generated by TranslationLearningService.
    Prepended to the reviewer user prompt so the reviewer is biased to flag
    these recurring errors when they reappear."""
    try:
        if LEARNING_BLOCK_PATH.is_file():
            return LEARNING_BLOCK_PATH.read_text(encoding="utf-8").strip()
    except Exception:
        pass
    return ""


def ensure_runtime_home_env() -> None:
    cli_home = os.environ.get("DCC_CLI_AUTH_HOME", "").strip()
    if cli_home:
        os.environ["HOME"] = cli_home
    runtime_home = os.environ.get("DCC_TRANSLATION_RUNTIME_HOME", "").strip()
    if runtime_home:
        cache_home = Path(runtime_home) / ".cache"
        cache_home.mkdir(parents=True, exist_ok=True)
        os.environ.setdefault("XDG_CACHE_HOME", str(cache_home))


ensure_runtime_home_env()


VN_CHAR_RE = re.compile(
    r"[àáạảãăắằẳẵặâấầẩẫậđèéẹẻẽêếềểễệìíịỉĩòóọỏõôốồổỗộơớờởỡợùúụủũưứừửữựỳýỵỷỹ]",
    re.I,
)

# Stripped to the same set of skip-tags as the translator pipeline.
_SKIP_RE = re.compile(
    r"<(?:script|style|noscript|svg|math|pre|code)\b[^>]*>.*?</(?:script|style|noscript|svg|math|pre|code)>",
    re.I | re.S,
)
_TAG_RE = re.compile(r"<[^>]+>")
_WS_RE = re.compile(r"[ \t ]+")
_BLANK_LINE_RE = re.compile(r"\n\s*\n+")


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        raise RuntimeError(f"cannot read {path}: {exc}") from exc


def visible_paragraphs(markup: str) -> List[str]:
    """Strip HTML and segment into paragraphs (1 paragraph ≈ 1 source line/block)."""
    cleaned = _SKIP_RE.sub(" ", markup or "")
    # Convert structural breaks to newlines so paragraphs survive.
    cleaned = re.sub(r"<(?:br|/p|/li|/td|/h\d|/div|/tr|/section|/article)[^>]*>", "\n", cleaned, flags=re.I)
    cleaned = _TAG_RE.sub(" ", cleaned)
    cleaned = html_mod.unescape(cleaned)
    cleaned = _WS_RE.sub(" ", cleaned)
    # Split on blank line / single newline.
    paragraphs = [p.strip() for p in cleaned.splitlines()]
    paragraphs = [p for p in paragraphs if p]
    # Collapse very short consecutive lines (e.g. role-code badges) into the
    # previous paragraph to keep alignment with VN source rougher but stable.
    merged: List[str] = []
    for p in paragraphs:
        if merged and len(p) < 8:
            merged[-1] = merged[-1] + " " + p
        else:
            merged.append(p)
    return merged


def build_paired_text(vi_paragraphs: List[str], en_paragraphs: List[str], cap: int) -> Dict[str, str]:
    """Build [V1]/[E1] aligned bodies. When counts differ we still emit both lists
    fully so the reviewer can spot missing/extra paragraphs."""
    vi = vi_paragraphs[:cap]
    en = en_paragraphs[:cap]
    vi_body = "\n\n".join(f"[V{i+1}] {p}" for i, p in enumerate(vi))
    en_body = "\n\n".join(f"[E{i+1}] {p}" for i, p in enumerate(en))
    return {"vi": vi_body, "en": en_body}


def read_system_prompt() -> str:
    if PROMPT_PATH.is_file():
        return PROMPT_PATH.read_text(encoding="utf-8")
    return (
        "You are a QMS translation reviewer. Output a JSON object with keys "
        "outcome ('pass'|'advisory'|'fail'), summary, stats, issues."
    )


def build_user_prompt(doc_code: str, vi_body: str, en_body: str) -> str:
    learning = load_learning_block()
    head = ""
    if learning:
        head = (
            "Apply the LEARNED ANTI-PATTERNS below when scanning the translation; "
            "any recurrence should be flagged as a critical issue with the appropriate category.\n\n"
            + learning
            + "\n\n"
        )
    return (
        head
        + f"doc_code: {doc_code}\n\n"
        + f"=== VIETNAMESE SOURCE (visible text, paragraph-numbered) ===\n"
        + f"{vi_body}\n\n"
        + f"=== ENGLISH TRANSLATION (visible text, paragraph-numbered) ===\n"
        + f"{en_body}\n\n"
        + f"Emit the JSON review report now."
    )


_JSON_OBJECT_RE = re.compile(r"\{.*\}", re.S)


def extract_json(text: str) -> Optional[dict]:
    """Try strict json.loads first, then fall back to greedy { ... } match."""
    if not text:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    m = _JSON_OBJECT_RE.search(text)
    if not m:
        return None
    candidate = m.group(0)
    try:
        return json.loads(candidate)
    except json.JSONDecodeError:
        return None


def call_claude_cli(system_prompt: str, user_prompt: str) -> Dict[str, object]:
    cmd = [
        CLI_BINARY,
        "-p",
        "--max-turns", "1",
        "--no-session-persistence",
        "--output-format", "json",
        "--model", MODEL,
        "--system-prompt", system_prompt,
        user_prompt,
    ]
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
            timeout=TIMEOUT,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(f"claude CLI not found at {CLI_BINARY}: {exc}") from exc
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"reviewer timed out after {TIMEOUT}s") from exc

    if proc.returncode != 0:
        raise RuntimeError(
            f"claude CLI exit={proc.returncode} stderr={proc.stderr[:600]}"
        )

    try:
        decoded = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"claude CLI stdout was not JSON: {proc.stdout[:400]}") from exc

    text = ""
    if isinstance(decoded, dict):
        text = (
            decoded.get("result")
            or decoded.get("message")
            or (decoded.get("content")[0].get("text") if isinstance(decoded.get("content"), list) and decoded.get("content") else "")
            or ""
        )
    usage = (decoded or {}).get("usage") or {}
    return {
        "text": str(text),
        "usage": {
            "input_tokens": int(usage.get("input_tokens", 0) or 0),
            "output_tokens": int(usage.get("output_tokens", 0) or 0),
            "cached_input_tokens": int(usage.get("cache_read_input_tokens", usage.get("cached_input_tokens", 0)) or 0),
        },
    }


def normalise_review(review: dict, paragraphs_reviewed: int) -> dict:
    """Apply defensive defaults + clamp issue list size."""
    if not isinstance(review, dict):
        return {
            "outcome": "fail",
            "summary": "reviewer returned non-object payload",
            "stats": {"paragraphs_reviewed": paragraphs_reviewed, "issues_critical": 1, "issues_advisory": 0},
            "issues": [{
                "segment": "html",
                "severity": "critical",
                "category": "other",
                "vi_excerpt": "",
                "en_excerpt": "",
                "explanation": "reviewer returned malformed JSON",
                "suggestion": "investigate reviewer output",
            }],
        }
    outcome = str(review.get("outcome") or "fail").lower()
    if outcome not in ("pass", "advisory", "fail"):
        outcome = "fail"
    issues = review.get("issues") or []
    if not isinstance(issues, list):
        issues = []
    # Hard cap.
    issues = issues[:25]
    crit = sum(1 for i in issues if isinstance(i, dict) and str(i.get("severity")).lower() == "critical")
    adv = sum(1 for i in issues if isinstance(i, dict) and str(i.get("severity")).lower() == "advisory")
    if crit > 0 and outcome != "fail":
        outcome = "fail"
    elif outcome == "pass" and adv > 0:
        outcome = "advisory"
    return {
        "outcome": outcome,
        "summary": str(review.get("summary") or "")[:600],
        "stats": {
            "paragraphs_reviewed": paragraphs_reviewed,
            "issues_critical": crit,
            "issues_advisory": adv,
        },
        "issues": issues,
    }


def review_pair(doc_code: str, vi_html: str, en_html: str, max_paragraphs: int) -> Dict[str, object]:
    vi_paragraphs = visible_paragraphs(vi_html)
    en_paragraphs = visible_paragraphs(en_html)

    # Cheap pre-flight: if EN visible text contains Vietnamese characters, we
    # still call the model (the JSON taxonomy is helpful) but bias the prompt.
    bodies = build_paired_text(vi_paragraphs, en_paragraphs, max_paragraphs)
    paragraphs_reviewed = min(max_paragraphs, max(len(vi_paragraphs), len(en_paragraphs)))

    user_prompt = build_user_prompt(doc_code, bodies["vi"], bodies["en"])
    response = call_claude_cli(read_system_prompt(), user_prompt)
    review_raw = extract_json(response["text"])
    review = normalise_review(review_raw or {}, paragraphs_reviewed)
    return {
        "review": review,
        "usage": response["usage"],
    }


def main() -> int:
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError as exc:
        print(json.dumps({"ok": False, "error": f"bad stdin json: {exc}"}))
        return 2

    doc_code = str(payload.get("doc_code") or "").strip() or "UNKNOWN"
    vi_inline = payload.get("vi_html")
    en_inline = payload.get("en_html")
    vi_path = payload.get("vi_html_path")
    en_path = payload.get("en_html_path")
    max_paragraphs = int(payload.get("max_paragraphs") or 80)

    try:
        if isinstance(vi_inline, str) and vi_inline.strip():
            vi_html = vi_inline
        elif vi_path:
            vi_html = read_text(Path(vi_path))
        else:
            print(json.dumps({"ok": False, "error": "vi_html or vi_html_path required"}))
            return 2
        if isinstance(en_inline, str) and en_inline.strip():
            en_html = en_inline
        elif en_path:
            en_html = read_text(Path(en_path))
        else:
            print(json.dumps({"ok": False, "error": "en_html or en_html_path required"}))
            return 2
    except RuntimeError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}))
        return 2

    started = time.time()
    try:
        result = review_pair(doc_code, vi_html, en_html, max_paragraphs)
    except RuntimeError as exc:
        print(json.dumps({"ok": False, "error": str(exc), "doc_code": doc_code, "model": MODEL}))
        return 3

    out = {
        "ok": True,
        "doc_code": doc_code,
        "model": MODEL,
        "review": result["review"],
        "usage": result["usage"],
        "elapsed_seconds": round(time.time() - started, 3),
    }
    print(json.dumps(out, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
