---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pqobnire/qms.hesem.com.vn
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    - /bin/mkdir -p /home/pqobnire/qms-data-private/config
    - /bin/cp _build/qms-data-private/config/folder_descriptions.json /home/pqobnire/qms-data-private/config/folder_descriptions.json 2>/dev/null || true
