from __future__ import annotations


def codes(*items: str) -> list[str]:
    return list(items)


def profile(
    departments: list[str],
    reports_to: list[str] | None = None,
    direct_reports: list[str] | None = None,
    primary_interfaces: list[str] | None = None,
    internal_interfaces: list[str] | None = None,
    external_interfaces: str = "",
) -> dict[str, object]:
    return {
        "departments": list(departments),
        "reports_to": list(reports_to or []),
        "direct_reports": list(direct_reports or []),
        "primary_interfaces": list(primary_interfaces or []),
        "internal_interfaces": list(internal_interfaces or []),
        "external_interfaces": external_interfaces,
    }


ROLE_BOUNDARY_PROFILES: dict[str, dict[str, object]] = {
    "CEO": profile(
        departments=codes("D-EXEC"),
        reports_to=[],
        direct_reports=codes("PD", "QA", "SCM", "FIN", "HR", "EHS", "ITA", "CS", "EST"),
        primary_interfaces=codes("PD", "QA", "SCM", "FIN", "HR", "EHS", "ITA", "CS", "EST"),
        internal_interfaces=codes("PD", "ENGM", "QA", "QMS", "SCM", "FIN", "HR", "EHS", "ITA", "CS", "EST"),
        external_interfaces="Customers, certification bodies, bankers, insurers, legal partners and strategic suppliers as assigned.",
    ),
    "PD": profile(
        departments=codes("D-PROD"),
        reports_to=codes("CEO"),
        direct_reports=codes("ENGM", "PPL", "WKM", "CPS", "MNT", "PIE"),
        primary_interfaces=codes("ENGM", "PPL", "WKM", "QA", "SCM"),
        internal_interfaces=codes("CEO", "ENGM", "PPL", "WKM", "QA", "QMS", "SCM", "MNT", "PIE", "CS", "EST", "XNK", "HR", "EHS", "ITA"),
        external_interfaces="Customers and outsourced process or equipment suppliers when commercial or technical escalation is required.",
    ),
    "WKM": profile(
        departments=codes("D-PROD"),
        reports_to=codes("PD"),
        direct_reports=codes("SL", "SET", "DBL"),
        primary_interfaces=codes("PPL", "ENGM", "QA", "QCL", "MNT", "TOOL"),
        internal_interfaces=codes("PD", "PPL", "ENGM", "QA", "QCL", "SL", "SET", "DBL", "MNT", "TOOL", "WAR", "XNK", "SCM", "PIE"),
        external_interfaces="Machine service providers and tooling or fixture suppliers through SCM, ENGM or MNT.",
    ),
    "SL": profile(
        departments=codes("D-PROD"),
        reports_to=codes("WKM"),
        direct_reports=codes("OPR"),
        primary_interfaces=codes("WKM", "SET", "QA", "QCL", "PPL"),
        internal_interfaces=codes("WKM", "SET", "OPR", "QA", "QCL", "PPL", "ENGM", "MNT", "TOOL", "WAR"),
        external_interfaces="None under normal operation; external contact only through WKM, ENGM or SCM.",
    ),
    "SET": profile(
        departments=codes("D-PROD"),
        reports_to=codes("WKM"),
        direct_reports=[],
        primary_interfaces=codes("WKM", "SL", "ENGM", "CAM", "QA", "QCL"),
        internal_interfaces=codes("WKM", "SL", "ENGM", "PE", "CAM", "QA", "QCL", "MNT", "TOOL", "WAR"),
        external_interfaces="External setup support only through ENGM, MNT or SCM.",
    ),
    "OPR": profile(
        departments=codes("D-PROD"),
        reports_to=codes("SL"),
        direct_reports=[],
        primary_interfaces=codes("SL", "SET", "QCL"),
        internal_interfaces=codes("SL", "SET", "QCL", "WKM", "QA", "MNT", "TOOL", "WAR"),
        external_interfaces="No direct external interface.",
    ),
    "MNT": profile(
        departments=codes("D-PROD"),
        reports_to=codes("PD"),
        direct_reports=[],
        primary_interfaces=codes("WKM", "ENGM", "SL", "SET"),
        internal_interfaces=codes("PD", "WKM", "ENGM", "SL", "SET", "ITA", "ESA", "TOOL", "SCM"),
        external_interfaces="Machine OEMs, service contractors and spare-parts suppliers through SCM.",
    ),
    "PIE": profile(
        departments=codes("D-PROD"),
        reports_to=codes("PD"),
        direct_reports=[],
        primary_interfaces=codes("PPL", "WKM", "ENGM", "QA"),
        internal_interfaces=codes("PD", "PPL", "WKM", "ENGM", "QA", "QMS", "SCM", "MNT", "HR", "FIN"),
        external_interfaces="External CI, tooling and process-improvement parties through PD or SCM.",
    ),
    "PPL": profile(
        departments=codes("D-PPC", "D-PROD"),
        reports_to=codes("PD"),
        direct_reports=[],
        primary_interfaces=codes("WKM", "SCM", "CS", "ENGM", "QA"),
        internal_interfaces=codes("PD", "WKM", "SL", "SCM", "WAR", "XNK", "CS", "EST", "ENGM", "QA", "QCL", "PIE"),
        external_interfaces="Customer promise-date alignment through CS; logistics commitment through XNK or SCM.",
    ),
    "CPS": profile(
        departments=codes("D-PROD"),
        reports_to=codes("PD"),
        direct_reports=codes("CPT"),
        primary_interfaces=codes("QA", "QCL", "WKM", "XNK"),
        internal_interfaces=codes("PD", "QA", "QCL", "WKM", "XNK", "WAR", "SCM", "EHS"),
        external_interfaces="Packaging or cleanliness material suppliers through SCM and XNK.",
    ),
    "CPT": profile(
        departments=codes("D-PROD"),
        reports_to=codes("CPS"),
        direct_reports=[],
        primary_interfaces=codes("CPS", "QCL", "XNK"),
        internal_interfaces=codes("CPS", "QCL", "QA", "WAR", "XNK", "EHS"),
        external_interfaces="No direct external interface.",
    ),
    "DBL": profile(
        departments=codes("D-PROD"),
        reports_to=codes("WKM"),
        direct_reports=codes("DBT"),
        primary_interfaces=codes("WKM", "QCL", "XNK"),
        internal_interfaces=codes("WKM", "SL", "QCL", "QA", "XNK", "WAR"),
        external_interfaces="No direct external interface.",
    ),
    "DBT": profile(
        departments=codes("D-PROD"),
        reports_to=codes("DBL"),
        direct_reports=[],
        primary_interfaces=codes("DBL", "QCL"),
        internal_interfaces=codes("DBL", "QCL", "QA", "XNK", "WAR"),
        external_interfaces="No direct external interface.",
    ),
    "ENGM": profile(
        departments=codes("D-ENG"),
        reports_to=codes("PD"),
        direct_reports=codes("DFM", "PE", "CAM"),
        primary_interfaces=codes("CS", "EST", "QA", "PPL", "WKM", "SCM"),
        internal_interfaces=codes("PD", "CS", "EST", "DFM", "PE", "CAM", "QA", "QE", "QCL", "MCS", "PPL", "WKM", "SET", "MNT", "SCM", "PIE"),
        external_interfaces="Customers for technical clarification and external tooling or process providers through CS or SCM.",
    ),
    "DFM": profile(
        departments=codes("D-ENG"),
        reports_to=codes("ENGM"),
        direct_reports=[],
        primary_interfaces=codes("CS", "EST", "ENGM", "PE", "QA"),
        internal_interfaces=codes("CS", "EST", "ENGM", "PE", "CAM", "QA", "QE", "PPL", "SCM"),
        external_interfaces="Customer drawing or requirement clarification through CS or EST.",
    ),
    "PE": profile(
        departments=codes("D-ENG"),
        reports_to=codes("ENGM"),
        direct_reports=[],
        primary_interfaces=codes("ENGM", "CAM", "WKM", "SET", "QA", "QCL"),
        internal_interfaces=codes("ENGM", "CAM", "WKM", "SET", "QA", "QCL", "PPL", "MCS", "MNT", "TOOL"),
        external_interfaces="Process and tooling support suppliers through ENGM or SCM.",
    ),
    "CAM": profile(
        departments=codes("D-ENG"),
        reports_to=codes("ENGM"),
        direct_reports=[],
        primary_interfaces=codes("ENGM", "PE", "SET", "WKM", "QA", "QCL"),
        internal_interfaces=codes("ENGM", "PE", "SET", "WKM", "QA", "QCL", "PPL", "MNT", "TOOL"),
        external_interfaces="CAM post, tooling and machine-control support through ENGM, MNT or SCM.",
    ),
    "QA": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("CEO"),
        direct_reports=codes("QMS", "QE", "QCL", "MCS", "IAO"),
        primary_interfaces=codes("CEO", "PD", "ENGM", "WKM", "SCM"),
        internal_interfaces=codes("CEO", "PD", "ENGM", "QMS", "QE", "QCL", "QC", "MCS", "PPL", "WKM", "SL", "SCM", "CS", "EST", "FIN", "EHS", "ITA"),
        external_interfaces="Customers, certification bodies, external auditors and approved laboratories as assigned.",
    ),
    "QMS": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QA"),
        direct_reports=[],
        primary_interfaces=codes("QA", "ENGM", "PD", "HR", "ITA"),
        internal_interfaces=codes("QA", "ENGM", "PD", "SCM", "FIN", "HR", "EHS", "ITA", "CS", "EST", "PPL", "WKM", "QCL"),
        external_interfaces="Certification bodies, customer auditors and document-system partners when assigned by QA.",
    ),
    "QE": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QA"),
        direct_reports=[],
        primary_interfaces=codes("QA", "ENGM", "WKM", "QCL", "MCS"),
        internal_interfaces=codes("QA", "ENGM", "WKM", "QCL", "QC", "MCS", "PPL", "SCM", "CS", "EST"),
        external_interfaces="Customer quality contacts and external labs through QA or CS.",
    ),
    "QCL": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QA"),
        direct_reports=codes("QC"),
        primary_interfaces=codes("QA", "WKM", "SL", "QE"),
        internal_interfaces=codes("QA", "WKM", "SL", "QE", "QC", "ENGM", "MCS", "PPL", "XNK", "WAR"),
        external_interfaces="External inspection or sorting support through QA or SCM.",
    ),
    "QC": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QCL"),
        direct_reports=[],
        primary_interfaces=codes("QCL", "QA", "WKM", "SL"),
        internal_interfaces=codes("QCL", "QA", "WKM", "SL", "QE", "ENGM", "MCS", "WAR", "XNK"),
        external_interfaces="No direct external interface unless specifically assigned by QA.",
    ),
    "MCS": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QA"),
        direct_reports=[],
        primary_interfaces=codes("QE", "QCL", "ENGM", "WKM", "SCM"),
        internal_interfaces=codes("QA", "QE", "QCL", "QC", "ENGM", "WKM", "SET", "TOOL", "WAR", "SCM"),
        external_interfaces="Calibration vendors, certified labs and equipment service providers through QA or SCM.",
    ),
    "IAO": profile(
        departments=codes("D-QUAL"),
        reports_to=codes("QA"),
        direct_reports=[],
        primary_interfaces=codes("QA", "QMS"),
        internal_interfaces=codes("QA", "QMS", "PD", "ENGM", "SCM", "FIN", "HR", "EHS", "ITA", "WKM"),
        external_interfaces="Acts as assigned against certification, customer and supplier-audit programs.",
    ),
    "SCM": profile(
        departments=codes("D-SCM"),
        reports_to=codes("CEO"),
        direct_reports=codes("BUY", "WAR", "TOOL", "XNK"),
        primary_interfaces=codes("CS", "EST", "PPL", "WKM", "QA"),
        internal_interfaces=codes("CEO", "CS", "EST", "PPL", "WKM", "QA", "ENGM", "BUY", "WAR", "TOOL", "XNK", "FIN"),
        external_interfaces="Suppliers, freight forwarders, carriers and logistics partners.",
    ),
    "BUY": profile(
        departments=codes("D-PUR", "D-SCM"),
        reports_to=codes("SCM"),
        direct_reports=[],
        primary_interfaces=codes("SCM", "ENGM", "QA", "WAR"),
        internal_interfaces=codes("SCM", "ENGM", "QA", "WAR", "TOOL", "CS", "EST", "PPL"),
        external_interfaces="Material, service and special-process suppliers.",
    ),
    "WAR": profile(
        departments=codes("D-WHS", "D-SCM"),
        reports_to=codes("SCM"),
        direct_reports=[],
        primary_interfaces=codes("PPL", "BUY", "QA", "XNK", "WKM"),
        internal_interfaces=codes("SCM", "PPL", "BUY", "QA", "QCL", "XNK", "WKM", "SL", "TOOL"),
        external_interfaces="Delivery carriers and receiving parties through XNK or SCM.",
    ),
    "TOOL": profile(
        departments=codes("D-TCR", "D-SCM"),
        reports_to=codes("SCM"),
        direct_reports=[],
        primary_interfaces=codes("WKM", "SET", "CAM", "MNT"),
        internal_interfaces=codes("SCM", "WKM", "SET", "CAM", "MNT", "QA", "QCL", "PPL", "WAR"),
        external_interfaces="Tooling, inserts and consumables suppliers through BUY or SCM.",
    ),
    "XNK": profile(
        departments=codes("D-LOG", "D-SCM"),
        reports_to=codes("SCM"),
        direct_reports=[],
        primary_interfaces=codes("CS", "PPL", "WAR", "QA"),
        internal_interfaces=codes("SCM", "CS", "EST", "PPL", "WAR", "QA", "QCL", "WKM", "FIN"),
        external_interfaces="Freight forwarders, carriers and customer shipping windows.",
    ),
    "CS": profile(
        departments=codes("D-SCS"),
        reports_to=codes("CEO"),
        direct_reports=[],
        primary_interfaces=codes("EST", "ENGM", "PPL", "QA", "XNK"),
        internal_interfaces=codes("CEO", "EST", "ENGM", "PPL", "QA", "SCM", "FIN", "PD", "WKM", "XNK"),
        external_interfaces="Customers for RFQ clarification, order acknowledgement, change notice, complaint and delivery updates.",
    ),
    "EST": profile(
        departments=codes("D-SCS"),
        reports_to=codes("CEO"),
        direct_reports=[],
        primary_interfaces=codes("CS", "ENGM", "QA", "SCM", "FIN"),
        internal_interfaces=codes("CEO", "CS", "ENGM", "QA", "SCM", "FIN", "PPL", "PD"),
        external_interfaces="Customers and approved external processors or suppliers during quoting and feasibility review.",
    ),
    "FIN": profile(
        departments=codes("D-FIN"),
        reports_to=codes("CEO"),
        direct_reports=codes("APAR", "GLP"),
        primary_interfaces=codes("CS", "EST", "SCM", "PD"),
        internal_interfaces=codes("CEO", "CS", "EST", "SCM", "PPL", "PD", "QA", "QMS", "XNK", "APAR", "GLP", "HR"),
        external_interfaces="Banks, tax advisors, customers and suppliers for payment or credit matters.",
    ),
    "APAR": profile(
        departments=codes("D-FIN"),
        reports_to=codes("FIN"),
        direct_reports=[],
        primary_interfaces=codes("FIN", "CS", "SCM", "XNK"),
        internal_interfaces=codes("FIN", "CS", "EST", "SCM", "XNK", "PPL", "WAR"),
        external_interfaces="Customers, suppliers and banks for invoicing, collection and payment transactions.",
    ),
    "GLP": profile(
        departments=codes("D-FIN"),
        reports_to=codes("FIN"),
        direct_reports=[],
        primary_interfaces=codes("FIN", "HR", "PD", "CS"),
        internal_interfaces=codes("FIN", "HR", "PD", "SCM", "QA", "CS", "EST"),
        external_interfaces="Tax, payroll and statutory reporting parties through FIN.",
    ),
    "HR": profile(
        departments=codes("D-HR"),
        reports_to=codes("CEO"),
        direct_reports=[],
        primary_interfaces=codes("PD", "QA", "ENGM", "FIN", "EHS"),
        internal_interfaces=codes("CEO", "PD", "QA", "ENGM", "FIN", "EHS", "QMS", "WKM", "SL", "QCL", "ITA"),
        external_interfaces="Candidates, labor authorities, payroll and training providers.",
    ),
    "EHS": profile(
        departments=codes("D-EHS"),
        reports_to=codes("CEO"),
        direct_reports=[],
        primary_interfaces=codes("PD", "WKM", "HR", "QA"),
        internal_interfaces=codes("CEO", "PD", "WKM", "SL", "CPS", "MNT", "HR", "QA", "SCM"),
        external_interfaces="Authorities, waste handlers, emergency responders and safety service providers.",
    ),
    "ITA": profile(
        departments=codes("D-IT"),
        reports_to=codes("CEO"),
        direct_reports=codes("ESA"),
        primary_interfaces=codes("QMS", "FIN", "HR", "ENGM", "PD"),
        internal_interfaces=codes("CEO", "QMS", "FIN", "HR", "ENGM", "PD", "SCM", "QA", "CS", "EST", "ESA"),
        external_interfaces="IT vendors, M365 administrators, network and security providers.",
    ),
    "ESA": profile(
        departments=codes("D-ERP", "D-IT"),
        reports_to=codes("ITA"),
        direct_reports=[],
        primary_interfaces=codes("QMS", "FIN", "PPL", "SCM"),
        internal_interfaces=codes("ITA", "QMS", "FIN", "PPL", "SCM", "ENGM", "PD", "HR", "QA", "WAR", "XNK"),
        external_interfaces="ERP partners, implementation vendors and technical support providers.",
    ),
}
