# -*- coding: utf-8 -*-
"""
WAVE 1: TYPE A CHECKLIST FORMS — 38 forms
All use same pattern: Ref(2 rows) + Checklist + Approval + Notice
Lean: min fields, max practical value for CNC job-order
"""

WAVE1 = [
    # === FRM-100 Series: QMS Core ===
    {
        'code': 'FRM-102', 'title': 'DOCUMENT CHANGE REQUEST', 'format': 'A4P',
        'owner': 'QA / QMS', 'approved': 'QA Manager',
        'ref_fields': [('Document Code / Title', 'Change Request Date'), ('Requested by', 'Priority')],
        'sections': [
            {'title': 'CHANGE EVALUATION', 'type': 'checklist',
             'headers': ['#','Cat.','Evaluation Item','Acceptance Criteria','Result','Owner'],
             'items': [
                 (1,'DOC','Change scope and affected documents identified.','All impacted docs listed.'),
                 (2,'DOC','Impact on other processes / forms assessed.','No unintended side effects.'),
                 (3,'QUA','Review by subject matter expert completed.','SME confirms technical accuracy.'),
                 (4,'QUA','Pilot / dry-run conducted (if applicable).','No issues found during trial.'),
                 (5,'DOC','Old revision recalled / new revision distributed.','All holders notified.'),
                 (6,'DOC','Training on change completed (if required).','Affected personnel briefed.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Requested by', 'Approved by'],
        'notice': 'NOTICE \u2014 One form per change request. Ref: SOP-101. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-104', 'title': 'DOCUMENT DEPLOYMENT CHECKLIST', 'format': 'A4P',
        'owner': 'QA / QMS', 'approved': 'QA Manager',
        'ref_fields': [('Document Code / Rev', 'Deployment Date'), ('Deployed by', 'Effective Date')],
        'sections': [
            {'title': 'DEPLOYMENT VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'DOC','New revision uploaded to controlled location.','File accessible and correct version.'),
                 (2,'DOC','Old revision removed / marked superseded.','No duplicate active versions.'),
                 (3,'DOC','All affected personnel notified.','Email / meeting evidence exists.'),
                 (4,'DOC','Training delivered (if required by change).','Attendance recorded.'),
                 (5,'QUA','Spot-check: users can access correct version.','Random verification passed.'),
                 (6,'DOC','Document register (FRM-101) updated.','Registry reflects new revision.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Deployed by', 'Approved by'],
        'notice': 'NOTICE \u2014 One form per deployment event. Ref: SOP-101. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-110', 'title': 'M365 CONFIGURATION CHECKLIST', 'format': 'A4P',
        'owner': 'IT', 'approved': 'IT Manager',
        'ref_fields': [('System / Tenant', 'Configuration Date'), ('Configured by', 'Review Period')],
        'sections': [
            {'title': 'CONFIGURATION VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'DOC','Permissions and sharing settings correct.','Least-privilege principle applied.'),
                 (2,'DOC','Retention policies configured.','Meets QMS retention schedule.'),
                 (3,'DOC','Backup and recovery tested.','Restore test passed within RTO.'),
                 (4,'DOC','Security settings (MFA, DLP) active.','Compliance dashboard green.'),
                 (5,'DOC','Audit logging enabled.','Events captured for 90+ days.'),
                 (6,'DOC','External sharing restricted appropriately.','No unauthorized external access.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['IT Admin', 'IT Manager'],
        'notice': 'NOTICE \u2014 Ref: SOP-101. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-111', 'title': 'QUARTERLY ACCESS REVIEW', 'format': 'A4P',
        'owner': 'IT', 'approved': 'IT Manager',
        'ref_fields': [('Review Period', 'Review Date'), ('Reviewer', 'Systems Covered')],
        'sections': [
            {'title': 'ACCESS REVIEW', 'type': 'checklist',
             'items': [
                 (1,'DOC','Active user list matches current employees.','No departed users with active accounts.'),
                 (2,'DOC','Permission levels appropriate for each role.','No excess privileges found.'),
                 (3,'DOC','Shared drives / folders access verified.','Only authorized groups have access.'),
                 (4,'DOC','Service accounts reviewed and justified.','All service accounts have documented purpose.'),
                 (5,'DOC','Findings remediated or escalated.','All issues have action + owner.'),
                 (6,'DOC','Review log signed and filed.','Evidence retained for audit.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Reviewer', 'IT Manager'],
        'notice': 'NOTICE \u2014 Quarterly. Ref: SOP-101. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-141', 'title': 'IT ACCESS REQUEST', 'format': 'A4P',
        'owner': 'IT', 'approved': 'Department Manager',
        'ref_fields': [('Requester / Department', 'Request Date'), ('Access Type (New/Change/Remove)', 'Systems Requested')],
        'sections': [
            {'title': 'AUTHORIZATION', 'type': 'pairs',
             'fields': [('Justification', 'Access Level Requested'), ('Effective Date', 'Expiry Date (if temp)')],
            },
        ],
        'approval': ['Requester', 'Dept Manager', 'IT Admin'],
        'notice': 'NOTICE \u2014 Ref: SOP-101. Retain: 5 years.',
    },
    {
        'code': 'FRM-163', 'title': 'CONFIGURATION AUDIT CHECKLIST', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Audit Date', 'Auditor')],
        'sections': [
            {'title': 'CONFIGURATION VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'TEC','Drawing revision at workstation matches released rev.','No obsolete drawings in use.'),
                 (2,'TEC','CNC program revision matches setup sheet.','Program name/rev verified.'),
                 (3,'TEC','BOM / material matches specification.','Material cert aligns with drawing.'),
                 (4,'TEC','Tooling matches setup sheet tool list.','All tools accounted for.'),
                 (5,'TEC','Fixture / workholding matches setup sheet.','Fixture ID verified.'),
                 (6,'TEC','Routing / operation sequence correct.','Job traveler matches plan.'),
                 (7,'TEC','ECO / change notices incorporated.','No pending unincorporated changes.'),
                 (8,'QUA','All configuration items consistent.','Overall config audit: PASS/FAIL.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Auditor', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per audit. Ref: SOP-101. Retain: 5 years.',
        'dv_result_col': 32,
    },

    # === FRM-200 Series: Sales & Order ===
    {
        'code': 'FRM-202', 'title': 'CONTRACT REVIEW CHECKLIST', 'format': 'A4P',
        'owner': 'Sales / CS', 'approved': 'Sales Mgr / QA Mgr',
        'ref_fields': [('Customer', 'RFQ / PO No.'), ('Part No. / Revision', 'Required Delivery Date')],
        'sections': [
            {'title': 'EVALUATION \u2014 COMMERCIAL / TECHNICAL / QUALITY / CAPACITY', 'type': 'checklist',
             'items': [
                 (1,'COM','PO/RFQ contains: part no., rev., qty, due date, ship terms.','Complete \u2192 PASS; Missing \u2192 HOLD.'),
                 (2,'COM','Price and payment terms are acceptable.','Margin \u2265 threshold per SOP-201.'),
                 (3,'TEC','Drawing / spec received \u2014 correct rev., fully readable.','PDF+DXF/STEP; drawing no. matches PO.'),
                 (4,'TEC','Tolerance / CTQ / KCC achievable with current equipment.','Est. Cpk \u2265 1.33 \u2192 PASS.'),
                 (5,'TEC','Material / treatment / cert. listed in AML/APL.','AML match \u2192 PASS; New \u2192 HOLD.'),
                 (6,'TEC','Outsource / special process / ext. provider identified.','Qualified supplier available \u2192 PASS.'),
                 (7,'QUA','CSR / cleanliness / vacuum / packing requirements identified.','Level and responsible party documented.'),
                 (8,'QUA','QPL / inspection level / FAI requirement is clear.','Per AS9100D / SEMI S2 / customer-specific.'),
                 (9,'CAP','Machine / fixture / tooling / routing feasible.','Load \u2264 80% \u2192 PASS; Overload \u2192 HOLD.'),
                 (10,'CAP','Lead time and material sourcing feasible.','Schedule buffer \u2265 5 working days \u2192 PASS.'),
                 (11,'CAP','Ship label / CoC / packaging logic defined.','Template exists \u2192 PASS; To create \u2192 HOLD.'),
                 (12,'CON','Job dossier / evidence path confirmed before release.','Path created in Job Dossier prior to release.'),
             ], 'blank_rows': 0},
        ],
        'approval': ['Sales / CS', 'Engineering', 'QA / Approver'],
        'notice': 'NOTICE \u2014 One form per contract/PO. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-204', 'title': 'ORDER KICKOFF CHECKLIST', 'format': 'A4P',
        'owner': 'Planning', 'approved': 'Production Director',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Customer', 'Target Start Date')],
        'sections': [
            {'title': 'KICKOFF READINESS', 'type': 'checklist',
             'items': [
                 (1,'DOC','Drawing and spec package released to production.','Correct revision in job packet.'),
                 (2,'TEC','Material available or ordered with confirmed delivery.','Stock or PO confirmed.'),
                 (3,'TEC','Routing and operation sequence finalized.','Setup sheet (FRM-302) released.'),
                 (4,'CAP','Tooling and fixtures identified and available.','Tool list confirmed.'),
                 (5,'CAP','Outsource processes identified, PO issued.','Supplier confirmed, lead time fits.'),
                 (6,'CAP','Machine capacity and schedule confirmed.','No conflict with other jobs.'),
                 (7,'QUA','Inspection plan and gages identified.','Measurement capability confirmed.'),
                 (8,'DOC','Job dossier created, evidence path set.','M365 folder or controlled path ready.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Planner', 'Production Director'],
        'notice': 'NOTICE \u2014 One form per job kickoff. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-206', 'title': 'JOB COMPLETION CHECKLIST', 'format': 'A4P',
        'owner': 'Production / QA', 'approved': 'Production Director',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Customer', 'Completion Date')],
        'sections': [
            {'title': 'COMPLETION VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'OPS','All operations completed per routing.','Job traveler fully signed off.'),
                 (2,'QUA','Final inspection passed (FRM-641).','Inspection report attached.'),
                 (3,'QUA','CoC / cert package prepared.','CoC matches customer requirements.'),
                 (4,'OPS','Packaging completed per spec (FRM-707/709).','Packaging checklist passed.'),
                 (5,'DOC','Shipping documents prepared.','Labels, packing list, customs docs ready.'),
                 (6,'DOC','Job dossier complete \u2014 all evidence filed.','All forms and records in dossier.'),
                 (7,'QUA','All NCRs / holds resolved.','No open nonconformances.'),
                 (8,'DOC','Lessons learned captured (if any).','FRM-151 updated if applicable.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Production', 'QA'],
        'notice': 'NOTICE \u2014 One form per job completion. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-207', 'title': 'OPERATIONAL RISK CONTROL SHEET', 'format': 'A4P',
        'owner': 'Engineering / QA', 'approved': 'Production Director',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Risk Assessment Date', 'Assessed by')],
        'sections': [
            {'title': 'RISK EVALUATION', 'type': 'checklist',
             'headers': ['#','Cat.','Risk Item','Control / Mitigation','Result','Owner'],
             'items': [
                 (1,'TEC','Tight tolerance risk (\u22640.025mm features).','Capable machine + qualified operator assigned.'),
                 (2,'TEC','Material risk (new alloy / exotic material).','Test cut or material trial planned.'),
                 (3,'CAP','Capacity risk (machine availability / bottleneck).','Backup machine identified or schedule buffer.'),
                 (4,'CAP','Outsource risk (supplier lead time / quality).','Qualified backup supplier available.'),
                 (5,'QUA','Inspection risk (complex GD&T / CMM required).','CMM program validated, MSA current.'),
                 (6,'QUA','Cleanliness / contamination risk (semi parts).','Clean process and packaging confirmed.'),
                 (7,'OPS','First-time-right risk (new part / new process).','Trial run or pilot planned.'),
                 (8,'OPS','Delivery risk (tight deadline / partial ship).','Milestone dates confirmed with customer.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Assessed by', 'Approved by'],
        'notice': 'NOTICE \u2014 One form per job risk assessment. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-209', 'title': 'HIGH-RISK JOB READINESS REVIEW', 'format': 'A4P',
        'owner': 'Engineering / QA', 'approved': 'General Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Review Date', 'Review Lead')],
        'sections': [
            {'title': 'READINESS EVALUATION', 'type': 'checklist',
             'items': [
                 (1,'CAP','Machine capability confirmed for all critical features.','Process capability data available.'),
                 (2,'TEC','Tooling strategy validated (tool life, backup tools).','Tool list reviewed and approved.'),
                 (3,'TEC','Material sourced and verified (cert, grade, lot).','Material cert matches spec.'),
                 (4,'QUA','Inspection plan covers all critical characteristics.','CMM program ready, gages calibrated.'),
                 (5,'CAP','Outsource processes confirmed (lead time, capability).','Supplier qualified and available.'),
                 (6,'OPS','Contingency plan for failure modes documented.','PFMEA or risk sheet reviewed.'),
                 (7,'QUA','Operator qualified for this part / process.','Training record current.'),
                 (8,'OPS','Management approval to proceed.','Risk accepted at appropriate level.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Review Lead', 'General Manager'],
        'notice': 'NOTICE \u2014 Required for HIGH/CRITICAL risk jobs. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-212', 'title': 'CUSTOMER CHANGE REQUEST', 'format': 'A4P',
        'owner': 'Sales / CS', 'approved': 'Sales Manager',
        'ref_fields': [('Job / WO', 'Customer'), ('Change Request Date', 'Requested by')],
        'sections': [
            {'title': 'CHANGE EVALUATION', 'type': 'checklist',
             'items': [
                 (1,'COM','Change scope clearly defined by customer.','Written request received.'),
                 (2,'TEC','Technical feasibility assessed.','Engineering confirms capability.'),
                 (3,'COM','Cost and schedule impact evaluated.','Quote / timeline provided to customer.'),
                 (4,'QUA','Quality impact assessed (spec, inspection, cert).','No degradation of requirements.'),
                 (5,'COM','Customer approval of revised terms received.','Written confirmation on file.'),
                 (6,'DOC','Internal documents updated (drawing, routing, setup).','All affected docs revised.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Sales / CS', 'Engineering'],
        'notice': 'NOTICE \u2014 One form per customer change. Ref: SOP-201. Retain: 10 years.',
        'dv_result_col': 32,
    },

    # === FRM-300 Series: Engineering ===
    {
        'code': 'FRM-303', 'title': 'DFM REVIEW CHECKLIST', 'format': 'A4P',
        'owner': 'Engineering', 'approved': 'Engineering Manager',
        'ref_fields': [('Part No. / Revision', 'Customer'), ('DFM Review Date', 'DFM Engineer')],
        'sections': [
            {'title': 'MANUFACTURABILITY EVALUATION', 'type': 'checklist',
             'items': [
                 (1,'TEC','All tolerances achievable with available machines.','Tight features (<0.025mm) identified.'),
                 (2,'TEC','GD&T datums accessible for machining and measurement.','CMM fixturing feasible.'),
                 (3,'TEC','Material machinability confirmed.','Cutting data available for this alloy.'),
                 (4,'TEC','Surface finish requirements achievable.','Ra targets within machine capability.'),
                 (5,'TEC','Fixture / workholding concept identified.','No deformation risk on thin walls.'),
                 (6,'CAP','Outsource processes identified (HT/plate/anod).','Qualified supplier available.'),
                 (7,'QUA','Cleanliness / vacuum compatibility assessed.','Cleaning process defined if required.'),
                 (8,'QUA','Inspection method defined for all critical dims.','Gage / CMM program feasible.'),
                 (9,'CAP','Estimated cycle time and cost realistic.','Competitive quote possible.'),
                 (10,'TEC','Customer RFI / clarification needed?','All ambiguities resolved before quote.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['DFM Engineer', 'Engineering Manager'],
        'notice': 'NOTICE \u2014 One form per DFM review. Ref: SOP-301. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-304', 'title': 'SEMICONDUCTOR PART CLASSIFICATION', 'format': 'A4P',
        'owner': 'Engineering / QA', 'approved': 'QA Manager',
        'ref_fields': [('Part No. / Revision', 'Customer'), ('Classification Date', 'Classified by')],
        'sections': [
            {'title': 'CLASSIFICATION CRITERIA', 'type': 'checklist',
             'items': [
                 (1,'QUA','Cleanliness class determined (ISO 14644 / SEMI).','Class level documented.'),
                 (2,'QUA','Vacuum compatibility required?','Material outgassing spec defined.'),
                 (3,'QUA','Material restriction (RoHS / REACH / F-gas).','Compliance confirmed.'),
                 (4,'TEC','Special process required (passivation, e-polish).','Qualified processor identified.'),
                 (5,'QUA','Marking / engraving restrictions.','No contamination risk from marking method.'),
                 (6,'QUA','Clean packaging required (double bag / N2 purge).','Packaging spec defined.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Classified by', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per part classification. Ref: SOP-301. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-305', 'title': 'INSPECTION PROGRAM RELEASE CHECKLIST', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('Part No. / Revision', 'CMM Program Name / Rev'), ('Release Date', 'Programmer')],
        'sections': [
            {'title': 'PROGRAM VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'QUA','Program aligns with drawing dimensions.','All critical dims included.'),
                 (2,'QUA','Datum structure matches drawing GD&T.','Alignment strategy correct.'),
                 (3,'QUA','Fixture / holding method documented.','Part orientation repeatable.'),
                 (4,'QUA','First run on known-good part: results match manual.','Delta < measurement uncertainty.'),
                 (5,'QUA','Output format meets customer / CoC requirements.','Report template correct.'),
                 (6,'QUA','Program archived in controlled location.','Version control applied.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Programmer', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per CMM program release. Ref: SOP-301. Retain: 10 years.',
        'dv_result_col': 32,
    },

    # === FRM-400 Series: Procurement ===
    {
        'code': 'FRM-403', 'title': 'OUTSOURCED PROCESS REQUEST', 'format': 'A4P',
        'owner': 'Purchasing', 'approved': 'Supply Chain Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Process Required', 'Preferred Supplier')],
        'sections': [
            {'title': 'REQUEST EVALUATION', 'type': 'checklist',
             'items': [
                 (1,'TEC','Process specification defined (temp, time, thickness).','Spec attached or referenced.'),
                 (2,'CAP','Supplier is on approved list (APL).','APL status confirmed.'),
                 (3,'CAP','Lead time fits job schedule.','Delivery date confirmed by supplier.'),
                 (4,'QUA','Requirements flowed down (spec, cert, marking).','PO includes all flowdown items.'),
                 (5,'QUA','Acceptance criteria defined for return.','Inspection method for incoming verification.'),
                 (6,'DOC','PO issued with all requirements.','PO number documented.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Buyer', 'Supply Chain Manager'],
        'notice': 'NOTICE \u2014 One form per outsource request. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-404', 'title': 'OUTSOURCE DISPATCH CHECKLIST', 'format': 'A4P',
        'owner': 'Warehouse / Production', 'approved': 'Production Supervisor',
        'ref_fields': [('Job / WO', 'Supplier'), ('Dispatch Date', 'Dispatched by')],
        'sections': [
            {'title': 'DISPATCH VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'OPS','Parts counted and match PO quantity.','Count verified.'),
                 (2,'DOC','Process spec / drawing attached to shipment.','Physical copy or digital link confirmed.'),
                 (3,'QUA','Special requirements noted on PO (masking, orientation).','Requirements visible to supplier.'),
                 (4,'OPS','Parts packaged to prevent damage in transit.','Appropriate packaging used.'),
                 (5,'OPS','Transport arranged and tracked.','Tracking number recorded.'),
                 (6,'DOC','Expected return date confirmed with supplier.','Date documented.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Dispatched by', 'Supervisor'],
        'notice': 'NOTICE \u2014 One form per dispatch. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-406', 'title': 'SUPPLIER CORRECTIVE ACTION REQUEST', 'format': 'A4P',
        'owner': 'QA / Purchasing', 'approved': 'QA Manager',
        'ref_fields': [('SCAR #', 'Supplier'), ('NCR Reference', 'Issue Date')],
        'sections': [
            {'title': 'PROBLEM & CORRECTIVE ACTION', 'type': 'textarea',
             'labels': ['PROBLEM DESCRIPTION (what, when, how many, impact)',
                        'ROOT CAUSE (supplier to complete)',
                        'CORRECTIVE ACTION (supplier to complete)',
                        'VERIFICATION OF EFFECTIVENESS (HESEM to verify)'],
             'rows': 3},
            {'title': 'DISPOSITION', 'type': 'pairs',
             'fields': [('SCAR Status', 'Closure Date')],
            },
        ],
        'approval': ['QA Engineer', 'QA Manager'],
        'notice': 'NOTICE \u2014 Send to supplier within 5 days. Ref: SOP-401. Retain: 10 years.',
    },
    {
        'code': 'FRM-408', 'title': 'REQUIREMENTS FLOW-DOWN CHECKLIST', 'format': 'A4P',
        'owner': 'Purchasing / QA', 'approved': 'QA Manager',
        'ref_fields': [('Supplier', 'PO Number'), ('Part / Process', 'Flow-down Date')],
        'sections': [
            {'title': 'REQUIREMENTS FLOW-DOWN', 'type': 'checklist',
             'items': [
                 (1,'DOC','Drawing / specification attached to PO.','Correct revision confirmed.'),
                 (2,'QUA','Material / process specification referenced.','Spec number on PO.'),
                 (3,'QUA','Inspection / test requirements specified.','Acceptance criteria clear.'),
                 (4,'QUA','Certification requirements (CoC, material cert).','Cert type stated on PO.'),
                 (5,'QUA','Special process requirements flowed down.','Nadcap / customer approval noted.'),
                 (6,'DOC','Packaging and labeling requirements stated.','Handling instructions on PO.'),
                 (7,'QUA','Right of access for customer / regulatory audit.','Clause included in PO terms.'),
                 (8,'QUA','Counterfeit part prevention requirements noted.','AS6174 / customer requirements referenced.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Buyer', 'QA'],
        'notice': 'NOTICE \u2014 Required for every external provider PO. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-409', 'title': 'SUPPLIER AUDIT CHECKLIST', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('Supplier', 'Audit Date'), ('Lead Auditor', 'Audit Scope')],
        'sections': [
            {'title': 'AUDIT EVALUATION', 'type': 'checklist',
             'items': [
                 (1,'QUA','QMS documented and implemented.','ISO/AS cert current or system adequate.'),
                 (2,'QUA','Process controls in place for contracted work.','Parameters monitored and recorded.'),
                 (3,'QUA','Inspection and test capability adequate.','Equipment calibrated, methods defined.'),
                 (4,'QUA','Calibration program current.','Certificates traceable to national standards.'),
                 (5,'QUA','NCR and corrective action process effective.','Evidence of closed CAPAs.'),
                 (6,'HR','Personnel trained and qualified.','Training records available.'),
                 (7,'QUA','Traceability maintained (material, process, lot).','Records link input to output.'),
                 (8,'DOC','Records retained per contract / standard.','Accessible and organized.'),
                 (9,'OPS','Facility and equipment adequate.','Clean, maintained, suitable.'),
                 (10,'QUA','Overall audit conclusion.','APPROVED / CONDITIONAL / REJECTED.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Lead Auditor', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per supplier audit. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-411', 'title': 'OUTSOURCE INCOMING VERIFICATION', 'format': 'A4P',
        'owner': 'QA / Warehouse', 'approved': 'QA',
        'ref_fields': [('Job / WO', 'Supplier'), ('Receipt Date', 'Received by')],
        'sections': [
            {'title': 'INCOMING VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'OPS','Quantity matches PO.','Count verified.'),
                 (2,'QUA','Visual inspection acceptable (no damage, contamination).','Surface condition OK.'),
                 (3,'QUA','Dimensional check (if required by spec).','Key dimensions within tolerance.'),
                 (4,'QUA','Certification / test report received and matches spec.','Cert reviewed and filed.'),
                 (5,'QUA','Marking / identification correct.','Part marking matches PO.'),
                 (6,'QUA','Accept / Reject decision.','Disposition recorded.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Inspector', 'QA'],
        'notice': 'NOTICE \u2014 One form per incoming receipt. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 32,
    },

    # === FRM-500 Series: Production ===
    {
        'code': 'FRM-501', 'title': 'PLANNING RELEASE CHECKLIST', 'format': 'A4P',
        'owner': 'Planning', 'approved': 'Production Director',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Release Date', 'Planner')],
        'sections': [
            {'title': 'RELEASE READINESS', 'type': 'checklist',
             'items': [
                 (1,'DOC','Drawing and job packet complete.','All documents in packet.'),
                 (2,'TEC','Material available (stock or PO confirmed).','Material status verified.'),
                 (3,'TEC','Routing and setup sheet released.','FRM-302 current revision.'),
                 (4,'CAP','Tooling and fixtures available.','Tool list checked.'),
                 (5,'CAP','Machine scheduled, no conflict.','Capacity confirmed.'),
                 (6,'CAP','Outsource lead time fits delivery.','Supplier confirmed.'),
                 (7,'QUA','Inspection plan and gages ready.','Measurement capability confirmed.'),
                 (8,'OPS','Release decision.','RELEASE / HOLD.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Planner', 'Production Director'],
        'notice': 'NOTICE \u2014 One form per job release. Ref: SOP-504. Retain: 10 years.',
        'dv_result_col': 32,
    },
    # FRM-511 already done — skip
    {
        'code': 'FRM-518', 'title': 'WORK TRANSFER VALIDATION', 'format': 'A4P',
        'owner': 'Production / QA', 'approved': 'Production Director',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('From Machine', 'To Machine')],
        'sections': [
            {'title': 'TRANSFER VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'SET','Setup on new machine matches original setup sheet.','FRM-302 parameters replicated.'),
                 (2,'SET','First piece on new machine within tolerance.','All critical dims measured.'),
                 (3,'QUA','Process capability comparable to original machine.','Results within acceptance.'),
                 (4,'SET','Operator qualified on new machine.','Training record current.'),
                 (5,'QUA','Transfer approved, production may continue.','Release decision documented.'),
                 (6,'DOC','Setup sheet updated if permanent transfer.','FRM-302 revised if needed.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Setup Tech', 'QA'],
        'notice': 'NOTICE \u2014 Required when moving job between machines. Ref: SOP-504. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-519', 'title': 'PRE-RUN VERIFICATION', 'format': 'A4P',
        'owner': 'Production', 'approved': 'Production Supervisor',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Machine', 'Operator')],
        'sections': [
            {'title': 'PRE-RUN CHECK', 'type': 'checklist',
             'items': [
                 (1,'DOC','Drawing revision in packet matches released rev.','No obsolete drawing.'),
                 (2,'SET','CNC program revision matches setup sheet.','Program name/rev verified.'),
                 (3,'TOOL','Tooling matches setup sheet tool list.','All tools present and in condition.'),
                 (4,'SET','Routing / operation matches job traveler.','Correct operation sequence.'),
                 (5,'SET','Material matches specification (grade, cert).','Material verified.'),
                 (6,'OPS','Pre-run decision: proceed / hold.','Release or hold with reason.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Operator', 'Supervisor'],
        'notice': 'NOTICE \u2014 Quick check before each run. Ref: SOP-504. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-521', 'title': 'PREVENTIVE MAINTENANCE CHECKLIST', 'format': 'A4P',
        'owner': 'Maintenance', 'approved': 'Workshop Manager',
        'ref_fields': [('Machine ID', 'PM Date'), ('PM Schedule', 'Technician')],
        'sections': [
            {'title': 'PM ITEMS', 'type': 'checklist',
             'items': [
                 (1,'OPS','Lubrication: way covers, slides, spindle.','Levels topped, no leaks.'),
                 (2,'OPS','Coolant: level, concentration, condition.','Within spec, no contamination.'),
                 (3,'OPS','Spindle: runout, vibration, temperature.','Within manufacturer limits.'),
                 (4,'OPS','Axis: backlash, repeatability check.','Within tolerance.'),
                 (5,'OPS','Safety: interlocks, guards, e-stop.','All functional.'),
                 (6,'OPS','Electrical: connections, alarms, display.','No faults or warnings.'),
                 (7,'OPS','Filters: air, oil, coolant replaced if due.','Replacement logged.'),
                 (8,'OPS','Machine released for production.','PM complete, machine OK.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Technician', 'Workshop Manager'],
        'notice': 'NOTICE \u2014 One form per PM event. Ref: SOP-504. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-522', 'title': 'CRASH REPORT', 'format': 'A4P',
        'owner': 'Production / Maintenance', 'approved': 'Production Director',
        'ref_fields': [('Machine ID', 'Date / Time'), ('Job / WO (if applicable)', 'Operator')],
        'sections': [
            {'title': 'EVENT & RESPONSE', 'type': 'textarea',
             'labels': ['EVENT DESCRIPTION (what happened, sequence of events)',
                        'DAMAGE ASSESSMENT (machine, tooling, part, fixture)',
                        'IMMEDIATE CONTAINMENT (what was done to secure)',
                        'ROOT CAUSE (why it happened)',
                        'CORRECTIVE ACTION (prevent recurrence)'],
             'rows': 2},
        ],
        'approval': ['Operator', 'Production Director'],
        'notice': 'NOTICE \u2014 Report within 24 hours. Ref: SOP-504. Retain: 10 years.',
    },

    # === FRM-600 Series: Quality ===
    {
        'code': 'FRM-654', 'title': 'CUSTOMER SATISFACTION SURVEY', 'format': 'A4P',
        'owner': 'Sales / QA', 'approved': 'QA Manager',
        'ref_fields': [('Customer', 'Survey Period'), ('Conducted by', 'Date')],
        'sections': [
            {'title': 'SATISFACTION EVALUATION', 'type': 'checklist',
             'headers': ['#','Cat.','Evaluation Criteria','Rating Guide','Score','Comments'],
             'items': [
                 (1,'QUA','Product quality meets expectations.','1=Poor 2=Fair 3=Good 4=Excellent.'),
                 (2,'OPS','Delivery performance (on-time, complete).','1=Poor 2=Fair 3=Good 4=Excellent.'),
                 (3,'COM','Communication and responsiveness.','1=Poor 2=Fair 3=Good 4=Excellent.'),
                 (4,'COM','Problem resolution effectiveness.','1=Poor 2=Fair 3=Good 4=Excellent.'),
                 (5,'COM','Overall satisfaction and value.','1=Poor 2=Fair 3=Good 4=Excellent.'),
                 (6,'COM','Would recommend HESEM to others?','YES / NO / CONDITIONAL.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Conducted by', 'QA Manager'],
        'notice': 'NOTICE \u2014 Annual or per-customer. Ref: SOP-605. Retain: 5 years.',
        'dv_result_col': 32,
    },

    # === FRM-700 Series: Warehouse & Logistics ===
    {
        'code': 'FRM-702', 'title': 'SHIPPING CHECKLIST', 'format': 'A4P',
        'owner': 'Warehouse', 'approved': 'Warehouse Lead',
        'ref_fields': [('Job / WO', 'Customer'), ('Ship Date', 'Shipped by')],
        'sections': [
            {'title': 'SHIPPING VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'QUA','Quantity matches order and inspection report.','Count verified.'),
                 (2,'QUA','Final inspection passed (FRM-641 attached).','Report in dossier.'),
                 (3,'DOC','CoC / certification package complete.','All required certs present.'),
                 (4,'OPS','Labeling correct (part, qty, PO, customer).','Labels match shipment.'),
                 (5,'OPS','Packaging per customer spec (FRM-707/709).','Packaging checklist passed.'),
                 (6,'DOC','Shipping documents prepared (packing list, BOL).','All docs attached.'),
                 (7,'DOC','Customs / export docs (if international).','Compliance verified.'),
                 (8,'OPS','Release: ready to ship.','All checks passed.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Shipped by', 'Warehouse Lead'],
        'notice': 'NOTICE \u2014 One form per shipment. Ref: SOP-701. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-707', 'title': 'PACKAGING CHECKLIST', 'format': 'A4P',
        'owner': 'Warehouse / Production', 'approved': 'QA',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Pack Date', 'Packed by')],
        'sections': [
            {'title': 'PACKAGING VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'OPS','Parts clean and free of chips / coolant.','Visual inspection passed.'),
                 (2,'OPS','Protective wrap / VCI applied.','Anti-corrosion protection confirmed.'),
                 (3,'OPS','Cushioning / separation adequate.','No part-to-part contact.'),
                 (4,'OPS','Labels applied (part, qty, PO, handling).','All labels correct.'),
                 (5,'OPS','Box / crate appropriate for weight and size.','Structural integrity OK.'),
                 (6,'OPS','Weight recorded (if required).','Weight matches expectation.'),
                 (7,'DOC','Documents enclosed (packing list, CoC copy).','All required docs inside.'),
                 (8,'OPS','Box sealed and ready for shipping.','Packaging complete.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Packed by', 'QA'],
        'notice': 'NOTICE \u2014 One form per packaging event. Ref: SOP-701. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-709', 'title': 'CLEAN PACKAGING CHECKLIST', 'format': 'A4P',
        'owner': 'Production / QA', 'approved': 'QA Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Pack Date', 'Packed by')],
        'sections': [
            {'title': 'CLEAN PACKAGING VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'QUA','Cleanroom / clean area gowning completed.','Gloves, smock, head cover.'),
                 (2,'QUA','Work surface clean and particle-free.','Wipe-down verified.'),
                 (3,'QUA','Parts cleanliness verified (FRM-711).','Cleanliness form attached.'),
                 (4,'QUA','Clean packaging material used (specified grade).','No contamination from packaging.'),
                 (5,'QUA','Double bagging completed (if required).','Inner + outer bag sealed.'),
                 (6,'QUA','N2 purge applied (if required).','Purge confirmed.'),
                 (7,'QUA','Labels applied (clean, no adhesive contamination).','Clean labels only.'),
                 (8,'QUA','Sealed and ready for controlled shipping.','No exposure to particles.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Packed by', 'QA Manager'],
        'notice': 'NOTICE \u2014 Semiconductor clean parts only. Ref: SOP-701. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-711', 'title': 'CLEANLINESS VERIFICATION FORM', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Verification Date', 'Inspector')],
        'sections': [
            {'title': 'CLEANLINESS CHECK', 'type': 'checklist',
             'items': [
                 (1,'QUA','Visual clean: no chips, oil, residue, fingerprints.','100% surface inspection.'),
                 (2,'QUA','Particle count within spec (if applicable).','Particle counter reading recorded.'),
                 (3,'QUA','Residue test passed (if applicable).','NVR / contact angle test.'),
                 (4,'QUA','Rinse water test passed (if applicable).','Conductivity / particle count.'),
                 (5,'QUA','UV check passed (if applicable).','No fluorescence detected.'),
                 (6,'QUA','Overall cleanliness: ACCEPT / REJECT.','Disposition recorded.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Inspector', 'QA Manager'],
        'notice': 'NOTICE \u2014 Semiconductor clean parts only. Ref: SOP-701. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-715', 'title': 'VACUUM CLEAN BUILD & BAGGING', 'format': 'A4P',
        'owner': 'Production / QA', 'approved': 'QA Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Build Date', 'Technician')],
        'sections': [
            {'title': 'VACUUM BUILD VERIFICATION', 'type': 'checklist',
             'items': [
                 (1,'QUA','Cleanliness verification passed (FRM-711).','Clean form attached.'),
                 (2,'QUA','Glove protocol followed (lint-free, powder-free).','Correct glove type used.'),
                 (3,'QUA','Assembly in clean area / laminar flow bench.','Environment controlled.'),
                 (4,'QUA','Vacuum-compatible bagging material used.','Material grade verified.'),
                 (5,'QUA','Vacuum sealed (no leaks).','Seal integrity confirmed.'),
                 (6,'QUA','Identification label applied (clean method).','No contamination from label.'),
                 (7,'QUA','Leak check passed (if applicable).','Test result recorded.'),
                 (8,'QUA','Released for shipping / storage.','Final acceptance.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Technician', 'QA Manager'],
        'notice': 'NOTICE \u2014 Vacuum-compatible parts only. Ref: SOP-701. Retain: 10 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-721', 'title': 'FOD LINE CLEARANCE & TOOL ACCOUNTABILITY', 'format': 'A4P',
        'owner': 'Production', 'approved': 'Production Supervisor',
        'ref_fields': [('Work Area / Machine', 'Clearance Date'), ('Job / WO (completed)', 'Cleared by')],
        'sections': [
            {'title': 'FOD CLEARANCE', 'type': 'checklist',
             'items': [
                 (1,'OPS','All tools accounted for (count in = count out).','Tool count verified.'),
                 (2,'OPS','All parts accounted for (good + scrap + WIP).','Part count matches.'),
                 (3,'OPS','Work area free of debris, chips, rags.','Visual inspection passed.'),
                 (4,'OPS','Machine table and enclosure clean.','No foreign objects.'),
                 (5,'OPS','Tooling stored in designated location.','Nothing left in machine.'),
                 (6,'OPS','Area ready for next job.','FOD-free clearance complete.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Cleared by', 'Supervisor'],
        'notice': 'NOTICE \u2014 Between every job changeover. Ref: SOP-701. Retain: 5 years.',
        'dv_result_col': 32,
    },

    # === FRM-800 Series: HR ===
    {
        'code': 'FRM-803', 'title': 'OJT CHECKLIST', 'format': 'A4P',
        'owner': 'HR / Department', 'approved': 'Department Manager',
        'ref_fields': [('Trainee Name', 'Skill / Task'), ('Trainer', 'Training Period')],
        'sections': [
            {'title': 'OJT PROGRESSION', 'type': 'checklist',
             'items': [
                 (1,'HR','Demonstration by trainer completed.','Trainee observed full process.'),
                 (2,'HR','Guided practice under supervision.','Trainee performed with assistance.'),
                 (3,'HR','Independent practice under observation.','Trainee performed, trainer observed.'),
                 (4,'HR','Independent work without supervision.','Trainee performed alone successfully.'),
                 (5,'HR','Competence assessment passed.','Written or practical test passed.'),
                 (6,'HR','Certification issued (FRM-805).','Skill level recorded in matrix.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Trainer', 'Department Manager'],
        'notice': 'NOTICE \u2014 One form per trainee per skill. Ref: SOP-801. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-821', 'title': 'INVOICE REQUEST', 'format': 'A4P',
        'owner': 'Sales / Finance', 'approved': 'Sales Manager',
        'ref_fields': [('Job / WO', 'Customer'), ('Invoice Amount', 'Payment Terms'), ('Customer PO #', 'Ship Date')],
        'sections': [],
        'approval': ['Requested by', 'Sales Manager'],
        'notice': 'NOTICE \u2014 Ref: SOP-801. Retain: 7 years.',
    },

    # === FRM-900 Series: Performance ===
    {
        'code': 'FRM-901', 'title': 'INTERNAL AUDIT CHECKLIST', 'format': 'A4P',
        'owner': 'QA / QMS', 'approved': 'QA Manager',
        'ref_fields': [('Audit # / Scope', 'Audit Date'), ('Lead Auditor', 'Auditee / Department')],
        'sections': [
            {'title': 'AUDIT EVALUATION', 'type': 'checklist',
             'headers': ['#','Cat.','Audit Question','Expected Evidence','Finding','Auditor'],
             'items': [
                 (1,'MGT','Context and interested parties reviewed (cl.4)?','Records of context analysis current.'),
                 (2,'MGT','Quality policy communicated and understood (cl.5)?','Personnel can explain relevance.'),
                 (3,'MGT','Risks and opportunities addressed (cl.6)?','Risk register current, actions tracked.'),
                 (4,'HR','Competence determined and training effective (cl.7)?','Training records, skill matrix current.'),
                 (5,'OPS','Customer requirements reviewed before acceptance (cl.8.2)?','Contract review records exist.'),
                 (6,'OPS','Production under controlled conditions (cl.8.5)?','Setup records, work instructions followed.'),
                 (7,'QUA','Inspection and test at appropriate stages (cl.8.6)?','Inspection records, release evidence.'),
                 (8,'QUA','Nonconformity handled and corrective action taken (cl.10)?','NCR/CAPA records, effectiveness verified.'),
                 (9,'QUA','Monitoring, measurement, analysis performed (cl.9.1)?','KPI data, trend analysis available.'),
                 (10,'MGT','Management review conducted with required inputs (cl.9.3)?','Minutes with decisions and actions.'),
             ], 'blank_rows': 4},
        ],
        'approval': ['Lead Auditor', 'QA Manager'],
        'notice': 'NOTICE \u2014 Per audit schedule. Ref: SOP-901. Retain: 10 years.',
        'dv_result_col': 32,
        'dv_formula': '=LISTS!$A$2:$A$5',
        'cf_pass': ['"C"'],  # Conformity
        'cf_hold': ['"OFI"'],  # Opportunity for Improvement
        'cf_fail': ['"NC"'],  # Nonconformity
    },
    {
        'code': 'FRM-902', 'title': 'LAYERED PROCESS AUDIT', 'format': 'A4P',
        'owner': 'Production / QA', 'approved': 'Production Director',
        'ref_fields': [('Area / Machine', 'Audit Date'), ('Auditor', 'Shift')],
        'sections': [
            {'title': 'PROCESS AUDIT', 'type': 'checklist',
             'items': [
                 (1,'OPS','5S standards maintained at workstation.','Clean, organized, labeled.'),
                 (2,'OPS','Work instruction available and followed.','Operator using current WI.'),
                 (3,'QUA','Gages calibrated and current (sticker check).','No overdue gages in use.'),
                 (4,'QUA','First piece / setup verification completed.','FRM-511 on file for current job.'),
                 (5,'QUA','SPC charts updated (if applicable).','Data current, no out-of-control.'),
                 (6,'QUA','NCR / hold procedures understood.','Operator can explain HOLD process.'),
                 (7,'SAF','Safety equipment in place and used.','PPE, guards, e-stops functional.'),
                 (8,'OPS','Overall area compliance.','PASS / FAIL with comments.'),
             ], 'blank_rows': 4},
        ],
        'approval': ['Auditor', 'Production Director'],
        'notice': 'NOTICE \u2014 Weekly per area. Ref: SOP-901. Retain: 10 years.',
        'dv_result_col': 32,
    },
]
