# -*- coding: utf-8 -*-
"""
WAVE 2: TYPE B REPORT / EVENT FORMS — 15 forms
Pattern: Ref + Text areas / scoring + Disposition + Approval
"""

WAVE2 = [
    {
        'code': 'FRM-121', 'title': 'CONTEXT ANALYSIS  SWOT / PESTLE', 'format': 'A4L',
        'owner': 'QA / QMS', 'approved': 'General Manager',
        'ref_fields': [('Analysis Period', 'Review Date'), ('Prepared by', 'Next Review Due')],
        'sections': [
            {'title': 'SWOT ANALYSIS', 'type': 'textarea',
             'labels': ['STRENGTHS (internal capabilities that support QMS objectives)',
                        'WEAKNESSES (internal limitations that hinder QMS objectives)',
                        'OPPORTUNITIES (external factors that could benefit the organization)',
                        'THREATS (external factors that could harm the organization)'],
             'rows': 3},
            {'title': 'KEY ACTIONS', 'type': 'pairs',
             'fields': [('Priority Action 1', 'Owner / Due Date'), ('Priority Action 2', 'Owner / Due Date'), ('Priority Action 3', 'Owner / Due Date')],
            },
        ],
        'approval': ['Prepared by', 'General Manager'],
        'notice': 'NOTICE \u2014 Annual review minimum. Ref: SOP-101. Retain: 10 years.',
    },
    {
        'code': 'FRM-124', 'title': 'CLIMATE CHANGE ASSESSMENT', 'format': 'A4P',
        'owner': 'QA / QMS', 'approved': 'General Manager',
        'ref_fields': [('Assessment Period', 'Assessment Date'), ('Assessed by', 'Next Review Due')],
        'sections': [
            {'title': 'CLIMATE CHANGE IMPACT ASSESSMENT', 'type': 'textarea',
             'labels': ['IDENTIFIED CLIMATE RISKS (physical, regulatory, supply chain)',
                        'IMPACT ON QMS AND OPERATIONS',
                        'ACTIONS TO ADDRESS IDENTIFIED RISKS'],
             'rows': 3},
        ],
        'approval': ['Assessed by', 'General Manager'],
        'notice': 'NOTICE \u2014 Annual. ISO 9001:2015 Amendment 1 (2024). Ref: SOP-101. Retain: 10 years.',
    },
    {
        'code': 'FRM-161', 'title': 'ENGINEERING CHANGE REQUEST / ORDER', 'format': 'A4P',
        'owner': 'Engineering', 'approved': 'Engineering Manager',
        'ref_fields': [('ECR/ECO #', 'Part No. / Revision'), ('Requested by', 'Date')],
        'sections': [
            {'title': 'CHANGE DETAIL', 'type': 'textarea',
             'labels': ['DESCRIPTION OF CHANGE (what is changing and why)',
                        'IMPACT ASSESSMENT (affected parts, processes, documents, inventory)',
                        'IMPLEMENTATION PLAN (steps, timeline, responsible)'],
             'rows': 3},
            {'title': 'DISPOSITION', 'type': 'pairs',
             'fields': [('ECR/ECO Decision', 'Effective Date'), ('Customer Notification Required?', 'Implementation Status')],
            },
        ],
        'approval': ['Requested by', 'Engineering Mgr', 'QA'],
        'notice': 'NOTICE \u2014 One form per engineering change. Ref: SOP-101. Retain: 10 years.',
    },
    {
        'code': 'FRM-181', 'title': 'BUSINESS DISRUPTION EVENT LOG', 'format': 'A4P',
        'owner': 'General Manager', 'approved': 'General Manager',
        'ref_fields': [('Event #', 'Event Date'), ('Reported by', 'Severity')],
        'sections': [
            {'title': 'EVENT & RECOVERY', 'type': 'textarea',
             'labels': ['EVENT DESCRIPTION (what happened, timeline, scope)',
                        'IMPACT ON OPERATIONS (production, delivery, quality, customers)',
                        'RECOVERY ACTIONS TAKEN',
                        'LESSONS LEARNED / PREVENTION MEASURES'],
             'rows': 3},
            {'title': 'STATUS', 'type': 'pairs',
             'fields': [('Recovery Status', 'Full Recovery Date')],
            },
        ],
        'approval': ['Reported by', 'General Manager'],
        'notice': 'NOTICE \u2014 One form per event. Ref: SOP-101. Retain: 10 years.',
    },
    {
        'code': 'FRM-402', 'title': 'SUPPLIER EVALUATION FORM', 'format': 'A4P',
        'owner': 'QA / Purchasing', 'approved': 'QA Manager',
        'ref_fields': [('Supplier Name', 'Evaluation Date'), ('Evaluator', 'Process / Service Provided')],
        'sections': [
            {'title': 'EVALUATION CRITERIA', 'type': 'checklist',
             'headers': ['#','Cat.','Evaluation Criteria','Rating Guide','Score','Comments'],
             'items': [
                 (1,'QUA','Quality system (ISO/AS cert or adequate controls).','0=None 1=Basic 2=Good 3=Certified.'),
                 (2,'QUA','Product/service quality history.','0=Poor 1=Fair 2=Good 3=Excellent.'),
                 (3,'CAP','Delivery performance (on-time, lead time).','0=Poor 1=Fair 2=Good 3=Excellent.'),
                 (4,'CAP','Technical capability for required process.','0=Cannot 1=Limited 2=Good 3=Expert.'),
                 (5,'COM','Communication and responsiveness.','0=Poor 1=Fair 2=Good 3=Excellent.'),
                 (6,'COM','Pricing competitiveness.','0=High 1=Fair 2=Good 3=Best value.'),
             ], 'blank_rows': 2},
            {'title': 'DECISION', 'type': 'pairs',
             'fields': [('Total Score / Max', 'Approval Decision'), ('Conditions (if conditional)', 'Next Review Due')],
            },
        ],
        'approval': ['Evaluator', 'QA Manager'],
        'notice': 'NOTICE \u2014 Required before adding to APL. Ref: SOP-401. Retain: 10 years.',
        'dv_result_col': 44 if False else 32,
    },
    {
        'code': 'FRM-514', 'title': 'SMED / CHANGEOVER RECORD', 'format': 'A4P',
        'owner': 'Production', 'approved': 'Production Director',
        'ref_fields': [('Machine ID', 'Date'), ('From Job / To Job', 'Operator')],
        'sections': [
            {'title': 'CHANGEOVER STEPS', 'type': 'checklist',
             'headers': ['#','Cat.','Changeover Step','Int/Ext','Time (min)','Owner'],
             'items': [
                 (1,'SET','Remove previous tooling / fixture.','INT.'),
                 (2,'SET','Clean machine table and enclosure.','INT.'),
                 (3,'SET','Install new fixture / workholding.','INT.'),
                 (4,'SET','Load new CNC program.','INT.'),
                 (5,'SET','Install and set new tools.','INT.'),
                 (6,'SET','Set work offsets and verify.','INT.'),
                 (7,'SET','Run first piece and measure.','INT.'),
                 (8,'SET','Adjust if needed, confirm production ready.','INT.'),
             ], 'blank_rows': 4},
            {'title': 'SUMMARY', 'type': 'pairs',
             'fields': [('Total Changeover Time (min)', 'Target Time (min)'), ('Internal Time', 'External Time')],
            },
        ],
        'approval': ['Operator', 'Supervisor'],
        'notice': 'NOTICE \u2014 Track changeover for continuous improvement. Ref: SOP-504. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-651', 'title': 'NCR REPORT', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('NCR ID', 'Job / WO'), ('Date / Source', 'Severity / Suspect Qty')],
        'sections': [
            {'title': 'NONCONFORMITY DETAIL', 'type': 'textarea',
             'labels': ['DESCRIPTION (what is wrong, requirement reference)',
                        'OBJECTIVE EVIDENCE / RISK TO DOWNSTREAM'],
             'rows': 3},
            {'title': 'CONTAINMENT / DISPOSITION', 'type': 'checklist',
             'headers': ['#','Cat.','Containment / Disposition Item','Requirement / Evidence','Status','Owner'],
             'items': [
                 (1,'CON','Suspect material segregated and tagged HOLD.','Physical isolation confirmed.'),
                 (2,'CON','Downstream / shipped product assessed.','Affected lots traced.'),
                 (3,'CON','WIP stopped or rerouted.','Production notified.'),
                 (4,'DIS','Disposition decision recorded.','USE-AS-IS / REWORK / SCRAP / RTV.'),
                 (5,'DIS','Rework instruction issued (if applicable).','Method and re-inspect defined.'),
             ], 'blank_rows': 3},
            {'title': 'CLOSURE', 'type': 'pairs',
             'fields': [('Disposition', 'Linked CAPA (if systemic)'), ('Closeout Status', 'Closure Date')],
            },
        ],
        'approval': ['Prepared by', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per NCR event. Ref: SOP-605. Retain: 10 years.',
        'dv_result_col': 32,
        'dv_formula': '=LISTS!$C$2:$C$5',
        'cf_pass': ['"CLOSED"'], 'cf_hold': ['"IN PROGRESS"'], 'cf_fail': ['"OPEN"'],
    },
    {
        'code': 'FRM-652', 'title': 'CAPA / 8D REPORT', 'format': 'A4L',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('CAPA #', 'Source NCR / Audit #'), ('Date Opened', 'Target Close Date')],
        'sections': [
            {'title': '8D CORRECTIVE ACTION', 'type': 'textarea',
             'labels': ['D1 \u2014 TEAM (names and roles)',
                        'D2 \u2014 PROBLEM DESCRIPTION (5W1H: what, where, when, how big)',
                        'D3 \u2014 INTERIM CONTAINMENT (immediate actions to protect customer)',
                        'D4 \u2014 ROOT CAUSE (use 5-Why; fishbone only if systemic)',
                        'D5 \u2014 PERMANENT CORRECTIVE ACTION (what will prevent recurrence)',
                        'D6 \u2014 IMPLEMENTATION & VERIFICATION (when, who, evidence)',
                        'D7 \u2014 PREVENTIVE ACTION / SYSTEM CHANGES',
                        'D8 \u2014 CLOSURE & RECOGNITION'],
             'rows': 2},
            {'title': 'EFFECTIVENESS', 'type': 'pairs',
             'fields': [('Verification Method', 'Verification Date'), ('Recurrence Check (30/60/90 days)', 'CAPA Status')],
            },
        ],
        'approval': ['CAPA Owner', 'QA Manager'],
        'notice': 'NOTICE \u2014 One form per CAPA. Ref: SOP-605. Retain: 10 years.',
    },
    {
        'code': 'FRM-653', 'title': 'A3 PDCA PROBLEM SOLVING', 'format': 'A4L',
        'owner': 'QA / Engineering', 'approved': 'Department Manager',
        'ref_fields': [('Topic / Problem', 'Date'), ('Owner', 'Target Completion')],
        'sections': [
            {'title': 'PLAN \u2014 DO \u2014 CHECK \u2014 ACT', 'type': 'textarea',
             'labels': ['PLAN: Define problem, analyze current state, set target, identify root cause',
                        'DO: Implement countermeasures, execute plan',
                        'CHECK: Verify results vs target, measure effectiveness',
                        'ACT: Standardize successful countermeasures, plan next cycle'],
             'rows': 4},
        ],
        'approval': ['Owner', 'Manager'],
        'notice': 'NOTICE \u2014 Lean problem-solving tool. Ref: SOP-605. Retain: 5 years.',
    },
    {
        'code': 'FRM-712', 'title': 'HELIUM LEAK TEST RECORD', 'format': 'A4P',
        'owner': 'QA', 'approved': 'QA Manager',
        'ref_fields': [('Job / WO', 'Part No. / Revision'), ('Test Date', 'Operator')],
        'sections': [
            {'title': 'TEST PARAMETERS & RESULTS', 'type': 'pairs',
             'fields': [('Leak Detector ID', 'Calibration Due'), ('Test Method (vacuum/sniff/spray)', 'Acceptance Limit'),
                        ('Background Rate', 'Measured Leak Rate'), ('Test Duration (min)', 'Result: PASS / FAIL')],
            },
        ],
        'approval': ['Operator', 'QA'],
        'notice': 'NOTICE \u2014 Vacuum-compatible parts. Ref: SOP-701. Retain: 10 years.',
    },
    {
        'code': 'FRM-714', 'title': 'ULTRASONIC CLEANING BATCH RECORD', 'format': 'A4P',
        'owner': 'Production', 'approved': 'QA',
        'ref_fields': [('Batch #', 'Cleaning Date'), ('Job / WO', 'Operator')],
        'sections': [
            {'title': 'PROCESS PARAMETERS', 'type': 'pairs',
             'fields': [('Solution Type / Concentration', 'Temperature'), ('Frequency (kHz)', 'Duration (min)'),
                        ('Rinse Method', 'Drying Method'), ('Cleanliness Verification', 'Result: PASS / FAIL')],
            },
        ],
        'approval': ['Operator', 'QA'],
        'notice': 'NOTICE \u2014 One form per cleaning batch. Ref: SOP-701. Retain: 10 years.',
    },
    {
        'code': 'FRM-801', 'title': 'TRAINING PLAN', 'format': 'A4L',
        'owner': 'HR', 'approved': 'General Manager',
        'ref_fields': [('Plan Year / Period', 'Prepared by'), ('Department', 'Approved Date')],
        'sections': [
            {'title': 'TRAINING SCHEDULE', 'type': 'checklist',
             'headers': ['#','Cat.','Training Topic','Target Audience / Method','Planned Date','Status'],
             'items': [
                 (1,'HR','ISO 9001 / AS9100D awareness.','All staff / classroom.'),
                 (2,'HR','Quality policy and objectives.','All staff / meeting.'),
                 (3,'HR','Job-specific skills (CNC, inspection, etc.).','Operators / OJT.'),
                 (4,'SAF','Safety and emergency procedures.','All staff / drill.'),
                 (5,'HR','New employee orientation.','New hires / onboarding.'),
                 (6,'HR','Customer-specific requirements (CSR).','Relevant staff / briefing.'),
             ], 'blank_rows': 6},
        ],
        'approval': ['HR Manager', 'General Manager'],
        'notice': 'NOTICE \u2014 Annual plan. Ref: SOP-801. Retain: 5 years.',
        'dv_result_col': 44 if False else 32,
    },
    {
        'code': 'FRM-804', 'title': 'COMPETENCE ASSESSMENT', 'format': 'A4P',
        'owner': 'HR / Department', 'approved': 'Department Manager',
        'ref_fields': [('Employee Name', 'Position / Role'), ('Assessment Date', 'Assessor')],
        'sections': [
            {'title': 'COMPETENCE EVALUATION', 'type': 'checklist',
             'headers': ['#','Cat.','Competence Area','Assessment Method','Result','Assessor'],
             'items': [
                 (1,'HR','Technical skill for assigned tasks.','Practical demonstration.'),
                 (2,'HR','Knowledge of applicable procedures / WI.','Verbal or written test.'),
                 (3,'HR','Quality awareness (NCR, hold, escalation).','Scenario questions.'),
                 (4,'HR','Safety awareness and PPE compliance.','Observation.'),
                 (5,'HR','Equipment operation (machines, gages).','Practical demonstration.'),
                 (6,'HR','Overall competence decision.','COMPETENT / NEEDS TRAINING / NOT YET COMPETENT.'),
             ], 'blank_rows': 2},
        ],
        'approval': ['Assessor', 'Department Manager'],
        'notice': 'NOTICE \u2014 Per employee, annual or on change. Ref: SOP-801. Retain: 5 years.',
        'dv_result_col': 32,
    },
    {
        'code': 'FRM-808', 'title': 'PERFORMANCE REVIEW', 'format': 'A4P',
        'owner': 'HR', 'approved': 'Department Manager',
        'ref_fields': [('Employee Name', 'Position / Role'), ('Review Period', 'Reviewer')],
        'sections': [
            {'title': 'PERFORMANCE & DEVELOPMENT', 'type': 'textarea',
             'labels': ['KEY ACHIEVEMENTS THIS PERIOD',
                        'AREAS FOR IMPROVEMENT',
                        'DEVELOPMENT PLAN / TRAINING NEEDS',
                        'GOALS FOR NEXT PERIOD'],
             'rows': 2},
            {'title': 'RATING', 'type': 'pairs',
             'fields': [('Overall Rating', 'Employee Comments')],
            },
        ],
        'approval': ['Employee', 'Reviewer', 'Manager'],
        'notice': 'NOTICE \u2014 Annual or semi-annual. Ref: SOP-801. Retain: 5 years.',
    },
    {
        'code': 'FRM-811', 'title': 'INCIDENT REPORT', 'format': 'A4P',
        'owner': 'EHS / HR', 'approved': 'General Manager',
        'ref_fields': [('Incident #', 'Date / Time'), ('Location', 'Reported by')],
        'sections': [
            {'title': 'INCIDENT DETAIL & INVESTIGATION', 'type': 'textarea',
             'labels': ['DESCRIPTION OF INCIDENT (what happened, who involved, injuries)',
                        'IMMEDIATE ACTIONS TAKEN (first aid, containment, notification)',
                        'ROOT CAUSE INVESTIGATION',
                        'CORRECTIVE / PREVENTIVE ACTIONS'],
             'rows': 3},
            {'title': 'STATUS', 'type': 'pairs',
             'fields': [('Incident Classification', 'Status / Closure Date')],
            },
        ],
        'approval': ['Reported by', 'EHS', 'General Manager'],
        'notice': 'NOTICE \u2014 Report within 24 hours. Ref: SOP-801. Retain: 10 years.',
    },
    {
        'code': 'FRM-911', 'title': 'MANAGEMENT REVIEW MINUTES', 'format': 'A4L',
        'owner': 'QA / QMS', 'approved': 'General Manager',
        'ref_fields': [('Meeting Date', 'Chair'), ('Attendees', 'Next Review Due')],
        'sections': [
            {'title': 'REVIEW INPUTS (ISO 9.3.2)', 'type': 'textarea',
             'labels': ['STATUS OF ACTIONS FROM PREVIOUS REVIEW',
                        'QMS PERFORMANCE: Quality KPIs, NCR trends, CAPA status, audit results',
                        'CUSTOMER FEEDBACK: satisfaction, complaints, delivery performance',
                        'RESOURCE ADEQUACY: people, equipment, infrastructure, training',
                        'RISKS AND OPPORTUNITIES: effectiveness of actions taken'],
             'rows': 2},
            {'title': 'REVIEW OUTPUTS / DECISIONS (ISO 9.3.3)', 'type': 'textarea',
             'labels': ['IMPROVEMENT DECISIONS',
                        'RESOURCE DECISIONS',
                        'ACTION ITEMS (action / owner / due date)'],
             'rows': 3},
        ],
        'approval': ['QA Manager', 'General Manager'],
        'notice': 'NOTICE \u2014 Minimum semi-annual. Ref: SOP-901. Retain: 10 years.',
    },
]
