export const registryResearchAnchors = [
  {
    key: 'microsoft_dynamics_quality',
    label: 'Microsoft Dynamics 365 Supply Chain Quality Management',
    url: 'https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/quality-management-processes',
    focus: ['quality orders', 'associations', 'sample management', 'blocking rules'],
  },
  {
    key: 'oracle_quality_management',
    label: 'Oracle Fusion Cloud Quality Management',
    url: 'https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25d/fauqm/using-quality-management.pdf',
    focus: ['inspection characteristics', 'inspection plans', 'quality issues', 'action plans'],
  },
  {
    key: 'sap_quality_management',
    label: 'SAP Quality Management',
    url: 'https://help.sap.com/doc/9364dd64548a4ef9a21f0c987e968517/6.00.29/en-US/Chapter_15__QM_Quality_ManagementE_%282%29.PDF',
    focus: ['inspection lots', 'inspection results', 'quality notifications', 'certificates'],
  },
  {
    key: 'epicor_cpc',
    label: 'Epicor Connected Process Control',
    url: 'https://www.epicor.com/en-us/resources/library/manufacturing/brochure-connected-process-control/',
    focus: ['connected work instructions', 'quality checks', 'digital execution', 'operator guidance'],
  },
  {
    key: 'iaqg_apqp_ppap',
    label: 'IAQG APQP / PPAP',
    url: 'https://iaqg.org/wp-content/uploads/2019/10/planning-for-quality-QP-article.pdf',
    focus: ['phase gates', 'deliverables', 'PPAP readiness', 'cross-functional reviews'],
  },
  {
    key: 'nadcap_pri',
    label: 'PRI Nadcap',
    url: 'https://www.p-r-i.org/nadcap/getting-started',
    focus: ['special processes', 'accreditation workflow', 'audit evidence', 'supplier controls'],
  },
  {
    key: 'bis_eccn',
    label: 'BIS ECCN Resources',
    url: 'https://www.bis.gov/media/1326',
    focus: ['ECCN classification', 'EAR controls', 'export classification workflow'],
  },
  {
    key: 'opcf_opcua',
    label: 'OPC Foundation OPC UA',
    url: 'https://opcfoundation.org/wp-content/uploads/2014/03/OPC_UA_I_4.0_Pioneer_US_v2.pdf',
    focus: ['interoperability', 'industrial connectivity', 'companion specifications', 'machine data models'],
  },
  {
    key: 'espr_dpp',
    label: 'EU Digital Product Passport / ESPR',
    url: 'https://webgate.ec.europa.eu/circabc-ewpp/d/d/workspace/SpacesStore/c03929dd-9d98-4472-bc13-ab118ac6973f/download',
    focus: ['digital product passport', 'sustainability attributes', 'traceability', 'product-level disclosures'],
  },
];

export const extraEnums = {
  inspection_level: {
    label: 'Inspection Level',
    labelEn: 'Inspection Level',
    options: [
      { value: 'I', label: 'Level I', labelEn: 'Level I', color: '#94a3b8' },
      { value: 'II', label: 'Level II', labelEn: 'Level II', color: '#3b82f6' },
      { value: 'III', label: 'Level III', labelEn: 'Level III', color: '#8b5cf6' },
      { value: 'S1', label: 'Special S1', labelEn: 'Special S1', color: '#10b981' },
      { value: 'S2', label: 'Special S2', labelEn: 'Special S2', color: '#0ea5e9' },
      { value: 'S3', label: 'Special S3', labelEn: 'Special S3', color: '#f59e0b' },
      { value: 'S4', label: 'Special S4', labelEn: 'Special S4', color: '#ef4444' },
    ],
  },
  export_control: {
    label: 'Export Control',
    labelEn: 'Export Control',
    options: [
      { value: 'not_controlled', label: 'Not Controlled', labelEn: 'Not Controlled', color: '#94a3b8' },
      { value: 'ear99', label: 'EAR99', labelEn: 'EAR99', color: '#3b82f6' },
      { value: 'eccn', label: 'ECCN', labelEn: 'ECCN', color: '#8b5cf6' },
      { value: 'itar', label: 'ITAR', labelEn: 'ITAR', color: '#ef4444' },
      { value: 'dual_use', label: 'Dual Use', labelEn: 'Dual Use', color: '#f59e0b' },
    ],
  },
  nadcap_process: {
    label: 'Nadcap Process',
    labelEn: 'Nadcap Process',
    options: [
      { value: 'heat_treat', label: 'Heat Treat', labelEn: 'Heat Treat', color: '#ef4444' },
      { value: 'chemical_processing', label: 'Chemical Processing', labelEn: 'Chemical Processing', color: '#3b82f6' },
      { value: 'coatings', label: 'Coatings', labelEn: 'Coatings', color: '#8b5cf6' },
      { value: 'ndt', label: 'NDT', labelEn: 'NDT', color: '#10b981' },
      { value: 'welding', label: 'Welding', labelEn: 'Welding', color: '#f59e0b' },
      { value: 'shot_peen', label: 'Shot Peen', labelEn: 'Shot Peen', color: '#06b6d4' },
    ],
  },
  fulfillment_status: {
    label: 'Fulfillment Status',
    labelEn: 'Fulfillment Status',
    options: [
      { value: 'planning', label: 'Planning', labelEn: 'Planning', color: '#94a3b8' },
      { value: 'ready_to_release', label: 'Ready to Release', labelEn: 'Ready to Release', color: '#3b82f6' },
      { value: 'in_process', label: 'In Process', labelEn: 'In Process', color: '#f59e0b' },
      { value: 'pending_shipment', label: 'Pending Shipment', labelEn: 'Pending Shipment', color: '#8b5cf6' },
      { value: 'shipped', label: 'Shipped', labelEn: 'Shipped', color: '#10b981' },
      { value: 'closed', label: 'Closed', labelEn: 'Closed', color: '#6b7280' },
      { value: 'on_hold', label: 'On Hold', labelEn: 'On Hold', color: '#ef4444' },
    ],
  },
  contract_review_status: {
    label: 'Contract Review Status',
    labelEn: 'Contract Review Status',
    options: [
      { value: 'pending', label: 'Pending', labelEn: 'Pending', color: '#94a3b8' },
      { value: 'in_review', label: 'In Review', labelEn: 'In Review', color: '#3b82f6' },
      { value: 'approved', label: 'Approved', labelEn: 'Approved', color: '#10b981' },
      { value: 'conditional', label: 'Conditional', labelEn: 'Conditional', color: '#f59e0b' },
      { value: 'rejected', label: 'Rejected', labelEn: 'Rejected', color: '#ef4444' },
    ],
  },
  sync_status: {
    label: 'Sync Status',
    labelEn: 'Sync Status',
    options: [
      { value: 'queued', label: 'Queued', labelEn: 'Queued', color: '#94a3b8' },
      { value: 'running', label: 'Running', labelEn: 'Running', color: '#3b82f6' },
      { value: 'success', label: 'Success', labelEn: 'Success', color: '#10b981' },
      { value: 'partial', label: 'Partial', labelEn: 'Partial', color: '#f59e0b' },
      { value: 'failed', label: 'Failed', labelEn: 'Failed', color: '#ef4444' },
    ],
  },
  inspection_type: {
    label: 'Inspection Type',
    labelEn: 'Inspection Type',
    options: [
      { value: 'receiving', label: 'Receiving', labelEn: 'Receiving', color: '#3b82f6' },
      { value: 'first_article', label: 'First Article', labelEn: 'First Article', color: '#8b5cf6' },
      { value: 'in_process', label: 'In Process', labelEn: 'In Process', color: '#f59e0b' },
      { value: 'final', label: 'Final', labelEn: 'Final', color: '#10b981' },
      { value: 'dock_audit', label: 'Dock Audit', labelEn: 'Dock Audit', color: '#06b6d4' },
    ],
  },
  sampling_plan: {
    label: 'Sampling Plan',
    labelEn: 'Sampling Plan',
    options: [
      { value: '100_percent', label: '100 Percent', labelEn: '100 Percent', color: '#ef4444' },
      { value: 'ansi_z14', label: 'ANSI Z1.4', labelEn: 'ANSI Z1.4', color: '#3b82f6' },
      { value: 'c_zero', label: 'C = 0', labelEn: 'C = 0', color: '#10b981' },
      { value: 'skip_lot', label: 'Skip Lot', labelEn: 'Skip Lot', color: '#8b5cf6' },
      { value: 'reduced', label: 'Reduced', labelEn: 'Reduced', color: '#f59e0b' },
    ],
  },
  fai_status: {
    label: 'FAI Status',
    labelEn: 'FAI Status',
    options: [
      { value: 'planned', label: 'Planned', labelEn: 'Planned', color: '#94a3b8' },
      { value: 'in_work', label: 'In Work', labelEn: 'In Work', color: '#3b82f6' },
      { value: 'awaiting_review', label: 'Awaiting Review', labelEn: 'Awaiting Review', color: '#f59e0b' },
      { value: 'approved', label: 'Approved', labelEn: 'Approved', color: '#10b981' },
      { value: 'rejected', label: 'Rejected', labelEn: 'Rejected', color: '#ef4444' },
    ],
  },
  ppap_status: {
    label: 'PPAP Status',
    labelEn: 'PPAP Status',
    options: [
      { value: 'planning', label: 'Planning', labelEn: 'Planning', color: '#94a3b8' },
      { value: 'collecting', label: 'Collecting Evidence', labelEn: 'Collecting Evidence', color: '#3b82f6' },
      { value: 'submitted', label: 'Submitted', labelEn: 'Submitted', color: '#8b5cf6' },
      { value: 'customer_review', label: 'Customer Review', labelEn: 'Customer Review', color: '#f59e0b' },
      { value: 'approved', label: 'Approved', labelEn: 'Approved', color: '#10b981' },
      { value: 'rejected', label: 'Rejected', labelEn: 'Rejected', color: '#ef4444' },
    ],
  },
  apqp_gate_status: {
    label: 'APQP Gate Status',
    labelEn: 'APQP Gate Status',
    options: [
      { value: 'not_started', label: 'Not Started', labelEn: 'Not Started', color: '#94a3b8' },
      { value: 'open', label: 'Open', labelEn: 'Open', color: '#3b82f6' },
      { value: 'ready', label: 'Ready for Gate', labelEn: 'Ready for Gate', color: '#8b5cf6' },
      { value: 'approved', label: 'Approved', labelEn: 'Approved', color: '#10b981' },
      { value: 'blocked', label: 'Blocked', labelEn: 'Blocked', color: '#ef4444' },
    ],
  },
  evidence_status: {
    label: 'Evidence Status',
    labelEn: 'Evidence Status',
    options: [
      { value: 'draft', label: 'Draft', labelEn: 'Draft', color: '#94a3b8' },
      { value: 'submitted', label: 'Submitted', labelEn: 'Submitted', color: '#3b82f6' },
      { value: 'verified', label: 'Verified', labelEn: 'Verified', color: '#10b981' },
      { value: 'rejected', label: 'Rejected', labelEn: 'Rejected', color: '#ef4444' },
      { value: 'expired', label: 'Expired', labelEn: 'Expired', color: '#f59e0b' },
    ],
  },
  program_approval_status: {
    label: 'Program Approval Status',
    labelEn: 'Program Approval Status',
    options: [
      { value: 'draft', label: 'Draft', labelEn: 'Draft', color: '#94a3b8' },
      { value: 'under_review', label: 'Under Review', labelEn: 'Under Review', color: '#3b82f6' },
      { value: 'approved', label: 'Approved', labelEn: 'Approved', color: '#10b981' },
      { value: 'superseded', label: 'Superseded', labelEn: 'Superseded', color: '#6b7280' },
      { value: 'rejected', label: 'Rejected', labelEn: 'Rejected', color: '#ef4444' },
    ],
  },
  schedule_conflict_status: {
    label: 'Schedule Conflict Status',
    labelEn: 'Schedule Conflict Status',
    options: [
      { value: 'open', label: 'Open', labelEn: 'Open', color: '#ef4444' },
      { value: 'mitigating', label: 'Mitigating', labelEn: 'Mitigating', color: '#f59e0b' },
      { value: 'resolved', label: 'Resolved', labelEn: 'Resolved', color: '#10b981' },
      { value: 'accepted_risk', label: 'Accepted Risk', labelEn: 'Accepted Risk', color: '#8b5cf6' },
    ],
  },
  passport_event_type: {
    label: 'Passport Event Type',
    labelEn: 'Passport Event Type',
    options: [
      { value: 'material_receipt', label: 'Material Receipt', labelEn: 'Material Receipt', color: '#3b82f6' },
      { value: 'operation_complete', label: 'Operation Complete', labelEn: 'Operation Complete', color: '#8b5cf6' },
      { value: 'inspection_complete', label: 'Inspection Complete', labelEn: 'Inspection Complete', color: '#10b981' },
      { value: 'shipment', label: 'Shipment', labelEn: 'Shipment', color: '#06b6d4' },
      { value: 'field_return', label: 'Field Return', labelEn: 'Field Return', color: '#ef4444' },
    ],
  },
  audit_finding_type: {
    label: 'Audit Finding Type',
    labelEn: 'Audit Finding Type',
    options: [
      { value: 'major_nc', label: 'Major NC', labelEn: 'Major Nonconformance', color: '#ef4444' },
      { value: 'minor_nc', label: 'Minor NC', labelEn: 'Minor Nonconformance', color: '#f59e0b' },
      { value: 'observation', label: 'Observation', labelEn: 'Observation', color: '#3b82f6' },
      { value: 'ofi', label: 'OFI', labelEn: 'Opportunity for Improvement', color: '#10b981' },
    ],
  },
};

export const normalizedFieldTypes = {
  string: { icon: 'Aa', format: 'text', apiType: 'string', inputControl: 'text', align: 'left', editable: true, filterType: 'text', sortable: true },
  number: { icon: '#', format: 'decimal', apiType: 'number', inputControl: 'number', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  integer: { icon: '#', format: 'integer', apiType: 'integer', inputControl: 'number', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  currency: { icon: '$', format: 'currency', apiType: 'number', inputControl: 'currency', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  percent: { icon: '%', format: 'percent', apiType: 'number', inputControl: 'percent', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  date: { icon: 'DT', format: 'date', apiType: 'string', inputControl: 'date', align: 'left', editable: true, filterType: 'date-range', sortable: true },
  datetime: { icon: 'TS', format: 'datetime', apiType: 'string', inputControl: 'datetime-local', align: 'left', editable: true, filterType: 'date-range', sortable: true },
  time: { icon: 'TM', format: 'time', apiType: 'string', inputControl: 'time', align: 'left', editable: true, filterType: 'text', sortable: true },
  boolean: { icon: 'YN', format: 'boolean', apiType: 'boolean', inputControl: 'checkbox', align: 'center', editable: true, filterType: 'boolean', sortable: true },
  badge: { icon: 'BG', format: 'badge', apiType: 'string', inputControl: 'select', align: 'center', editable: false, filterType: 'select', sortable: true },
  email: { icon: '@', format: 'email', apiType: 'string', inputControl: 'email', align: 'left', editable: true, filterType: 'text', sortable: true },
  phone: { icon: 'PH', format: 'phone', apiType: 'string', inputControl: 'tel', align: 'left', editable: true, filterType: 'text', sortable: false },
  url: { icon: 'URL', format: 'url', apiType: 'string', inputControl: 'url', align: 'left', editable: false, filterType: 'text', sortable: false },
  image: { icon: 'IMG', format: 'image', apiType: 'string', inputControl: 'file', align: 'center', editable: false, filterType: null, sortable: false },
  json: { icon: '{}', format: 'json', apiType: 'object', inputControl: 'json-editor', align: 'left', editable: true, filterType: null, sortable: false },
  textarea: { icon: 'TXT', format: 'multiline', apiType: 'string', inputControl: 'textarea', align: 'left', editable: true, filterType: 'text', sortable: false },
  select: { icon: 'SEL', format: 'select', apiType: 'string', inputControl: 'select', align: 'left', editable: true, filterType: 'select', sortable: true },
  tags: { icon: 'TAG', format: 'tags', apiType: 'array', inputControl: 'tag-picker', align: 'left', editable: true, filterType: 'text', sortable: false },
  progress: { icon: 'PRG', format: 'progress-bar', apiType: 'number', inputControl: 'readonly', align: 'center', editable: false, filterType: 'number-range', sortable: true },
  color: { icon: 'CLR', format: 'color', apiType: 'string', inputControl: 'color', align: 'center', editable: true, filterType: null, sortable: false },
  duration: { icon: 'DUR', format: 'duration', apiType: 'number', inputControl: 'duration', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  weight: { icon: 'WT', format: 'weight', apiType: 'number', inputControl: 'number', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  dimension: { icon: 'DIM', format: 'dimension', apiType: 'number', inputControl: 'number', align: 'right', editable: true, filterType: 'number-range', sortable: true },
  uuid: { icon: 'ID', format: 'uuid', apiType: 'string', inputControl: 'readonly', align: 'left', editable: false, filterType: 'text', sortable: false },
  code: { icon: '<>', format: 'code', apiType: 'string', inputControl: 'code-editor', align: 'left', editable: true, filterType: 'text', sortable: true },
};

export const normalizedComputedFormulas = {
  total_line_amount: { label: 'Line Total Amount', labelEn: 'Line Total Amount', formula: 'quantity * unit_price', resultType: 'currency', category: 'financial', description: 'Extended amount for a single commercial line.', inputs: ['quantity', 'unit_price'], tags: ['quote', 'order', 'finance'] },
  discount_amount: { label: 'Discount Amount', labelEn: 'Discount Amount', formula: 'subtotal * (discount_pct / 100)', resultType: 'currency', category: 'financial', description: 'Monetary discount derived from subtotal and percent.', inputs: ['subtotal', 'discount_pct'], tags: ['quote', 'order'] },
  gross_margin_pct: { label: 'Gross Margin Percent', labelEn: 'Gross Margin Percent', formula: '((selling_price - unit_cost) / selling_price) * 100', resultType: 'percent', category: 'financial', description: 'Margin percent relative to selling price.', inputs: ['selling_price', 'unit_cost'], tags: ['quote', 'costing'] },
  markup_pct: { label: 'Markup Percent', labelEn: 'Markup Percent', formula: '((selling_price - unit_cost) / unit_cost) * 100', resultType: 'percent', category: 'financial', description: 'Markup percent relative to cost.', inputs: ['selling_price', 'unit_cost'], tags: ['quote', 'costing'] },
  total_order_value: { label: 'Total Order Value', labelEn: 'Total Order Value', formula: 'SUM(lines.quantity * lines.unit_price)', resultType: 'currency', category: 'financial', description: 'Aggregate value across all lines in a commercial document.', inputs: ['lines.quantity', 'lines.unit_price'], tags: ['sales_order', 'quote'] },
  vat_amount: { label: 'VAT Amount', labelEn: 'VAT Amount', formula: 'subtotal * (vat_rate / 100)', resultType: 'currency', category: 'financial', description: 'Tax amount calculated from taxable subtotal.', inputs: ['subtotal', 'vat_rate'], tags: ['finance', 'compliance'] },
  grand_total: { label: 'Grand Total', labelEn: 'Grand Total', formula: 'subtotal - discount_amount + vat_amount + freight_amount', resultType: 'currency', category: 'financial', description: 'Commercial grand total including tax and freight.', inputs: ['subtotal', 'discount_amount', 'vat_amount', 'freight_amount'], tags: ['quote', 'sales_order'] },
  copq_total: { label: 'Total Cost Of Poor Quality', labelEn: 'Total Cost Of Poor Quality', formula: 'scrap_cost + rework_cost + warranty_cost + inspection_cost', resultType: 'currency', category: 'quality', description: 'Total direct poor quality cost bucket.', inputs: ['scrap_cost', 'rework_cost', 'warranty_cost', 'inspection_cost'], tags: ['quality', 'management_review'] },
  copq_rate_pct: { label: 'COPQ Rate Percent', labelEn: 'COPQ Rate Percent', formula: '(copq_total / revenue_amount) * 100', resultType: 'percent', category: 'quality', description: 'Poor quality cost as percentage of revenue.', inputs: ['copq_total', 'revenue_amount'], tags: ['quality', 'finance'] },
  cycle_time_total: { label: 'Total Cycle Time', labelEn: 'Total Cycle Time', formula: 'setup_time + (run_time_per_unit * quantity)', resultType: 'duration', category: 'production', description: 'Combined setup and runtime requirement.', inputs: ['setup_time', 'run_time_per_unit', 'quantity'], tags: ['routing', 'scheduling'] },
  takt_gap_minutes: { label: 'Takt Gap Minutes', labelEn: 'Takt Gap Minutes', formula: 'actual_cycle_time - takt_time', resultType: 'duration', category: 'production', description: 'Positive value indicates cycle exceeds takt.', inputs: ['actual_cycle_time', 'takt_time'], tags: ['production', 'capacity'] },
  oee_pct: { label: 'OEE Percent', labelEn: 'OEE Percent', formula: 'availability * performance * quality * 100', resultType: 'percent', category: 'production', description: 'Overall equipment effectiveness.', inputs: ['availability', 'performance', 'quality'], tags: ['machine', 'kpi'] },
  scrap_rate_pct: { label: 'Scrap Rate Percent', labelEn: 'Scrap Rate Percent', formula: '(scrap_qty / total_produced) * 100', resultType: 'percent', category: 'quality', description: 'Scrap quantity relative to production output.', inputs: ['scrap_qty', 'total_produced'], tags: ['quality', 'shop_floor'] },
  first_pass_yield: { label: 'First Pass Yield', labelEn: 'First Pass Yield', formula: '(good_qty / total_inspected) * 100', resultType: 'percent', category: 'quality', description: 'Yield without rework or repair.', inputs: ['good_qty', 'total_inspected'], tags: ['quality', 'inspection'] },
  defect_escape_rate: { label: 'Defect Escape Rate', labelEn: 'Defect Escape Rate', formula: '(customer_returns / total_shipments) * 100', resultType: 'percent', category: 'quality', description: 'Escaped defects as percentage of shipments.', inputs: ['customer_returns', 'total_shipments'], tags: ['quality', 'customer'] },
  dpmo: { label: 'DPMO', labelEn: 'Defects Per Million Opportunities', formula: '(defect_count / (total_units * opportunities_per_unit)) * 1000000', resultType: 'number', category: 'quality', description: 'Six Sigma style opportunity metric.', inputs: ['defect_count', 'total_units', 'opportunities_per_unit'], tags: ['quality', 'spc'] },
  cpk: { label: 'Cpk', labelEn: 'Process Capability Index Cpk', formula: 'MIN((usl - mean) / (3 * stdev), (mean - lsl) / (3 * stdev))', resultType: 'number', category: 'quality', description: 'Capability index using upper and lower specification limits.', inputs: ['usl', 'mean', 'stdev', 'lsl'], tags: ['quality', 'spc'] },
  closure_aging_days: { label: 'Closure Aging Days', labelEn: 'Closure Aging Days', formula: 'DATEDIFF(close_date, open_date)', resultType: 'integer', category: 'quality', description: 'Elapsed days from event opening to closure.', inputs: ['close_date', 'open_date'], tags: ['ncr', 'capa', 'scar'] },
  audit_closure_rate: { label: 'Audit Closure Rate', labelEn: 'Audit Closure Rate', formula: '(closed_findings / total_findings) * 100', resultType: 'percent', category: 'audit', description: 'Closure percentage of audit findings.', inputs: ['closed_findings', 'total_findings'], tags: ['audit', 'supplier'] },
  ppap_completeness_pct: { label: 'PPAP Completeness Percent', labelEn: 'PPAP Completeness Percent', formula: '(approved_elements / required_elements) * 100', resultType: 'percent', category: 'quality', description: 'PPAP element completeness score.', inputs: ['approved_elements', 'required_elements'], tags: ['ppap', 'apqp'] },
  first_article_completion_pct: { label: 'First Article Completion Percent', labelEn: 'First Article Completion Percent', formula: '(completed_characteristics / total_characteristics) * 100', resultType: 'percent', category: 'quality', description: 'Completion percent for first article inspection characteristics.', inputs: ['completed_characteristics', 'total_characteristics'], tags: ['fai', 'inspection'] },
  supplier_score: { label: 'Supplier Scorecard', labelEn: 'Supplier Scorecard', formula: '(quality_score * 0.4) + (delivery_score * 0.3) + (cost_score * 0.2) + (service_score * 0.1)', resultType: 'number', category: 'supplier', description: 'Weighted supplier composite performance score.', inputs: ['quality_score', 'delivery_score', 'cost_score', 'service_score'], tags: ['supplier', 'scorecard'] },
  on_time_delivery_pct: { label: 'On Time Delivery Percent', labelEn: 'On Time Delivery Percent', formula: '(on_time_count / total_deliveries) * 100', resultType: 'percent', category: 'supplier', description: 'Delivery performance percentage.', inputs: ['on_time_count', 'total_deliveries'], tags: ['supplier', 'shipping'] },
  incoming_acceptance_rate: { label: 'Incoming Acceptance Rate', labelEn: 'Incoming Acceptance Rate', formula: '(accepted_lots / total_lots_inspected) * 100', resultType: 'percent', category: 'supplier', description: 'Receiving acceptance ratio.', inputs: ['accepted_lots', 'total_lots_inspected'], tags: ['supplier', 'inspection'] },
  supplier_ppm: { label: 'Supplier PPM', labelEn: 'Supplier Parts Per Million', formula: '(defective_qty / received_qty) * 1000000', resultType: 'number', category: 'supplier', description: 'Supplier defect rate per million units received.', inputs: ['defective_qty', 'received_qty'], tags: ['supplier', 'quality'] },
  scar_closure_pct: { label: 'SCAR Closure Percent', labelEn: 'SCAR Closure Percent', formula: '(closed_scars / total_scars) * 100', resultType: 'percent', category: 'supplier', description: 'Closure percentage for supplier corrective actions.', inputs: ['closed_scars', 'total_scars'], tags: ['supplier', 'scar'] },
  material_cost_estimate: { label: 'Material Cost Estimate', labelEn: 'Material Cost Estimate', formula: 'raw_weight * material_price_per_kg * buy_to_fly_ratio', resultType: 'currency', category: 'quoting', description: 'Material cost estimate for machining and aerospace parts.', inputs: ['raw_weight', 'material_price_per_kg', 'buy_to_fly_ratio'], tags: ['quote', 'material'] },
  machining_cost_estimate: { label: 'Machining Cost Estimate', labelEn: 'Machining Cost Estimate', formula: 'cycle_time_hours * machine_rate_per_hour', resultType: 'currency', category: 'quoting', description: 'Estimated cost of machine runtime.', inputs: ['cycle_time_hours', 'machine_rate_per_hour'], tags: ['quote', 'production'] },
  setup_cost_estimate: { label: 'Setup Cost Estimate', labelEn: 'Setup Cost Estimate', formula: 'setup_hours * setup_rate_per_hour', resultType: 'currency', category: 'quoting', description: 'Setup cost burden for quoting and routing.', inputs: ['setup_hours', 'setup_rate_per_hour'], tags: ['quote', 'routing'] },
  quote_total: { label: 'Quote Total', labelEn: 'Quote Total', formula: 'material_cost + machining_cost + overhead_cost + profit_margin', resultType: 'currency', category: 'quoting', description: 'Quoted commercial total before tax.', inputs: ['material_cost', 'machining_cost', 'overhead_cost', 'profit_margin'], tags: ['quote'] },
  lead_time_days: { label: 'Lead Time Days', labelEn: 'Lead Time Days', formula: 'material_lead_days + production_days + finishing_days + buffer_days', resultType: 'integer', category: 'quoting', description: 'Estimated end-to-end lead time.', inputs: ['material_lead_days', 'production_days', 'finishing_days', 'buffer_days'], tags: ['quote', 'planning'] },
  inventory_value: { label: 'Inventory Value', labelEn: 'Inventory Value', formula: 'qty_on_hand * unit_cost', resultType: 'currency', category: 'inventory', description: 'Inventory carrying value at location or part level.', inputs: ['qty_on_hand', 'unit_cost'], tags: ['inventory', 'finance'] },
  reorder_point: { label: 'Reorder Point', labelEn: 'Reorder Point', formula: '(avg_daily_usage * lead_time_days) + safety_stock', resultType: 'number', category: 'inventory', description: 'Inventory reorder trigger threshold.', inputs: ['avg_daily_usage', 'lead_time_days', 'safety_stock'], tags: ['inventory', 'planning'] },
  days_of_supply: { label: 'Days Of Supply', labelEn: 'Days Of Supply', formula: 'qty_on_hand / avg_daily_usage', resultType: 'number', category: 'inventory', description: 'Projected available supply days.', inputs: ['qty_on_hand', 'avg_daily_usage'], tags: ['inventory', 'planning'] },
  lot_age_days: { label: 'Lot Age Days', labelEn: 'Lot Age Days', formula: 'DATEDIFF(today, receipt_date)', resultType: 'integer', category: 'inventory', description: 'Age of a lot since receipt.', inputs: ['today', 'receipt_date'], tags: ['lot', 'traceability'] },
  traceability_completeness_pct: { label: 'Traceability Completeness Percent', labelEn: 'Traceability Completeness Percent', formula: '(completed_trace_links / required_trace_links) * 100', resultType: 'percent', category: 'traceability', description: 'Completeness of lot, serial, cert, and operation genealogy.', inputs: ['completed_trace_links', 'required_trace_links'], tags: ['traceability', 'passport'] },
  labor_efficiency_pct: { label: 'Labor Efficiency Percent', labelEn: 'Labor Efficiency Percent', formula: '(standard_hours / actual_hours) * 100', resultType: 'percent', category: 'production', description: 'Standard to actual labor efficiency.', inputs: ['standard_hours', 'actual_hours'], tags: ['labor', 'production'] },
  machine_utilization_pct: { label: 'Machine Utilization Percent', labelEn: 'Machine Utilization Percent', formula: '(actual_run_time / available_time) * 100', resultType: 'percent', category: 'production', description: 'Machine utilization ratio.', inputs: ['actual_run_time', 'available_time'], tags: ['machine', 'capacity'] },
  schedule_adherence_pct: { label: 'Schedule Adherence Percent', labelEn: 'Schedule Adherence Percent', formula: '(operations_on_time / total_operations) * 100', resultType: 'percent', category: 'production', description: 'Schedule adherence across operations.', inputs: ['operations_on_time', 'total_operations'], tags: ['schedule', 'production'] },
  runtime_variance_pct: { label: 'Runtime Variance Percent', labelEn: 'Runtime Variance Percent', formula: '((actual_runtime - planned_runtime) / planned_runtime) * 100', resultType: 'percent', category: 'production', description: 'Deviation between planned and actual runtime.', inputs: ['actual_runtime', 'planned_runtime'], tags: ['production', 'variance'] },
  energy_cost_per_part: { label: 'Energy Cost Per Part', labelEn: 'Energy Cost Per Part', formula: '(kwh_consumed * electricity_rate) / parts_completed', resultType: 'currency', category: 'energy', description: 'Energy cost allocation per produced part.', inputs: ['kwh_consumed', 'electricity_rate', 'parts_completed'], tags: ['energy', 'cost'] },
  carbon_per_part: { label: 'Carbon Per Part', labelEn: 'Carbon Per Part', formula: '(kwh_consumed * emission_factor) / parts_completed', resultType: 'number', category: 'energy', description: 'Estimated carbon footprint per part.', inputs: ['kwh_consumed', 'emission_factor', 'parts_completed'], tags: ['energy', 'sustainability'] },
  weight_from_dimensions: { label: 'Weight From Dimensions', labelEn: 'Weight From Dimensions', formula: 'length * width * height * material_density', resultType: 'weight', category: 'engineering', description: 'Estimated weight from envelope dimensions and density.', inputs: ['length', 'width', 'height', 'material_density'], tags: ['engineering', 'material'] },
};

export const normalizedIotConnectors = {
  mtconnect: {
    label: 'MTConnect',
    protocol: 'http',
    category: 'machine',
    defaultPort: 5000,
    direction: 'pull',
    authType: 'none',
    description: 'Open machine tool standard for CNC state, alarms, spindle, feed, and part counters.',
    dataPoints: ['execution_state', 'spindle_speed', 'feed_rate', 'tool_id', 'part_count', 'alarm_code', 'axis_load'],
    pollIntervalMs: 1000,
    typicalUseCases: ['machine monitoring', 'cycle completion', 'utilization tracking'],
    securityFeatures: ['network segmentation', 'read-only adapter'],
    configFields: [
      { key: 'agentUrl', label: 'Agent URL', type: 'url', required: true, placeholder: 'http://192.168.1.100:5000' },
      { key: 'deviceId', label: 'Device ID', type: 'string', required: true },
      { key: 'pollRate', label: 'Poll Rate (ms)', type: 'number', default: 1000 },
    ],
  },
  opcua: {
    label: 'OPC UA',
    protocol: 'opcua',
    category: 'machine',
    defaultPort: 4840,
    direction: 'subscribe',
    authType: 'certificate',
    description: 'Industrial interoperability stack for PLC, SCADA, machine tools, and contextual manufacturing tags.',
    dataPoints: ['node_value', 'temperature', 'pressure', 'vibration', 'alarm_state', 'energy_kw'],
    pollIntervalMs: 500,
    typicalUseCases: ['production telemetry', 'energy monitoring', 'machine alarms'],
    securityFeatures: ['certificate auth', 'message signing', 'encryption'],
    configFields: [
      { key: 'endpointUrl', label: 'Endpoint URL', type: 'url', required: true, placeholder: 'opc.tcp://192.168.1.50:4840' },
      { key: 'securityPolicy', label: 'Security Policy', type: 'select', options: ['None', 'Basic128Rsa15', 'Basic256', 'Basic256Sha256'], default: 'Basic256Sha256' },
      { key: 'nodeIds', label: 'Node IDs', type: 'textarea', required: true },
    ],
  },
  modbus_tcp: {
    label: 'Modbus TCP',
    protocol: 'tcp',
    category: 'sensor',
    defaultPort: 502,
    direction: 'pull',
    authType: 'none',
    description: 'Legacy industrial polling for meters, sensors, and simple controllers.',
    dataPoints: ['register_value', 'coil_status', 'input_register', 'holding_register'],
    pollIntervalMs: 2000,
    typicalUseCases: ['energy meters', 'facility sensors', 'legacy PLC telemetry'],
    securityFeatures: ['network segmentation'],
    configFields: [
      { key: 'host', label: 'Host IP', type: 'string', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 502 },
      { key: 'slaveId', label: 'Slave ID', type: 'number', default: 1 },
      { key: 'registers', label: 'Register Map', type: 'json', required: true },
    ],
  },
  mqtt: {
    label: 'MQTT',
    protocol: 'mqtt',
    category: 'gateway',
    defaultPort: 1883,
    direction: 'subscribe',
    authType: 'username_password',
    description: 'Lightweight pub/sub connector for edge gateways and custom sensor payloads.',
    dataPoints: ['topic_payload'],
    pollIntervalMs: 0,
    typicalUseCases: ['edge telemetry', 'shopfloor event stream', 'mobile sensor messages'],
    securityFeatures: ['username password', 'TLS', 'topic isolation'],
    configFields: [
      { key: 'brokerUrl', label: 'Broker URL', type: 'url', required: true, placeholder: 'mqtt://192.168.1.10:1883' },
      { key: 'topics', label: 'Subscribe Topics', type: 'textarea', required: true },
      { key: 'username', label: 'Username', type: 'string' },
      { key: 'password', label: 'Password', type: 'string' },
      { key: 'qos', label: 'QoS Level', type: 'select', options: ['0', '1', '2'], default: '1' },
    ],
  },
  focas: {
    label: 'FANUC FOCAS',
    protocol: 'tcp',
    category: 'machine',
    defaultPort: 8193,
    direction: 'pull',
    authType: 'none',
    description: 'Direct FANUC CNC polling for program, alarm, tool, and load details.',
    dataPoints: ['program_number', 'sequence_number', 'spindle_speed_actual', 'tool_number', 'alarm_number', 'servo_load'],
    pollIntervalMs: 1000,
    typicalUseCases: ['fanuc runtime', 'program download status', 'tool wear trending'],
    securityFeatures: ['network isolation'],
    configFields: [
      { key: 'host', label: 'CNC IP Address', type: 'string', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 8193 },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', default: 5000 },
    ],
  },
  rest_api: {
    label: 'REST API',
    protocol: 'https',
    category: 'integration',
    defaultPort: 443,
    direction: 'pull',
    authType: 'bearer_token',
    description: 'Generic HTTP JSON connector for enterprise or custom platform integration.',
    dataPoints: ['json_response'],
    pollIntervalMs: 5000,
    typicalUseCases: ['erp sync', 'external quality data', 'warehouse services'],
    securityFeatures: ['https', 'bearer token', 'custom headers'],
    configFields: [
      { key: 'url', label: 'API URL', type: 'url', required: true },
      { key: 'method', label: 'HTTP Method', type: 'select', options: ['GET', 'POST'], default: 'GET' },
      { key: 'headers', label: 'Custom Headers', type: 'json' },
      { key: 'body', label: 'Request Body', type: 'json' },
      { key: 'authToken', label: 'Bearer Token', type: 'string' },
      { key: 'responseMapping', label: 'Response Mapping', type: 'json' },
    ],
  },
  epicor_kinetic: {
    label: 'Epicor Kinetic',
    protocol: 'https',
    category: 'erp',
    defaultPort: 443,
    direction: 'pull',
    authType: 'api_key',
    description: 'Epicor REST v2 / BAQ / BO / Function integration profile for ERP and MES data exchange.',
    dataPoints: ['baq_result', 'bo_method_result', 'efx_result'],
    pollIntervalMs: 30000,
    typicalUseCases: ['part master sync', 'job status', 'quote enrichment'],
    securityFeatures: ['api key', 'https', 'tenant isolation'],
    configFields: [
      { key: 'serverUrl', label: 'Epicor Server URL', type: 'url', required: true, placeholder: 'https://erp.company.com/api/v2' },
      { key: 'apiKey', label: 'API Key', type: 'string', required: true },
      { key: 'company', label: 'Company ID', type: 'string', required: true },
      { key: 'baqId', label: 'BAQ ID', type: 'string' },
      { key: 'boName', label: 'Business Object', type: 'string' },
      { key: 'methodName', label: 'BO Method', type: 'string' },
    ],
  },
  database_poll: {
    label: 'Database Query',
    protocol: 'tcp',
    category: 'integration',
    defaultPort: 5432,
    direction: 'pull',
    authType: 'username_password',
    description: 'Direct database polling for dashboards and reference sync.',
    dataPoints: ['query_result'],
    pollIntervalMs: 10000,
    typicalUseCases: ['legacy databases', 'report snapshots', 'reference master sync'],
    securityFeatures: ['db credential vaulting', 'read-only users'],
    configFields: [
      { key: 'dbType', label: 'Database Type', type: 'select', options: ['postgresql', 'mysql', 'sqlserver'], default: 'postgresql' },
      { key: 'host', label: 'Host', type: 'string', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 5432 },
      { key: 'database', label: 'Database Name', type: 'string', required: true },
      { key: 'username', label: 'Username', type: 'string', required: true },
      { key: 'password', label: 'Password', type: 'string', required: true },
      { key: 'query', label: 'SQL Query', type: 'textarea', required: true },
    ],
  },
  csv_file_watch: {
    label: 'CSV File Watcher',
    protocol: 'filesystem',
    category: 'batch',
    defaultPort: null,
    direction: 'watch',
    authType: 'none',
    description: 'Filesystem watcher for measurement exports, CMM programs, or batch uploads.',
    dataPoints: ['csv_rows'],
    pollIntervalMs: 5000,
    typicalUseCases: ['cmm result import', 'lab exports', 'supplier batch uploads'],
    securityFeatures: ['path allowlist', 'archive after processing'],
    configFields: [
      { key: 'watchDir', label: 'Watch Directory', type: 'string', required: true },
      { key: 'filePattern', label: 'File Pattern', type: 'string', default: '*.csv' },
      { key: 'delimiter', label: 'Delimiter', type: 'select', options: [',', ';', '\\t', '|'], default: ',' },
      { key: 'headerRow', label: 'Header Row', type: 'boolean', default: true },
      { key: 'archiveAfterRead', label: 'Archive After Read', type: 'boolean', default: true },
    ],
  },
  webhook: {
    label: 'Webhook',
    protocol: 'https',
    category: 'integration',
    defaultPort: 443,
    direction: 'push',
    authType: 'signature',
    description: 'Inbound or outbound event webhook connector for transactional event propagation.',
    dataPoints: ['event_payload'],
    pollIntervalMs: 0,
    typicalUseCases: ['event notifications', 'supplier portal callbacks', 'workflow alerts'],
    securityFeatures: ['shared secret', 'signed payload', 'replay protection'],
    configFields: [
      { key: 'endpointUrl', label: 'Endpoint URL', type: 'url', required: true },
      { key: 'sharedSecret', label: 'Shared Secret', type: 'string', required: true },
      { key: 'eventFilter', label: 'Event Filter', type: 'tags' },
    ],
  },
  sftp_drop: {
    label: 'SFTP Drop',
    protocol: 'sftp',
    category: 'batch',
    defaultPort: 22,
    direction: 'watch',
    authType: 'ssh_key',
    description: 'Secure file exchange channel for customer, supplier, and compliance data packets.',
    dataPoints: ['file_manifest', 'file_payload'],
    pollIntervalMs: 60000,
    typicalUseCases: ['cert package exchange', 'supplier scorecards', 'batch inspection uploads'],
    securityFeatures: ['ssh key', 'remote folder isolation', 'checksum validation'],
    configFields: [
      { key: 'host', label: 'Host', type: 'string', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 22 },
      { key: 'username', label: 'Username', type: 'string', required: true },
      { key: 'privateKeyPath', label: 'Private Key Path', type: 'string', required: true },
      { key: 'remoteDir', label: 'Remote Directory', type: 'string', required: true },
    ],
  },
  ethernet_ip: {
    label: 'EtherNet/IP',
    protocol: 'cip',
    category: 'machine',
    defaultPort: 44818,
    direction: 'pull',
    authType: 'none',
    description: 'Industrial protocol profile for Rockwell and compatible controllers.',
    dataPoints: ['tag_value', 'run_mode', 'alarm_state', 'part_counter'],
    pollIntervalMs: 1000,
    typicalUseCases: ['plc telemetry', 'andon events', 'line counters'],
    securityFeatures: ['network segmentation'],
    configFields: [
      { key: 'host', label: 'Host', type: 'string', required: true },
      { key: 'tags', label: 'Controller Tags', type: 'textarea', required: true },
    ],
  },
  kafka: {
    label: 'Kafka',
    protocol: 'kafka',
    category: 'event-stream',
    defaultPort: 9092,
    direction: 'subscribe',
    authType: 'sasl',
    description: 'High-throughput event streaming connector for digital thread and enterprise event buses.',
    dataPoints: ['topic_message'],
    pollIntervalMs: 0,
    typicalUseCases: ['enterprise event bus', 'traceability stream', 'analytics feed'],
    securityFeatures: ['sasl', 'tls', 'consumer group isolation'],
    configFields: [
      { key: 'brokers', label: 'Brokers', type: 'textarea', required: true },
      { key: 'topic', label: 'Topic', type: 'string', required: true },
      { key: 'groupId', label: 'Consumer Group', type: 'string', required: true },
      { key: 'securityProtocol', label: 'Security Protocol', type: 'select', options: ['PLAINTEXT', 'SSL', 'SASL_SSL'], default: 'SASL_SSL' },
    ],
  },
};

export const workflowBlueprints = [
  {
    key: 'quote_to_cash',
    label: 'Quote To Cash',
    description: 'Commercial flow from RFQ capture to quote, sales order, release, packing, and delivery confirmation.',
    domains: ['commercial', 'planning', 'shipping'],
    entities: ['quote', 'sales_order', 'dispatch_target', 'packing_list', 'delivery'],
    statusRefs: ['quote_status', 'so_status', 'fulfillment_status', 'contract_review_status'],
    endpoints: ['quote_list', 'quote_create', 'quote_transition', 'quote_convert_to_so', 'order_so_list', 'dispatch_dashboard', 'packing_list', 'delivery_confirm'],
    kpis: ['quote_total', 'lead_time_days', 'on_time_delivery_pct'],
  },
  {
    key: 'plan_to_produce',
    label: 'Plan To Produce',
    description: 'Job and work order planning, schedule slot management, dispatch, execution, and machine reporting.',
    domains: ['planning', 'production', 'mes'],
    entities: ['job_order', 'work_order', 'schedule_slot', 'dispatch_target', 'mobile_queue'],
    statusRefs: ['jo_status', 'wo_status', 'fulfillment_status', 'schedule_conflict_status'],
    endpoints: ['order_jo_list', 'order_wo_list', 'schedule_get', 'schedule_slot_create', 'dispatch_list_targets', 'dispatch_report_production'],
    kpis: ['cycle_time_total', 'schedule_adherence_pct', 'machine_utilization_pct'],
  },
  {
    key: 'supplier_quality',
    label: 'Supplier Quality',
    description: 'Receiving inspection, skip lot governance, ASL management, SCAR handling, and supplier audits.',
    domains: ['supplier', 'quality', 'audit'],
    entities: ['incoming_inspection', 'skip_lot', 'asl_entry', 'scar', 'supplier_audit'],
    statusRefs: ['iqc_result', 'skip_lot_level', 'scar_status', 'audit_finding_type'],
    endpoints: ['supplier_incoming_list', 'supplier_incoming_create', 'supplier_skip_lot_status', 'supplier_asl_list', 'supplier_scar_list', 'supplier_audit_list'],
    kpis: ['supplier_score', 'incoming_acceptance_rate', 'scar_closure_pct'],
  },
  {
    key: 'ncr_to_capa',
    label: 'NCR To CAPA',
    description: 'Nonconformance intake, material review, 8D, corrective action, and closure effectiveness.',
    domains: ['quality', 'risk', 'improvement'],
    entities: ['ncr_record', 'mrb_disposition', 'eight_d', 'capa_record'],
    statusRefs: ['ncr_status', 'disposition', 'action_priority', 'severity'],
    endpoints: ['quality_exception_list', 'quality_exception_create', 'quality_exception_mrb_disposition', 'quality_exception_save_8d', 'quality_exception_transition'],
    kpis: ['closure_aging_days', 'copq_total', 'defect_escape_rate'],
  },
  {
    key: 'apqp_ppap_launch',
    label: 'APQP And PPAP Launch',
    description: 'Launch readiness workflow covering APQP phases, FMEA, control plans, and PPAP evidence gates.',
    domains: ['engineering', 'quality', 'program_management'],
    entities: ['apqp_project', 'pfmea', 'control_plan', 'ppap_submission'],
    statusRefs: ['apqp_phase', 'apqp_gate_status', 'ppap_status', 'action_priority'],
    endpoints: ['apqp_dashboard', 'apqp_project_list', 'fmea_list', 'cp_detail', 'ppap_create'],
    kpis: ['ppap_completeness_pct', 'first_article_completion_pct', 'traceability_completeness_pct'],
  },
  {
    key: 'documented_information',
    label: 'Documented Information',
    description: 'Controlled documents, revisions, form schemas, record IDs, and knowledge articles.',
    domains: ['document_control', 'records', 'training'],
    entities: ['document', 'document_revision', 'online_form', 'record_id', 'knowledge_article'],
    statusRefs: ['doc_status', 'master_data_status'],
    endpoints: ['doc_create', 'doc_versions_list', 'online_form_list', 'record_id_next', 'knowledge_list'],
    kpis: ['audit_closure_rate', 'traceability_completeness_pct'],
  },
  {
    key: 'digital_thread_traceability',
    label: 'Digital Thread Traceability',
    description: 'Lot, serial, material cert, process event, and shipment trace continuity into product passport artifacts.',
    domains: ['traceability', 'compliance', 'shipping'],
    entities: ['lot', 'serial', 'certificate', 'passport', 'shipment'],
    statusRefs: ['passport_event_type', 'export_control', 'evidence_status'],
    endpoints: ['product_passport_list', 'product_passport_add_event', 'product_passport_trace', 'compliance_report_evidence_package'],
    kpis: ['traceability_completeness_pct', 'carbon_per_part'],
  },
  {
    key: 'cnc_program_release',
    label: 'CNC Program Release',
    description: 'Program authoring, setup sheets, revision approvals, and controlled NC release to the shop floor.',
    domains: ['engineering', 'production', 'document_control'],
    entities: ['cnc_program', 'program_version', 'setup_sheet', 'approval'],
    statusRefs: ['program_approval_status', 'doc_status'],
    endpoints: ['cnc_program_list', 'cnc_program_create', 'cnc_program_upload_version', 'cnc_program_approve', 'cnc_program_setup_create'],
    kpis: ['runtime_variance_pct', 'machine_utilization_pct'],
  },
];

export const relationBlueprints = [
  { from: 'quote', to: 'sales_order', relation: 'converts_to', joinFields: ['quote_id', 'so_id'], endpoints: ['quote_convert_to_so'] },
  { from: 'sales_order', to: 'job_order', relation: 'drives', joinFields: ['so_id', 'jo_id'], endpoints: ['order_jo_list', 'order_detail'] },
  { from: 'job_order', to: 'work_order', relation: 'contains', joinFields: ['jo_id', 'wo_id'], endpoints: ['order_wo_list', 'order_detail'] },
  { from: 'work_order', to: 'dispatch_target', relation: 'dispatches_to', joinFields: ['wo_id', 'dispatch_id'], endpoints: ['dispatch_list_targets', 'dispatch_send'] },
  { from: 'work_order', to: 'schedule_slot', relation: 'plans_into', joinFields: ['wo_id', 'slot_id'], endpoints: ['schedule_get', 'schedule_slot_create'] },
  { from: 'work_order', to: 'subcontract', relation: 'outsources_to', joinFields: ['wo_number', 'vendor_id'], endpoints: ['subcontract_create', 'subcontract_receive'] },
  { from: 'sales_order', to: 'oqc_record', relation: 'ships_through', joinFields: ['so_number', 'oqc_id'], endpoints: ['oqc_create', 'oqc_update'] },
  { from: 'sales_order', to: 'packing_list', relation: 'packed_as', joinFields: ['so_number', 'packing_id'], endpoints: ['packing_create', 'packing_update'] },
  { from: 'packing_list', to: 'delivery', relation: 'delivered_by', joinFields: ['so_number', 'delivery_id'], endpoints: ['delivery_confirm'] },
  { from: 'sales_order', to: 'product_passport', relation: 'disclosed_in', joinFields: ['so_number', 'passport_id'], endpoints: ['product_passport_create', 'product_passport_trace'] },
  { from: 'incoming_inspection', to: 'supplier_scorecard', relation: 'rolls_up_to', joinFields: ['vendor_id', 'period'], endpoints: ['supplier_scorecards', 'supplier_scorecard_detail'] },
  { from: 'incoming_inspection', to: 'skip_lot', relation: 'feeds', joinFields: ['vendor_id', 'part_id'], endpoints: ['supplier_skip_lot_status', 'supplier_skip_lot_update'] },
  { from: 'supplier_scorecard', to: 'scar', relation: 'may_trigger', joinFields: ['vendor_id', 'scar_id'], endpoints: ['supplier_scar_create', 'supplier_scar_transition'] },
  { from: 'scar', to: 'supplier_audit', relation: 'verified_by', joinFields: ['vendor_id', 'audit_id'], endpoints: ['supplier_audit_create'] },
  { from: 'ncr_record', to: 'capa_record', relation: 'corrected_by', joinFields: ['ncr_id', 'capa_id'], endpoints: ['quality_exception_transition', 'quality_exception_save_8d'] },
  { from: 'ncr_record', to: 'evidence', relation: 'proven_by', joinFields: ['ncr_id', 'evidence_id'], endpoints: ['evidence_attach', 'evidence_verify'] },
  { from: 'pfmea', to: 'control_plan', relation: 'derives', joinFields: ['fmea_id', 'cp_id'], endpoints: ['cp_auto_generate', 'cp_add_characteristic'] },
  { from: 'apqp_project', to: 'ppap_submission', relation: 'culminates_in', joinFields: ['apqp_id', 'ppap_id'], endpoints: ['ppap_create', 'ppap_update_element'] },
  { from: 'cnc_program', to: 'program_version', relation: 'revisions', joinFields: ['program_id', 'version_id'], endpoints: ['cnc_program_upload_version'] },
  { from: 'program_version', to: 'setup_sheet', relation: 'configures', joinFields: ['program_id', 'setup_sheet_id'], endpoints: ['cnc_program_setup_create'] },
  { from: 'document', to: 'record_id', relation: 'identified_by', joinFields: ['document_number', 'record_id'], endpoints: ['record_id_registry', 'record_id_next'] },
  { from: 'document', to: 'knowledge_article', relation: 'institutionalized_as', joinFields: ['doc_id', 'knowledge_id'], endpoints: ['knowledge_create', 'knowledge_comment'] },
];

export const complianceStandards = {
  as9100_rev_d: {
    label: 'AS9100 Rev D',
    sourceUrls: [
      'https://iaqg.org/wp-content/uploads/2019/10/planning-for-quality-QP-article.pdf',
      'https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/quality-management-processes',
    ],
    workflows: ['documented_information', 'quote_to_cash', 'digital_thread_traceability'],
    statusRefs: ['doc_status', 'contract_review_status', 'fulfillment_status'],
    focusFields: ['customer_spec_ref', 'drawing_number', 'revision_number', 'lot_number', 'serial_number', 'training_requirement_id'],
    endpointHints: ['doc_create', 'compliance_report_management_review', 'product_passport_trace'],
  },
  as9102_fai: {
    label: 'AS9102 First Article Inspection',
    sourceUrls: ['https://iaqg.org/wp-content/uploads/2019/10/planning-for-quality-QP-article.pdf'],
    workflows: ['apqp_ppap_launch', 'digital_thread_traceability'],
    statusRefs: ['fai_status', 'inspection_type'],
    focusFields: ['fai_number', 'balloon_number', 'drawing_rev', 'characteristic_type', 'measurement_method', 'gage_id'],
    endpointHints: ['product_passport_trace', 'compliance_report_evidence_package'],
  },
  as9145_apqp_ppap: {
    label: 'AS9145 APQP / PPAP',
    sourceUrls: ['https://iaqg.org/wp-content/uploads/2019/10/planning-for-quality-QP-article.pdf'],
    workflows: ['apqp_ppap_launch'],
    statusRefs: ['apqp_phase', 'apqp_gate_status', 'ppap_status'],
    focusFields: ['phase_owner', 'gate_due_date', 'deliverable_status', 'ppap_level', 'customer_submission_date'],
    endpointHints: ['apqp_project_list', 'ppap_create', 'ppap_update_element'],
  },
  as13100_pfmea: {
    label: 'AS13100 / PFMEA Action Priority',
    sourceUrls: ['https://iaqg.org/wp-content/uploads/2019/10/planning-for-quality-QP-article.pdf'],
    workflows: ['apqp_ppap_launch', 'ncr_to_capa'],
    statusRefs: ['action_priority', 'severity'],
    focusFields: ['severity', 'occurrence', 'detection', 'action_priority', 'prevention_action'],
    endpointHints: ['fmea_list', 'cp_auto_generate'],
  },
  nadcap_special_process: {
    label: 'Nadcap Special Process',
    sourceUrls: ['https://www.p-r-i.org/nadcap/getting-started'],
    workflows: ['supplier_quality', 'digital_thread_traceability'],
    statusRefs: ['nadcap_process', 'evidence_status'],
    focusFields: ['special_process_code', 'nadcap_process', 'supplier_accreditation_expiry', 'heat_treat_condition'],
    endpointHints: ['subcontract_create', 'compliance_report_evidence_package'],
  },
  iso_2859_1_aql: {
    label: 'ISO 2859-1 / AQL',
    sourceUrls: ['https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/quality-sample-management-overview'],
    workflows: ['supplier_quality', 'ncr_to_capa'],
    statusRefs: ['inspection_level', 'sampling_plan', 'iqc_result', 'oqc_result'],
    focusFields: ['inspection_level', 'lot_size', 'sample_size', 'accept_number', 'reject_number', 'aql_level'],
    endpointHints: ['supplier_incoming_create', 'oqc_create'],
  },
  export_control_itar_ear: {
    label: 'ITAR / EAR Export Control',
    sourceUrls: [
      'https://www.bis.gov/media/1326',
      'https://www.pmddtc.state.gov/sys_attachment.do?sys_id=2ad95ca0db959b0044f9ff621f9619f6',
    ],
    workflows: ['digital_thread_traceability', 'quote_to_cash'],
    statusRefs: ['export_control'],
    focusFields: ['itar_controlled', 'eccn_classification', 'usml_category', 'country_of_origin', 'end_use_statement'],
    endpointHints: ['product_passport_trace', 'compliance_report_generate', 'quote_create'],
  },
  digital_product_passport: {
    label: 'Digital Product Passport / ESPR',
    sourceUrls: ['https://webgate.ec.europa.eu/circabc-ewpp/d/d/workspace/SpacesStore/c03929dd-9d98-4472-bc13-ab118ac6973f/download'],
    workflows: ['digital_thread_traceability'],
    statusRefs: ['passport_event_type', 'sync_status'],
    focusFields: ['passport_id', 'material_cert_number', 'co2_per_part', 'repairability_score', 'recycled_content_pct'],
    endpointHints: ['product_passport_create', 'product_passport_add_event', 'product_passport_trace'],
  },
};

export const unitLibrary = {
  systems: { default: 'metric', supported: ['metric', 'imperial', 'mixed'] },
  dimensions: {
    quantity: { baseUnit: 'ea', units: ['ea', 'pcs', 'set', 'lot'] },
    length: { baseUnit: 'mm', units: ['mm', 'cm', 'm', 'in'] },
    area: { baseUnit: 'mm2', units: ['mm2', 'cm2', 'm2', 'in2'] },
    volume: { baseUnit: 'cm3', units: ['cm3', 'l', 'm3', 'in3'] },
    mass: { baseUnit: 'kg', units: ['g', 'kg', 'lb'] },
    time: { baseUnit: 'min', units: ['sec', 'min', 'hr', 'day'] },
    temperature: { baseUnit: 'C', units: ['C', 'F'] },
    pressure: { baseUnit: 'bar', units: ['bar', 'psi', 'kpa'] },
    energy: { baseUnit: 'kwh', units: ['wh', 'kwh', 'mwh'] },
    force: { baseUnit: 'n', units: ['n', 'kn', 'lbf'] },
  },
  fieldUnitHints: {
    qty_received: 'ea',
    qty_inspected: 'ea',
    qty_on_hand: 'ea',
    raw_weight: 'kg',
    material_price_per_kg: 'currency_per_kg',
    cycle_time_hours: 'hr',
    setup_time: 'min',
    run_time_per_unit: 'min',
    spindle_speed: 'rpm',
    coolant_pressure: 'bar',
    cpk_value: 'index',
    carbon_per_part: 'kg_co2e',
  },
};

export const identifierPatterns = {
  quote_number: { prefix: 'QT', regex: '^QT-\\d{4}-\\d{6}$', example: 'QT-2026-000123', description: 'Commercial quote identifier' },
  so_number: { prefix: 'SO', regex: '^SO-\\d{4}-\\d{6}$', example: 'SO-2026-000456', description: 'Sales order identifier' },
  jo_number: { prefix: 'JO', regex: '^JO-\\d{4}-\\d{6}$', example: 'JO-2026-000789', description: 'Job order identifier' },
  wo_number: { prefix: 'WO', regex: '^WO-\\d{4}-\\d{6}$', example: 'WO-2026-001024', description: 'Work order identifier' },
  ncr_number: { prefix: 'NCR', regex: '^NCR-\\d{4}-\\d{5}$', example: 'NCR-2026-01234', description: 'Nonconformance report identifier' },
  capa_number: { prefix: 'CAPA', regex: '^CAPA-\\d{4}-\\d{5}$', example: 'CAPA-2026-00456', description: 'Corrective action identifier' },
  scar_number: { prefix: 'SCAR', regex: '^SCAR-\\d{4}-\\d{5}$', example: 'SCAR-2026-00123', description: 'Supplier corrective action identifier' },
  audit_number: { prefix: 'AUD', regex: '^AUD-\\d{4}-\\d{5}$', example: 'AUD-2026-00077', description: 'Audit identifier' },
  doc_code: { prefix: 'DOC', regex: '^[A-Z]{2,6}-[A-Z0-9_-]{3,40}$', example: 'QP-DOC-CONTROL-001', description: 'Controlled document code' },
  passport_number: { prefix: 'DPP', regex: '^DPP-\\d{4}-\\d{6}$', example: 'DPP-2026-000019', description: 'Digital product passport identifier' },
};
