export const tokenTranslations = {
  account: 'Tài khoản',
  action: 'Hành động',
  actual: 'Thực tế',
  address: 'Địa chỉ',
  amount: 'Giá trị',
  approval: 'Phê duyệt',
  approved: 'Đã phê duyệt',
  approver: 'Người phê duyệt',
  assigned: 'Được giao',
  attachment: 'Tệp đính kèm',
  audit: 'Đánh giá',
  available: 'Khả dụng',
  average: 'Trung bình',
  batch: 'Lô',
  bom: 'BOM',
  buy: 'Mua',
  capability: 'Năng lực',
  capa: 'CAPA',
  category: 'Danh mục',
  certificate: 'Chứng chỉ',
  classification: 'Phân loại',
  close: 'Đóng',
  closed: 'Đã đóng',
  coa: 'COA',
  code: 'Mã',
  class: 'Phân hạng',
  complaint: 'Khiếu nại',
  compliance: 'Tuân thủ',
  condition: 'Tình trạng',
  confirmed: 'Đã xác nhận',
  containment: 'Ngăn chặn',
  control: 'Kiểm soát',
  cost: 'Chi phí',
  count: 'Số lượng',
  critical: 'Trọng yếu',
  customer: 'Khách hàng',
  custody: 'Bàn giao',
  cycle: 'Chu kỳ',
  date: 'Ngày',
  defect: 'Khuyết tật',
  delivery: 'Giao hàng',
  description: 'Mô tả',
  detection: 'Phát hiện',
  deviation: 'Sai lệch',
  digital: 'Số',
  disposition: 'Xử lý',
  dispatch: 'Điều độ',
  distribution: 'Phân phối',
  document: 'Tài liệu',
  due: 'Hạn',
  duration: 'Thời lượng',
  eccn: 'ECCN',
  ear: 'EAR',
  effective: 'Hiệu lực',
  effectiveness: 'Hiệu lực',
  efficiency: 'Hiệu suất',
  email: 'Email',
  end: 'Kết thúc',
  engineering: 'Kỹ thuật',
  equipment: 'Thiết bị',
  estimate: 'Ước tính',
  evidence: 'Bằng chứng',
  event: 'Sự kiện',
  execution: 'Thực thi',
  expiry: 'Hết hạn',
  export: 'Xuất khẩu',
  fai: 'FAI',
  feature: 'Đặc tính',
  final: 'Cuối',
  first: 'Đầu tiên',
  fmea: 'FMEA',
  formula: 'Công thức',
  from: 'Từ',
  genealogy: 'Phả hệ',
  grr: 'GRR',
  group: 'Nhóm',
  gross: 'Gộp',
  hash: 'Băm',
  heat: 'Mẻ nhiệt',
  hold: 'Giữ',
  inspection: 'Kiểm tra',
  integration: 'Tích hợp',
  inventory: 'Tồn kho',
  item: 'Mã hàng',
  itar: 'ITAR',
  job: 'Lệnh',
  jo: 'JO',
  kpi: 'KPI',
  labor: 'Nhân công',
  lead: 'Dẫn',
  level: 'Mức',
  life: 'Vòng đời',
  line: 'Dòng',
  list: 'Danh sách',
  load: 'Tải',
  location: 'Vị trí',
  log: 'Nhật ký',
  lot: 'Lô',
  machine: 'Máy',
  management: 'Quản lý',
  margin: 'Biên lợi nhuận',
  markup: 'Tỷ lệ cộng giá',
  material: 'Vật liệu',
  match: 'Đối soát',
  method: 'Phương pháp',
  metric: 'Chỉ số',
  mrb: 'MRB',
  nadcap: 'NADCAP',
  net: 'Tịnh',
  ncr: 'NCR',
  note: 'Ghi chú',
  number: 'Số',
  occurrence: 'Tần suất',
  oee: 'OEE',
  oot: 'OOT',
  offset: 'Bù dao',
  operation: 'Công đoạn',
  order: 'Đơn',
  payment: 'Thanh toán',
  performance: 'Hiệu năng',
  permission: 'Quyền',
  plan: 'Kế hoạch',
  planned: 'Kế hoạch',
  po: 'PO',
  policy: 'Chính sách',
  ppm: 'PPM',
  ppk: 'Ppk',
  pressure: 'Áp suất',
  price: 'Đơn giá',
  priority: 'Ưu tiên',
  process: 'Quy trình',
  production: 'Sản xuất',
  profile: 'Hồ sơ',
  promise: 'Cam kết',
  quality: 'Chất lượng',
  quantity: 'Số lượng',
  quarantine: 'Cách ly',
  quote: 'Báo giá',
  qrqc: 'QRQC',
  rate: 'Tỷ lệ',
  reason: 'Lý do',
  receipt: 'Nhập hàng',
  received: 'Đã nhận',
  record: 'Hồ sơ',
  relation: 'Liên kết',
  release: 'Phát hành',
  released: 'Đã phát hành',
  remaining: 'Còn lại',
  report: 'Báo cáo',
  requested: 'Yêu cầu',
  reservation: 'Giữ chỗ',
  resource: 'Nguồn lực',
  retention: 'Lưu giữ',
  review: 'Xem xét',
  revision: 'Phiên bản',
  risk: 'Rủi ro',
  root: 'Gốc',
  routing: 'Quy trình công nghệ',
  schedule: 'Lịch',
  scorecard: 'Thẻ điểm',
  scrap: 'Phế phẩm',
  serial: 'Số sê-ri',
  severity: 'Mức độ nghiêm trọng',
  shelf: 'Hạn sử dụng',
  shift: 'Ca',
  ship: 'Giao',
  shipping: 'Giao hàng',
  signature: 'Chữ ký',
  source: 'Nguồn',
  special: 'Đặc biệt',
  spc: 'SPC',
  start: 'Bắt đầu',
  state: 'Trạng thái',
  status: 'Trạng thái',
  supplier: 'Nhà cung cấp',
  smed: 'SMED',
  target: 'Mục tiêu',
  temperature: 'Nhiệt độ',
  tool: 'Dao cụ',
  total: 'Tổng',
  traceability: 'Truy xuất nguồn gốc',
  training: 'Đào tạo',
  transition: 'Chuyển trạng thái',
  trend: 'Xu hướng',
  type: 'Loại',
  unit: 'Đơn vị',
  updated: 'Cập nhật',
  uom: 'Đơn vị tính',
  user: 'Người dùng',
  validation: 'Kiểm tra tính hợp lệ',
  value: 'Giá trị',
  variance: 'Chênh lệch',
  vendor: 'Nhà cung cấp',
  waiver: 'Miễn trừ',
  warehouse: 'Kho',
  weight: 'Khối lượng',
  wo: 'WO',
  workflow: 'Luồng công việc',
  yield: 'Tỷ lệ đạt',
  affected: 'bị ảnh hưởng',
  active: 'hoạt động',
  andon: 'Andon',
  auth: 'xác thực',
  browser: 'trình duyệt',
  change: 'thay đổi',
  content: 'nội dung',
  counter: 'bộ đếm',
  current: 'hiện tại',
  currency: 'tiền tệ',
  data: 'dữ liệu',
  department: 'phòng ban',
  employee: 'nhân viên',
  entity: 'đối tượng',
  expires: 'hết hạn',
  failure: 'lỗi',
  fiscal: 'tài chính',
  gross: 'gộp',
  hour: 'giờ',
  hours: 'giờ',
  id: 'ID',
  initialized: 'khởi tạo',
  internal: 'nội bộ',
  issuer: 'đơn vị cấp',
  kaizen: 'Kaizen',
  language: 'ngôn ngữ',
  logged: 'đã đăng nhập',
  magnitude: 'biên độ',
  mfa: 'MFA',
  member: 'thành viên',
  members: 'thành viên',
  mode: 'chế độ',
  modified: 'sửa đổi',
  materials: 'Vật liệu',
  message: 'thông điệp',
  name: 'tên',
  notes: 'ghi chú',
  ok: 'đạt',
  otp: 'OTP',
  output: 'đầu ra',
  password: 'mật khẩu',
  pending: 'chờ xử lý',
  pct: 'tỷ lệ',
  portal: 'cổng thông tin',
  queue: 'hàng đợi',
  required: 'bắt buộc',
  schema: 'lược đồ',
  secret: 'bí mật',
  server: 'máy chủ',
  session: 'phiên',
  parameter: 'tham số',
  submission: 'lần nộp',
  submitted: 'đã gửi',
  time: 'thời gian',
  thread: 'luồng',
  timezone: 'múi giờ',
  title: 'tiêu đề',
  url: 'URL',
  username: 'tên đăng nhập',
  version: 'phiên bản',
  year: 'năm',
};

export const fieldLabelOverrides = {
  org_company_code: { vi: 'Mã công ty tổ chức', en: 'Organization Company Code' },
  org_legal_entity_code: { vi: 'Mã pháp nhân tổ chức', en: 'Organization Legal Entity Code' },
  org_plant_id: { vi: 'ID nhà máy tổ chức', en: 'Organization Plant ID' },
  org_site_id: { vi: 'ID site tổ chức', en: 'Organization Site ID' },
  source_record_id: { vi: 'ID bản ghi nguồn', en: 'Source Record ID' },
  source_system: { vi: 'Hệ thống nguồn', en: 'Source System' },
  row_version: { vi: 'Phiên bản dòng', en: 'Row Version' },
  payload_schema_version: { vi: 'Phiên bản lược đồ payload', en: 'Payload Schema Version' },
  uom: { vi: 'Đơn vị tính', en: 'UOM' },
  alt_uom: { vi: 'Đơn vị tính thay thế', en: 'Alternate UOM' },
  component_uom: { vi: 'Đơn vị tính thành phần', en: 'Component UOM' },
  dimension_uom: { vi: 'Đơn vị tính kích thước', en: 'Dimension UOM' },
  from_uom: { vi: 'Đơn vị tính nguồn', en: 'From UOM' },
  to_uom: { vi: 'Đơn vị tính đích', en: 'To UOM' },
  weight_uom: { vi: 'Đơn vị tính khối lượng', en: 'Weight UOM' },
  uom_conversion_factor: { vi: 'Hệ số quy đổi đơn vị tính', en: 'UOM Conversion Factor' },
  item_id: { vi: 'ID mã hàng', en: 'Item ID' },
  item_class: { vi: 'Phân hạng mã hàng', en: 'Item Class' },
  item_number: { vi: 'Mã hàng', en: 'Item Number' },
  customer_id: { vi: 'ID khách hàng', en: 'Customer ID' },
  customer_name: { vi: 'Tên khách hàng', en: 'Customer Name' },
  supplier_id: { vi: 'ID nhà cung cấp', en: 'Supplier ID' },
  supplier_name: { vi: 'Tên nhà cung cấp', en: 'Supplier Name' },
  order_class: { vi: 'Phân hạng đơn hàng', en: 'Order Class' },
  quote_number: { vi: 'Số báo giá', en: 'Quote Number' },
  sales_order_number: { vi: 'Số đơn hàng bán', en: 'Sales Order Number' },
  wo_number: { vi: 'Số WO', en: 'WO Number' },
  po_number: { vi: 'Số PO', en: 'PO Number' },
  receipt_number: { vi: 'Số phiếu nhập', en: 'Receipt Number' },
  qty: { vi: 'Số lượng', en: 'Quantity' },
  qty_ordered: { vi: 'Số lượng đặt', en: 'Ordered Quantity' },
  qty_completed: { vi: 'Số lượng hoàn thành', en: 'Completed Quantity' },
  qty_scrapped: { vi: 'Số lượng phế phẩm', en: 'Scrapped Quantity' },
  qty_received: { vi: 'Số lượng nhận', en: 'Received Quantity' },
  qty_accepted: { vi: 'Số lượng đạt', en: 'Accepted Quantity' },
  qty_rejected: { vi: 'Số lượng không đạt', en: 'Rejected Quantity' },
  qty_required: { vi: 'Số lượng yêu cầu', en: 'Required Quantity' },
  qty_issued: { vi: 'Số lượng cấp phát', en: 'Issued Quantity' },
  requested_date: { vi: 'Ngày yêu cầu', en: 'Requested Date' },
  promise_date: { vi: 'Ngày cam kết', en: 'Promise Date' },
  commit_date: { vi: 'Ngày cam kết nội bộ', en: 'Internal Commit Date' },
  source: { vi: 'Nguồn', en: 'Source' },
  unit_price: { vi: 'Đơn giá', en: 'Unit Price' },
  extended_amount: { vi: 'Thành tiền', en: 'Extended Amount' },
  estimated_cycle_time: { vi: 'Thời gian chu kỳ ước tính', en: 'Estimated Cycle Time' },
  estimated_setup_time: { vi: 'Thời gian setup ước tính', en: 'Estimated Setup Time' },
  weight_gross: { vi: 'Khối lượng gộp', en: 'Gross Weight' },
  weight_net: { vi: 'Khối lượng tịnh', en: 'Net Weight' },
  gross_weight_kg: { vi: 'Khối lượng gộp (kg)', en: 'Gross Weight (kg)' },
  net_weight_kg: { vi: 'Khối lượng tịnh (kg)', en: 'Net Weight (kg)' },
  work_order_id: { vi: 'ID WO', en: 'Work Order ID' },
  lot_id: { vi: 'ID lô', en: 'Lot ID' },
  lot_number: { vi: 'Số lô', en: 'Lot Number' },
  serial_number: { vi: 'Số sê-ri', en: 'Serial Number' },
  digital_signature_status: { vi: 'Trạng thái chữ ký số', en: 'Digital Signature Status' },
  retention_policy_code: { vi: 'Mã chính sách lưu giữ', en: 'Retention Policy Code' },
  buy_to_fly_ratio: { vi: 'Tỷ lệ buy-to-fly', en: 'Buy-to-Fly Ratio' },
  cpk_target: { vi: 'Mục tiêu Cpk', en: 'Cpk Target' },
  ppk_target: { vi: 'Mục tiêu Ppk', en: 'Ppk Target' },
  eccn_code: { vi: 'Mã ECCN', en: 'ECCN Code' },
  usml_category: { vi: 'Danh mục USML', en: 'USML Category' },
  itar_controlled: { vi: 'Thuộc kiểm soát ITAR', en: 'ITAR Controlled' },
  ear_controlled: { vi: 'Thuộc kiểm soát EAR', en: 'EAR Controlled' },
  customer_source_approval_required: { vi: 'Yêu cầu CSA khách hàng', en: 'Customer Source Approval Required' },
  customer_source_approval_status: { vi: 'Trạng thái CSA', en: 'Customer Source Approval Status' },
  customer_source_approval_ref: { vi: 'Mã tham chiếu CSA', en: 'Customer Source Approval Reference' },
  first_article_required: { vi: 'Yêu cầu FAI', en: 'First Article Required' },
  first_article_waiver_ref: { vi: 'Tham chiếu miễn trừ FAI', en: 'First Article Waiver Reference' },
  delta_fai_required: { vi: 'Yêu cầu Delta FAI', en: 'Delta FAI Required' },
  nadcap_required: { vi: 'Yêu cầu NADCAP', en: 'NADCAP Required' },
  nadcap_certificate_number: { vi: 'Số chứng chỉ NADCAP', en: 'NADCAP Certificate Number' },
  nadcap_expiry_date: { vi: 'Ngày hết hạn NADCAP', en: 'NADCAP Expiry Date' },
  tool_life_limit: { vi: 'Giới hạn tuổi thọ dao', en: 'Tool Life Limit' },
  tool_life_used: { vi: 'Tuổi thọ dao đã dùng', en: 'Tool Life Used' },
  tool_life_remaining: { vi: 'Tuổi thọ dao còn lại', en: 'Tool Life Remaining' },
  offset_history: { vi: 'Lịch sử bù dao', en: 'Offset History' },
  shelf_life_days: { vi: 'Số ngày hạn sử dụng', en: 'Shelf Life Days' },
  shelf_life_start_date: { vi: 'Ngày bắt đầu hạn sử dụng', en: 'Shelf Life Start Date' },
  remaining_shelf_life_pct: { vi: 'Phần trăm hạn sử dụng còn lại', en: 'Remaining Shelf Life Percent' },
  heat_number: { vi: 'Số mẻ nhiệt', en: 'Heat Number' },
  melt_number: { vi: 'Số mẻ nấu', en: 'Melt Number' },
  material_genealogy_ref: { vi: 'Tham chiếu phả hệ vật liệu', en: 'Material Genealogy Reference' },
  flight_critical_flag: { vi: 'Cờ trọng yếu bay', en: 'Flight-Critical Flag' },
  safety_critical_flag: { vi: 'Cờ an toàn trọng yếu', en: 'Safety-Critical Flag' },
  as9102_form1_ref: { vi: 'Tham chiếu AS9102 Form 1', en: 'AS9102 Form 1 Reference' },
  as9102_form2_ref: { vi: 'Tham chiếu AS9102 Form 2', en: 'AS9102 Form 2 Reference' },
  as9102_form3_ref: { vi: 'Tham chiếu AS9102 Form 3', en: 'AS9102 Form 3 Reference' },
  source_inspection_status: { vi: 'Trạng thái kiểm tra nguồn', en: 'Source Inspection Status' },
  digital_thread_status: { vi: 'Trạng thái digital thread', en: 'Digital Thread Status' },
  evidence_hash: { vi: 'Giá trị băm bằng chứng', en: 'Evidence Hash' },
  evidence_chain_ref: { vi: 'Tham chiếu chuỗi bằng chứng', en: 'Evidence Chain Reference' },
  so_number: { vi: 'Số SO', en: 'SO Number' },
  jo_number: { vi: 'Số JO', en: 'JO Number' },
  ncr_number: { vi: 'Số NCR', en: 'NCR Number' },
  capa_number: { vi: 'Số CAPA', en: 'CAPA Number' },
  fai_number: { vi: 'Số FAI', en: 'FAI Number' },
  due_date: { vi: 'Ngày đến hạn', en: 'Due Date' },
  currency_code: { vi: 'Mã tiền tệ', en: 'Currency Code' },
  markup_pct: { vi: 'Tỷ lệ cộng giá', en: 'Markup Percent' },
  gross_margin_pct: { vi: 'Biên lợi nhuận gộp', en: 'Gross Margin Percent' },
  bom_id: { vi: 'ID BOM', en: 'BOM ID' },
  routing_id: { vi: 'ID quy trình công nghệ', en: 'Routing ID' },
  materials_available: { vi: 'Tình trạng vật liệu khả dụng', en: 'Materials Available' },
  qty_affected: { vi: 'Số lượng bị ảnh hưởng', en: 'Affected Quantity' },
  root_cause_category: { vi: 'Danh mục nguyên nhân gốc', en: 'Root Cause Category' },
  root_cause_description: { vi: 'Mô tả nguyên nhân gốc', en: 'Root Cause Description' },
  evidence_notes: { vi: 'Ghi chú bằng chứng', en: 'Evidence Notes' },
  source_inspection_status: { vi: 'Trạng thái kiểm tra tại nguồn', en: 'Source Inspection Status' },
  digital_thread_status: { vi: 'Trạng thái luồng số', en: 'Digital Thread Status' },
  mrb_id: { vi: 'ID MRB', en: 'MRB ID' },
  mrb_number: { vi: 'Số MRB', en: 'MRB Number' },
  mrb_reference: { vi: 'Tham chiếu MRB', en: 'MRB Reference' },
  mrb_date: { vi: 'Ngày MRB', en: 'MRB Date' },
  mrb_members: { vi: 'Thành viên MRB', en: 'MRB Members' },
  mrb_chairperson: { vi: 'Chủ tịch MRB', en: 'MRB Chairperson' },
  grr_id: { vi: 'ID GRR', en: 'GRR ID' },
  grr_pct: { vi: 'Tỷ lệ GRR', en: 'GRR Percent' },
  grr_result: { vi: 'Kết quả GRR', en: 'GRR Result' },
  grr_status: { vi: 'Trạng thái GRR', en: 'GRR Status' },
  oot_id: { vi: 'ID OOT', en: 'OOT ID' },
  oot_discovery_date: { vi: 'Ngày phát hiện OOT', en: 'OOT Discovery Date' },
  oot_parameter: { vi: 'Thông số OOT', en: 'OOT Parameter' },
  oot_magnitude: { vi: 'Biên độ OOT', en: 'OOT Magnitude' },
  oot_direction: { vi: 'Chiều lệch OOT', en: 'OOT Direction' },
  kaizen_id: { vi: 'ID Kaizen', en: 'Kaizen ID' },
  kaizen_number: { vi: 'Số Kaizen', en: 'Kaizen Number' },
  kaizen_type: { vi: 'Loại Kaizen', en: 'Kaizen Type' },
  qrqc_id: { vi: 'ID QRQC', en: 'QRQC ID' },
  qrqc_number: { vi: 'Số QRQC', en: 'QRQC Number' },
  qrqc_level: { vi: 'Cấp QRQC', en: 'QRQC Level' },
  andon_id: { vi: 'ID Andon', en: 'Andon ID' },
  andon_type: { vi: 'Loại Andon', en: 'Andon Type' },
  andon_color: { vi: 'Màu Andon', en: 'Andon Color' },
  smed_id: { vi: 'ID SMED', en: 'SMED ID' },
  smed_number: { vi: 'Số SMED', en: 'SMED Number' },
  serial_lot_trace_status: { vi: 'Trạng thái truy xuất serial/lô', en: 'Serial/Lot Trace Status' },
  real_data_collected: { vi: 'Dữ liệu thực tế đã thu thập', en: 'Actual Data Collected' },
  capacity_hours: { vi: 'Giờ công suất', en: 'Capacity Hours' },
  load_hours: { vi: 'Giờ tải', en: 'Load Hours' },
  created_at: { vi: 'Ngày tạo', en: 'Created At' },
  created_by: { vi: 'Người tạo', en: 'Created By' },
  updated_at: { vi: 'Ngày cập nhật', en: 'Updated At' },
  updated_by: { vi: 'Người cập nhật', en: 'Updated By' },
  approved_at: { vi: 'Ngày phê duyệt', en: 'Approved At' },
  approved_by: { vi: 'Người phê duyệt', en: 'Approved By' },
  reviewed_at: { vi: 'Ngày xem xét', en: 'Reviewed At' },
  reviewed_by: { vi: 'Người xem xét', en: 'Reviewed By' },
  user_id: { vi: 'ID người dùng', en: 'User ID' },
  employee_id: { vi: 'ID nhân viên', en: 'Employee ID' },
  employee_name: { vi: 'Họ tên nhân viên', en: 'Employee Name' },
  user_id_code: { vi: 'Mã người dùng', en: 'User ID Code' },
  role: { vi: 'Vai trò', en: 'Role' },
  full_name: { vi: 'Họ và tên', en: 'Full Name' },
  username: { vi: 'Tên đăng nhập', en: 'Username' },
  title: { vi: 'Tiêu đề', en: 'Title' },
  department: { vi: 'Phòng ban', en: 'Department' },
  notes: { vi: 'Ghi chú', en: 'Notes' },
  content: { vi: 'Nội dung', en: 'Content' },
  schema: { vi: 'Lược đồ', en: 'Schema' },
  data: { vi: 'Dữ liệu', en: 'Data' },
  year: { vi: 'Năm', en: 'Year' },
  version: { vi: 'Phiên bản', en: 'Version' },
  version_number: { vi: 'Số phiên bản', en: 'Version Number' },
  effective_date: { vi: 'Ngày hiệu lực', en: 'Effective Date' },
  sequence_number: { vi: 'Số thứ tự', en: 'Sequence Number' },
  fiscal_year: { vi: 'Năm tài chính', en: 'Fiscal Year' },
  current_counter: { vi: 'Bộ đếm hiện tại', en: 'Current Counter' },
  source_record: { vi: 'Hồ sơ nguồn', en: 'Source Record' },
  commit_output: { vi: 'Kết quả commit', en: 'Commit Output' },
  entity_id: { vi: 'ID đối tượng', en: 'Entity ID' },
  submission_id: { vi: 'ID lần nộp', en: 'Submission ID' },
  queue_id: { vi: 'ID hàng đợi', en: 'Queue ID' },
  failure_cause: { vi: 'Nguyên nhân lỗi', en: 'Failure Cause' },
  failure_mode_id: { vi: 'ID dạng lỗi', en: 'Failure Mode ID' },
  root_cause: { vi: 'Nguyên nhân gốc', en: 'Root Cause' },
  closed_at: { vi: 'Ngày đóng', en: 'Closed At' },
  submitted_at: { vi: 'Ngày gửi', en: 'Submitted At' },
  is_active: { vi: 'Đang hoạt động', en: 'Is Active' },
  logged_in: { vi: 'Đã đăng nhập', en: 'Logged In' },
  mfa_pending: { vi: 'MFA chờ xử lý', en: 'MFA Pending' },
  enroll_pending: { vi: 'Chờ kích hoạt', en: 'Enroll Pending' },
  pending_expires_in: { vi: 'Thời gian chờ hết hạn', en: 'Pending Expires In' },
  auth_expired: { vi: 'Xác thực hết hạn', en: 'Auth Expired' },
  server_time: { vi: 'Thời gian máy chủ', en: 'Server Time' },
  initialized: { vi: 'Đã khởi tạo', en: 'Initialized' },
  secret: { vi: 'Bí mật', en: 'Secret' },
  password: { vi: 'Mật khẩu', en: 'Password' },
  mfa_required: { vi: 'Yêu cầu MFA', en: 'MFA Required' },
  enroll_required: { vi: 'Yêu cầu kích hoạt', en: 'Enroll Required' },
  otpauth_url: { vi: 'URL OTPAuth', en: 'OTPAuth URL' },
  timezone: { vi: 'Múi giờ', en: 'Timezone' },
  portal_language: { vi: 'Ngôn ngữ cổng thông tin', en: 'Portal Language' },
  current_user_username: { vi: 'Tên đăng nhập người dùng hiện tại', en: 'Current User Username' },
  current_user_name: { vi: 'Tên người dùng hiện tại', en: 'Current User Name' },
  current_user_role: { vi: 'Vai trò người dùng hiện tại', en: 'Current User Role' },
  current_user_dept: { vi: 'Phòng ban người dùng hiện tại', en: 'Current User Department' },
  session_last_active: { vi: 'Thời điểm hoạt động cuối', en: 'Session Last Active' },
  last_edit_by: { vi: 'Người sửa lần cuối', en: 'Last Edit By' },
  last_edit_role: { vi: 'Vai trò sửa lần cuối', en: 'Last Edit Role' },
  last_edit_note: { vi: 'Ghi chú sửa lần cuối', en: 'Last Edit Note' },
  version_history_entry: { vi: 'Mục lịch sử phiên bản', en: 'Version History Entry' },
  change_reason: { vi: 'Lý do thay đổi', en: 'Change Reason' },
  event_title: { vi: 'Tiêu đề sự kiện', en: 'Event Title' },
  submission_reason: { vi: 'Lý do nộp hồ sơ', en: 'Submission Reason' },
  training_required: { vi: 'Yêu cầu đào tạo', en: 'Training Required' },
};

export const worldFieldDefinitions = {
  export_control_regime: { label: 'Chế độ kiểm soát xuất khẩu', labelEn: 'Export Control Regime', type: 'select', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  eccn_code: { label: 'Mã ECCN', labelEn: 'ECCN Code', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: { pattern: '^[0-9A-Z]{5}$' } },
  usml_category: { label: 'Danh mục USML', labelEn: 'USML Category', type: 'select', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  export_license_required: { label: 'Yêu cầu giấy phép xuất khẩu', labelEn: 'Export License Required', type: 'boolean', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  export_license_number: { label: 'Số giấy phép xuất khẩu', labelEn: 'Export License Number', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  export_license_expiry_date: { label: 'Ngày hết hạn giấy phép xuất khẩu', labelEn: 'Export License Expiry Date', type: 'date', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  end_user_statement_ref: { label: 'Tham chiếu tuyên bố người dùng cuối', labelEn: 'End User Statement Reference', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  customer_source_approval_required: { label: 'Yêu cầu CSA khách hàng', labelEn: 'Customer Source Approval Required', type: 'boolean', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  customer_source_approval_status: { label: 'Trạng thái CSA', labelEn: 'Customer Source Approval Status', type: 'badge', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  customer_source_approval_ref: { label: 'Mã tham chiếu CSA', labelEn: 'Customer Source Approval Reference', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  first_article_required: { label: 'Yêu cầu FAI', labelEn: 'First Article Required', type: 'boolean', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  fai_status: { label: 'Trạng thái FAI', labelEn: 'FAI Status', type: 'badge', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  as9102_form1_ref: { label: 'Tham chiếu AS9102 Form 1', labelEn: 'AS9102 Form 1 Reference', type: 'string', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  as9102_form2_ref: { label: 'Tham chiếu AS9102 Form 2', labelEn: 'AS9102 Form 2 Reference', type: 'string', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  as9102_form3_ref: { label: 'Tham chiếu AS9102 Form 3', labelEn: 'AS9102 Form 3 Reference', type: 'string', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  first_article_waiver_required: { label: 'Yêu cầu miễn trừ FAI', labelEn: 'First Article Waiver Required', type: 'boolean', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  first_article_waiver_ref: { label: 'Tham chiếu miễn trừ FAI', labelEn: 'First Article Waiver Reference', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  delta_fai_required: { label: 'Yêu cầu Delta FAI', labelEn: 'Delta FAI Required', type: 'boolean', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  delta_fai_reason: { label: 'Lý do Delta FAI', labelEn: 'Delta FAI Reason', type: 'textarea', source: 'world', dbColumn: null, group: 'quality', constraints: { minLength: 10, maxLength: 2000 } },
  nadcap_required: { label: 'Yêu cầu NADCAP', labelEn: 'NADCAP Required', type: 'boolean', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  special_process_category: { label: 'Nhóm công đoạn đặc biệt', labelEn: 'Special Process Category', type: 'select', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  special_process_supplier_id: { label: 'Nhà cung cấp công đoạn đặc biệt', labelEn: 'Special Process Supplier', type: 'number', source: 'world', dbColumn: null, group: 'compliance', constraints: { min: 1 } },
  nadcap_certificate_number: { label: 'Số chứng chỉ NADCAP', labelEn: 'NADCAP Certificate Number', type: 'string', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  nadcap_expiry_date: { label: 'Ngày hết hạn NADCAP', labelEn: 'NADCAP Expiry Date', type: 'date', source: 'world', dbColumn: null, group: 'compliance', constraints: {} },
  shelf_life_days: { label: 'Số ngày hạn sử dụng', labelEn: 'Shelf Life Days', type: 'duration', source: 'world', dbColumn: null, group: 'traceability', constraints: { min: 0 } },
  shelf_life_start_date: { label: 'Ngày bắt đầu hạn sử dụng', labelEn: 'Shelf Life Start Date', type: 'date', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  remaining_shelf_life_pct: { label: 'Phần trăm hạn sử dụng còn lại', labelEn: 'Remaining Shelf Life Percent', type: 'percentage', source: 'world', dbColumn: null, group: 'traceability', constraints: { min: 0, max: 100 } },
  heat_number: { label: 'Số mẻ nhiệt', labelEn: 'Heat Number', type: 'string', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  melt_number: { label: 'Số mẻ nấu', labelEn: 'Melt Number', type: 'string', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  mill_cert_number: { label: 'Số chứng chỉ vật liệu', labelEn: 'Mill Certificate Number', type: 'string', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  material_genealogy_ref: { label: 'Tham chiếu phả hệ vật liệu', labelEn: 'Material Genealogy Reference', type: 'string', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  flight_critical_flag: { label: 'Cờ trọng yếu bay', labelEn: 'Flight-Critical Flag', type: 'boolean', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  safety_critical_flag: { label: 'Cờ an toàn trọng yếu', labelEn: 'Safety-Critical Flag', type: 'boolean', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  key_characteristic_flag: { label: 'Cờ đặc tính trọng yếu', labelEn: 'Key Characteristic Flag', type: 'boolean', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  cpk_target: { label: 'Mục tiêu Cpk', labelEn: 'Cpk Target', type: 'number', source: 'world', dbColumn: null, group: 'quality', constraints: { min: 0, max: 10 } },
  ppk_target: { label: 'Mục tiêu Ppk', labelEn: 'Ppk Target', type: 'number', source: 'world', dbColumn: null, group: 'quality', constraints: { min: 0, max: 10 } },
  balloon_number: { label: 'Số balloon đặc tính', labelEn: 'Balloon Number', type: 'string', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  drawing_zone: { label: 'Vùng bản vẽ', labelEn: 'Drawing Zone', type: 'string', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  buy_to_fly_ratio: { label: 'Tỷ lệ buy-to-fly', labelEn: 'Buy-to-Fly Ratio', type: 'number', source: 'world', dbColumn: null, group: 'cost', constraints: { min: 0 } },
  billet_weight_kg: { label: 'Khối lượng phôi (kg)', labelEn: 'Billet Weight (kg)', type: 'weight', source: 'world', dbColumn: null, group: 'dimensions', constraints: { min: 0 } },
  finished_weight_kg: { label: 'Khối lượng thành phẩm (kg)', labelEn: 'Finished Weight (kg)', type: 'weight', source: 'world', dbColumn: null, group: 'dimensions', constraints: { min: 0 } },
  tool_life_limit: { label: 'Giới hạn tuổi thọ dao', labelEn: 'Tool Life Limit', type: 'number', source: 'world', dbColumn: null, group: 'traceability', constraints: { min: 0 } },
  tool_life_used: { label: 'Tuổi thọ dao đã dùng', labelEn: 'Tool Life Used', type: 'number', source: 'world', dbColumn: null, group: 'traceability', constraints: { min: 0 } },
  tool_life_remaining: { label: 'Tuổi thọ dao còn lại', labelEn: 'Tool Life Remaining', type: 'number', source: 'world', dbColumn: null, group: 'traceability', constraints: { min: 0 } },
  offset_history: { label: 'Lịch sử bù dao', labelEn: 'Offset History', type: 'json', source: 'world', dbColumn: null, group: 'traceability', constraints: {} },
  source_inspection_status: { label: 'Trạng thái kiểm tra nguồn', labelEn: 'Source Inspection Status', type: 'badge', source: 'world', dbColumn: null, group: 'quality', constraints: {} },
  digital_thread_status: { label: 'Trạng thái digital thread', labelEn: 'Digital Thread Status', type: 'badge', source: 'fusion', dbColumn: null, group: 'traceability', constraints: {} },
  evidence_hash: { label: 'Giá trị băm bằng chứng', labelEn: 'Evidence Hash', type: 'string', source: 'fusion', dbColumn: null, group: 'compliance', constraints: { minLength: 32, maxLength: 256 } },
  evidence_chain_ref: { label: 'Tham chiếu chuỗi bằng chứng', labelEn: 'Evidence Chain Reference', type: 'string', source: 'fusion', dbColumn: null, group: 'compliance', constraints: {} },
};

export const fieldGroups = {
  audit_trail: ['created_by', 'created_at', 'updated_by', 'updated_at', 'approved_by', 'approved_at'],
  document_audit: ['created_by', 'created_at', 'reviewed_by', 'reviewed_at', 'approved_by', 'approved_at'],
  quote_header: ['quote_number', 'customer_id', 'customer_name', 'status', 'requested_date', 'promise_date', 'commit_date', 'currency_code', 'payment_terms', 'incoterm', 'markup_pct', 'gross_margin_pct', 'total_order_value', 'flight_critical_flag', 'customer_source_approval_required'],
  quote_line: ['line_number', 'item_id', 'item_number', 'description', 'material', 'qty', 'unit_of_measure', 'estimated_cycle_time', 'estimated_setup_time', 'material_cost', 'labor_cost', 'overhead_cost', 'markup_pct', 'unit_price', 'extended_amount', 'buy_to_fly_ratio'],
  sales_header: ['sales_order_number', 'customer_id', 'customer_name', 'status', 'requested_date', 'promise_date', 'commit_date', 'ship_to_name', 'ship_method', 'source_inspection_status', 'flight_critical_flag'],
  sales_line: ['line_number', 'item_id', 'item_number', 'customer_part_number', 'revision', 'qty_ordered', 'qty_shipped', 'unit_price', 'due_date', 'source_inspection_status', 'as9102_form1_ref'],
  work_order_core: ['wo_number', 'status', 'item_id', 'item_number', 'revision', 'qty_ordered', 'qty_completed', 'qty_scrapped', 'due_date', 'bom_id', 'routing_id', 'materials_available', 'fai_status', 'digital_thread_status'],
  work_order_operation: ['operation_number', 'operation_name', 'work_center_id', 'setup_time_min', 'run_time_min', 'queue_time_min', 'is_hold_point', 'tool_life_remaining', 'cpk_target', 'ppk_target', 'source_inspection_status'],
  work_order_material: ['line_number', 'component_item_id', 'component_item_number', 'lot_id', 'lot_number', 'qty_required', 'qty_issued', 'heat_number', 'melt_number', 'shelf_life_start_date', 'remaining_shelf_life_pct'],
  work_order_labor: ['employee_id', 'employee_name', 'shift_code', 'start_time', 'end_time', 'labor_hours', 'labor_rate'],
  planning: ['plan_number', 'plan_date', 'status', 'resource_id', 'resource_name', 'constraint_type', 'capacity_hours', 'load_hours', 'schedule_adherence_pct'],
  supplier: ['supplier_code', 'supplier_name', 'status', 'country_code', 'vendor_rating', 'approved_date', 'nadcap_required', 'nadcap_certificate_number', 'source_inspection_status'],
  receiving: ['receipt_number', 'po_number', 'supplier_id', 'lot_number', 'qty_received', 'qty_accepted', 'qty_rejected', 'inspection_status', 'mill_cert_number', 'remaining_shelf_life_pct'],
  quality_case: ['ncr_number', 'status', 'description', 'defect_type', 'severity', 'source', 'item_id', 'work_order_id', 'lot_id', 'qty_affected', 'disposition', 'root_cause_category', 'root_cause_description', 'evidence_notes'],
  capa_case: ['capa_number', 'status', 'title', 'description', 'owner_id', 'due_date', 'effectiveness_review_date', 'root_cause_category', 'containment_summary'],
  fai: ['fai_number', 'status', 'item_id', 'item_number', 'revision', 'as9102_form1_ref', 'as9102_form2_ref', 'as9102_form3_ref', 'first_article_waiver_ref', 'delta_fai_required', 'customer_source_approval_ref'],
  fmea: ['fmea_number', 'status', 'process_step', 'failure_mode', 'failure_effect', 'severity', 'occurrence', 'detection', 'risk_priority_number', 'recommended_action', 'cpk_target', 'ppk_target'],
  spc: ['control_chart_id', 'feature_name', 'balloon_number', 'sample_size', 'mean_value', 'range_value', 'cpk_value', 'ppk_value', 'upper_control_limit', 'lower_control_limit'],
  calibration: ['calibration_number', 'equipment_id', 'equipment_name', 'status', 'last_calibration_date', 'next_calibration_date', 'calibration_result', 'measurement_uncertainty'],
  evidence: ['record_id', 'evidence_hash', 'evidence_chain_ref', 'digital_signature_status', 'custody_owner', 'retention_policy_code', 'created_by', 'created_at'],
  report: ['report_id', 'report_name', 'period_start', 'period_end', 'target_value', 'actual_value', 'variance_pct'],
  document: ['doc_id', 'doc_title', 'doc_type', 'revision', 'status', 'effective_date', 'owner_role', 'reviewed_by', 'approved_by', 'training_required'],
  administration: ['user_id', 'username', 'full_name', 'email', 'role_code', 'status', 'last_login_at', 'mfa_enabled', 'permission_set'],
};

export const packSpecs = [
  ['bao_gia', 'quote_header', 'Báo giá - Phần đầu', 'Quote Header', ['quote_header', 'audit_trail']],
  ['bao_gia', 'quote_line', 'Báo giá - Dòng chi tiết', 'Quote Line', ['quote_line']],
  ['bao_gia', 'material_estimate', 'Ước tính vật liệu', 'Material Estimate', ['quote_line']],
  ['bao_gia', 'cycle_time_estimate', 'Ước tính thời gian chu kỳ', 'Cycle Time Estimate', ['work_order_operation']],
  ['bao_gia', 'tooling_cost', 'Chi phí dao cụ', 'Tooling Cost', ['quote_line']],
  ['bao_gia', 'markup_calculation', 'Tính giá cộng thêm', 'Markup Calculation', ['quote_header', 'quote_line']],
  ['don_hang', 'so_header', 'Đơn hàng bán - Phần đầu', 'Sales Order Header', ['sales_header', 'audit_trail']],
  ['don_hang', 'so_line', 'Đơn hàng bán - Dòng', 'Sales Order Line', ['sales_line']],
  ['don_hang', 'jo_header', 'Lệnh công việc - Phần đầu', 'Job Order Header', ['sales_header', 'planning']],
  ['don_hang', 'jo_line', 'Lệnh công việc - Dòng', 'Job Order Line', ['sales_line', 'planning']],
  ['don_hang', 'wo_header', 'Lệnh sản xuất - Phần đầu', 'Work Order Header', ['work_order_core', 'audit_trail']],
  ['don_hang', 'wo_operation', 'Lệnh sản xuất - Công đoạn', 'Work Order Operation', ['work_order_operation']],
  ['don_hang', 'wo_material', 'Lệnh sản xuất - Vật liệu', 'Work Order Material', ['work_order_material']],
  ['don_hang', 'wo_labor', 'Lệnh sản xuất - Nhân công', 'Work Order Labor', ['work_order_labor']],
  ['ke_hoach', 'capacity_plan', 'Kế hoạch năng lực', 'Capacity Plan', ['planning']],
  ['ke_hoach', 'mrp_suggestion', 'Đề xuất MRP', 'MRP Suggestion', ['planning', 'supplier']],
  ['ke_hoach', 'scheduling_gantt', 'Lập lịch Gantt', 'Scheduling Gantt', ['planning', 'work_order_core']],
  ['ke_hoach', 'resource_calendar', 'Lịch nguồn lực', 'Resource Calendar', ['planning']],
  ['ke_hoach', 'constraint_set', 'Bộ ràng buộc', 'Constraint Set', ['planning']],
  ['mua_hang', 'po_header', 'Đơn mua hàng - Phần đầu', 'Purchase Order Header', ['supplier', 'audit_trail']],
  ['mua_hang', 'po_line', 'Đơn mua hàng - Dòng', 'Purchase Order Line', ['quote_line', 'supplier']],
  ['mua_hang', 'vendor_master', 'Danh mục nhà cung cấp', 'Vendor Master', ['supplier', 'audit_trail']],
  ['mua_hang', 'receiving_inspection', 'Kiểm tra đầu vào', 'Receiving Inspection', ['receiving', 'quality_case']],
  ['mua_hang', 'goods_receipt', 'Phiếu nhập hàng', 'Goods Receipt', ['receiving', 'audit_trail']],
  ['mua_hang', 'three_way_match', 'Đối soát 3 chiều', 'Three-Way Match', ['receiving', 'quote_header']],
  ['san_xuat', 'wo_dispatch', 'Điều độ WO', 'WO Dispatch', ['work_order_core', 'planning']],
  ['san_xuat', 'wo_execution', 'Thực thi WO', 'WO Execution', ['work_order_core', 'work_order_operation']],
  ['san_xuat', 'wo_clock', 'Ghi nhận thời gian WO', 'WO Clock', ['work_order_labor', 'planning']],
  ['san_xuat', 'machine_setup', 'Thiết lập máy', 'Machine Setup', ['work_order_operation', 'spc']],
  ['san_xuat', 'tool_management', 'Quản lý dao cụ', 'Tool Management', ['work_order_operation']],
  ['san_xuat', 'scrap_report', 'Báo cáo phế phẩm', 'Scrap Report', ['work_order_core', 'quality_case']],
  ['san_xuat', 'shift_handoff', 'Bàn giao ca', 'Shift Handoff', ['work_order_core', 'evidence']],
  ['chat_luong', 'ncr_form', 'Biểu mẫu NCR', 'NCR Form', ['quality_case', 'evidence']],
  ['chat_luong', 'capa_form', 'Biểu mẫu CAPA', 'CAPA Form', ['capa_case', 'evidence']],
  ['chat_luong', 'fai_form', 'Biểu mẫu FAI', 'FAI Form', ['fai', 'evidence']],
  ['chat_luong', 'inspection_lot', 'Lô kiểm tra', 'Inspection Lot', ['receiving', 'spc']],
  ['chat_luong', 'spc_control_chart', 'Biểu đồ SPC', 'SPC Control Chart', ['spc']],
  ['chat_luong', 'fmea_worksheet', 'Phiếu FMEA', 'FMEA Worksheet', ['fmea']],
  ['chat_luong', 'audit_finding', 'Điểm không phù hợp đánh giá', 'Audit Finding', ['quality_case', 'document']],
  ['chat_luong', 'calibration_record', 'Hồ sơ hiệu chuẩn', 'Calibration Record', ['calibration', 'evidence']],
  ['ho_so', 'evidence_record', 'Hồ sơ bằng chứng', 'Evidence Record', ['evidence']],
  ['ho_so', 'hash_chain', 'Chuỗi băm', 'Hash Chain', ['evidence']],
  ['ho_so', 'custody_log', 'Nhật ký bàn giao', 'Custody Log', ['evidence']],
  ['ho_so', 'digital_signature', 'Chữ ký số', 'Digital Signature', ['evidence']],
  ['ho_so', 'retention_policy', 'Chính sách lưu giữ', 'Retention Policy', ['evidence', 'document']],
  ['bao_cao', 'kpi_card', 'Thẻ KPI', 'KPI Card', ['report']],
  ['bao_cao', 'trend_chart', 'Biểu đồ xu hướng', 'Trend Chart', ['report']],
  ['bao_cao', 'pareto_chart', 'Biểu đồ Pareto', 'Pareto Chart', ['report', 'quality_case']],
  ['bao_cao', 'spc_chart', 'Biểu đồ SPC', 'SPC Chart', ['spc', 'report']],
  ['bao_cao', 'oee_dashboard', 'Bảng điều khiển OEE', 'OEE Dashboard', ['report', 'planning', 'work_order_core']],
  ['bao_cao', 'copq_breakdown', 'Phân rã COPQ', 'COPQ Breakdown', ['report', 'quality_case']],
  ['bao_cao', 'supplier_scorecard', 'Thẻ điểm nhà cung cấp', 'Supplier Scorecard', ['supplier', 'report']],
  ['tai_lieu', 'doc_master', 'Danh mục tài liệu', 'Document Master', ['document', 'document_audit']],
  ['tai_lieu', 'doc_revision', 'Phiên bản tài liệu', 'Document Revision', ['document', 'document_audit']],
  ['tai_lieu', 'doc_approval', 'Phê duyệt tài liệu', 'Document Approval', ['document', 'document_audit']],
  ['tai_lieu', 'doc_distribution', 'Phân phối tài liệu', 'Document Distribution', ['document', 'document_audit']],
  ['tai_lieu', 'doc_training_link', 'Liên kết đào tạo tài liệu', 'Document Training Link', ['document', 'administration']],
  ['quan_tri', 'user_profile', 'Hồ sơ người dùng', 'User Profile', ['administration']],
  ['quan_tri', 'role_definition', 'Định nghĩa vai trò', 'Role Definition', ['administration']],
  ['quan_tri', 'permission_matrix', 'Ma trận phân quyền', 'Permission Matrix', ['administration']],
  ['quan_tri', 'audit_log_viewer', 'Trình xem nhật ký kiểm soát', 'Audit Log Viewer', ['administration', 'evidence']],
  ['quan_tri', 'system_config', 'Cấu hình hệ thống', 'System Configuration', ['administration']],
  ['quan_tri', 'integration_monitor', 'Giám sát tích hợp', 'Integration Monitor', ['administration', 'planning']],
];

export const workflowSpecs = [
  {
    workflowId: 'wf_quote_lifecycle',
    name: 'Vòng đời báo giá',
    nameEn: 'Quote Lifecycle',
    entity: 'quote',
    standard: 'internal',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['review', 'Xem xét', 'Review', '#3b82f6'],
      ['sent', 'Đã gửi', 'Sent', '#8b5cf6'],
      ['won', 'Thắng', 'Won', '#10b981'],
      ['lost', 'Thua', 'Lost', '#ef4444'],
      ['expired', 'Hết hạn', 'Expired', '#f59e0b'],
    ],
    transitions: [
      ['draft', 'review', 'submit', 'Gửi xem xét', 'Submit for Review'],
      ['review', 'sent', 'send', 'Gửi khách hàng', 'Send to Customer'],
      ['sent', 'won', 'award', 'Trúng báo giá', 'Award Quote'],
      ['sent', 'lost', 'lose', 'Mất báo giá', 'Lose Quote'],
      ['sent', 'expired', 'expire', 'Hết hạn', 'Expire'],
    ],
    upstreamTriggers: ['customer_rfq_received'],
    downstreamEffects: ['sales_order_create', 'cost_baseline_lock'],
  },
  {
    workflowId: 'wf_sales_order',
    name: 'Thực hiện đơn hàng bán',
    nameEn: 'Sales Order Fulfillment',
    entity: 'sales_order',
    standard: 'internal',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['confirmed', 'Đã xác nhận', 'Confirmed', '#3b82f6'],
      ['engineering_ready', 'Sẵn sàng kỹ thuật', 'Engineering Ready', '#8b5cf6'],
      ['in_production', 'Đang sản xuất', 'In Production', '#f59e0b'],
      ['shipped', 'Đã giao', 'Shipped', '#10b981'],
      ['closed', 'Đã đóng', 'Closed', '#64748b'],
    ],
    transitions: [
      ['draft', 'confirmed', 'confirm', 'Xác nhận', 'Confirm'],
      ['confirmed', 'engineering_ready', 'release_engineering', 'Nhả kỹ thuật', 'Release Engineering'],
      ['engineering_ready', 'in_production', 'launch', 'Khởi chạy', 'Launch'],
      ['in_production', 'shipped', 'ship', 'Giao hàng', 'Ship'],
      ['shipped', 'closed', 'close', 'Đóng đơn', 'Close Order'],
    ],
    upstreamTriggers: ['quote_awarded'],
    downstreamEffects: ['job_order_create', 'shipment_release'],
  },
  {
    workflowId: 'wf_job_order',
    name: 'Lệnh công việc',
    nameEn: 'Job Order Lifecycle',
    entity: 'job_order',
    standard: 'internal',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['planned', 'Kế hoạch', 'Planned', '#3b82f6'],
      ['released', 'Đã phát hành', 'Released', '#8b5cf6'],
      ['active', 'Đang chạy', 'Active', '#f59e0b'],
      ['completed', 'Hoàn thành', 'Completed', '#10b981'],
      ['closed', 'Đã đóng', 'Closed', '#64748b'],
    ],
    transitions: [
      ['draft', 'planned', 'plan', 'Lập kế hoạch', 'Plan'],
      ['planned', 'released', 'release', 'Phát hành', 'Release'],
      ['released', 'active', 'start', 'Bắt đầu', 'Start'],
      ['active', 'completed', 'complete', 'Hoàn thành', 'Complete'],
      ['completed', 'closed', 'close', 'Đóng', 'Close'],
    ],
    upstreamTriggers: ['sales_order_confirmed'],
    downstreamEffects: ['work_order_create', 'mrp_reservation'],
  },
  {
    workflowId: 'wf_work_order_execution',
    name: 'Thực thi WO',
    nameEn: 'Work Order Execution',
    entity: 'work_order',
    standard: 'ISA-95 / internal',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['planned', 'Đã lập kế hoạch', 'Planned', '#3b82f6'],
      ['released', 'Đã phát hành', 'Released', '#8b5cf6'],
      ['in_production', 'Đang sản xuất', 'In Production', '#f59e0b'],
      ['quality_hold', 'Giữ chất lượng', 'Quality Hold', '#ef4444'],
      ['closed', 'Đã đóng', 'Closed', '#10b981'],
      ['cancelled', 'Đã hủy', 'Cancelled', '#64748b'],
    ],
    transitions: [
      ['draft', 'planned', 'plan', 'Lập kế hoạch', 'Plan'],
      ['planned', 'released', 'release', 'Phát hành', 'Release'],
      ['released', 'in_production', 'start', 'Bắt đầu', 'Start Production'],
      ['in_production', 'quality_hold', 'hold', 'Giữ chất lượng', 'Quality Hold'],
      ['quality_hold', 'in_production', 'release_hold', 'Nhả giữ', 'Release Hold'],
      ['in_production', 'closed', 'close', 'Đóng WO', 'Close WO'],
    ],
    upstreamTriggers: ['job_order_released', 'material_reserved'],
    downstreamEffects: ['lot_trace_record', 'fai_trigger', 'ncr_auto_create'],
  },
  {
    workflowId: 'wf_purchase_order',
    name: 'Đơn mua hàng',
    nameEn: 'Purchase Order Lifecycle',
    entity: 'purchase_order',
    standard: 'internal',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['pending_approval', 'Chờ phê duyệt', 'Pending Approval', '#f59e0b'],
      ['approved', 'Đã phê duyệt', 'Approved', '#3b82f6'],
      ['released', 'Đã phát hành', 'Released', '#8b5cf6'],
      ['partial', 'Nhận một phần', 'Partial', '#f59e0b'],
      ['received', 'Đã nhận', 'Received', '#10b981'],
      ['closed', 'Đã đóng', 'Closed', '#64748b'],
    ],
    transitions: [
      ['draft', 'pending_approval', 'submit', 'Gửi phê duyệt', 'Submit'],
      ['pending_approval', 'approved', 'approve', 'Phê duyệt', 'Approve'],
      ['approved', 'released', 'release', 'Phát hành', 'Release'],
      ['released', 'partial', 'receive_partial', 'Nhận một phần', 'Receive Partial'],
      ['released', 'received', 'receive_full', 'Nhận đủ', 'Receive Full'],
      ['received', 'closed', 'close', 'Đóng', 'Close'],
    ],
    upstreamTriggers: ['mrp_purchase_suggestion'],
    downstreamEffects: ['goods_receipt_create', 'supplier_otif_update'],
  },
  {
    workflowId: 'wf_receiving_inspection',
    name: 'Kiểm tra đầu vào',
    nameEn: 'Receiving Inspection',
    entity: 'receiving_inspection',
    standard: 'AS9100D §8.4',
    states: [
      ['queued', 'Chờ kiểm tra', 'Queued', '#3b82f6'],
      ['in_progress', 'Đang kiểm tra', 'In Progress', '#f59e0b'],
      ['accepted', 'Đạt', 'Accepted', '#10b981'],
      ['rejected', 'Không đạt', 'Rejected', '#ef4444'],
      ['waived', 'Miễn kiểm', 'Waived', '#8b5cf6'],
    ],
    transitions: [
      ['queued', 'in_progress', 'start', 'Bắt đầu', 'Start'],
      ['in_progress', 'accepted', 'accept', 'Chấp nhận', 'Accept'],
      ['in_progress', 'rejected', 'reject', 'Từ chối', 'Reject'],
      ['queued', 'waived', 'waive', 'Miễn kiểm', 'Waive'],
    ],
    upstreamTriggers: ['goods_receipt_posted'],
    downstreamEffects: ['inventory_release', 'ncr_auto_create'],
  },
  {
    workflowId: 'wf_supplier_qualification',
    name: 'Phê duyệt nhà cung cấp',
    nameEn: 'Supplier Qualification',
    entity: 'supplier',
    standard: 'AS9100D §8.4',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['assessment', 'Đánh giá', 'Assessment', '#3b82f6'],
      ['approved', 'Đã phê duyệt', 'Approved', '#10b981'],
      ['conditional', 'Có điều kiện', 'Conditional', '#f59e0b'],
      ['hold', 'Tạm dừng', 'Hold', '#ef4444'],
      ['inactive', 'Ngưng hoạt động', 'Inactive', '#64748b'],
    ],
    transitions: [
      ['draft', 'assessment', 'assess', 'Đánh giá', 'Assess'],
      ['assessment', 'approved', 'approve', 'Phê duyệt', 'Approve'],
      ['assessment', 'conditional', 'conditional_approve', 'Duyệt có điều kiện', 'Conditional Approve'],
      ['approved', 'hold', 'hold', 'Tạm dừng', 'Hold'],
      ['hold', 'approved', 'reactivate', 'Kích hoạt lại', 'Reactivate'],
    ],
    upstreamTriggers: ['supplier_created'],
    downstreamEffects: ['asl_entry_create', 'supplier_scorecard_update'],
  },
  {
    workflowId: 'wf_ncr',
    name: 'Xử lý NCR',
    nameEn: 'NCR Processing',
    entity: 'ncr',
    standard: 'AS9100D §10.2',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['submitted', 'Đã gửi', 'Submitted', '#3b82f6'],
      ['under_review', 'Đang xem xét', 'Under Review', '#f59e0b'],
      ['disposition_set', 'Đã xác lập xử lý', 'Disposition Set', '#8b5cf6'],
      ['containment_active', 'Đang ngăn chặn', 'Containment Active', '#f59e0b'],
      ['close_requested', 'Yêu cầu đóng', 'Close Requested', '#3b82f6'],
      ['closed', 'Đã đóng', 'Closed', '#10b981'],
    ],
    transitions: [
      ['draft', 'submitted', 'submit', 'Gửi duyệt', 'Submit'],
      ['submitted', 'under_review', 'assign_review', 'Phân công xem xét', 'Assign Review'],
      ['under_review', 'disposition_set', 'set_disposition', 'Xác lập xử lý', 'Set Disposition'],
      ['disposition_set', 'containment_active', 'start_containment', 'Bắt đầu ngăn chặn', 'Start Containment'],
      ['containment_active', 'close_requested', 'request_close', 'Yêu cầu đóng', 'Request Close'],
      ['close_requested', 'closed', 'close', 'Đóng NCR', 'Close NCR'],
    ],
    upstreamTriggers: ['wo_defect_found', 'receiving_inspection_fail', 'customer_complaint'],
    downstreamEffects: ['lot_quarantine', 'capa_auto_create', 'supplier_scorecard_deduct'],
  },
  {
    workflowId: 'wf_capa',
    name: 'Xử lý CAPA',
    nameEn: 'CAPA Lifecycle',
    entity: 'capa',
    standard: 'AS9100D §10.2 / ISO 13485',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['initiated', 'Khởi tạo', 'Initiated', '#3b82f6'],
      ['action_planning', 'Lập kế hoạch hành động', 'Action Planning', '#f59e0b'],
      ['implementation', 'Triển khai', 'Implementation', '#8b5cf6'],
      ['effectiveness_review', 'Đánh giá hiệu lực', 'Effectiveness Review', '#3b82f6'],
      ['closed', 'Đã đóng', 'Closed', '#10b981'],
    ],
    transitions: [
      ['draft', 'initiated', 'initiate', 'Khởi tạo', 'Initiate'],
      ['initiated', 'action_planning', 'plan', 'Lập kế hoạch', 'Plan'],
      ['action_planning', 'implementation', 'implement', 'Triển khai', 'Implement'],
      ['implementation', 'effectiveness_review', 'review', 'Đánh giá hiệu lực', 'Review'],
      ['effectiveness_review', 'closed', 'close', 'Đóng CAPA', 'Close CAPA'],
    ],
    upstreamTriggers: ['ncr_escalated', 'audit_major_finding', 'customer_complaint_8d'],
    downstreamEffects: ['training_update', 'control_plan_update', 'fmea_review'],
  },
  {
    workflowId: 'wf_fai',
    name: 'Kiểm tra FAI',
    nameEn: 'First Article Inspection',
    entity: 'fai',
    standard: 'AS9102',
    states: [
      ['planned', 'Lên kế hoạch', 'Planned', '#3b82f6'],
      ['in_progress', 'Đang thực hiện', 'In Progress', '#f59e0b'],
      ['review', 'Xem xét', 'Review', '#8b5cf6'],
      ['approved', 'Đã phê duyệt', 'Approved', '#10b981'],
      ['waived', 'Miễn trừ', 'Waived', '#64748b'],
    ],
    transitions: [
      ['planned', 'in_progress', 'start', 'Bắt đầu', 'Start'],
      ['in_progress', 'review', 'submit_review', 'Gửi xem xét', 'Submit Review'],
      ['review', 'approved', 'approve', 'Phê duyệt', 'Approve'],
      ['planned', 'waived', 'waive', 'Miễn trừ', 'Waive'],
    ],
    upstreamTriggers: ['new_part_release', 'major_revision_change'],
    downstreamEffects: ['shipment_release_hold', 'doc_package_create'],
  },
  {
    workflowId: 'wf_document_change_control',
    name: 'Kiểm soát thay đổi tài liệu',
    nameEn: 'Document Change Control',
    entity: 'document',
    standard: 'AS9100D §7.5',
    states: [
      ['draft', 'Nháp', 'Draft', '#94a3b8'],
      ['in_review', 'Đang xem xét', 'In Review', '#3b82f6'],
      ['pending_approval', 'Chờ phê duyệt', 'Pending Approval', '#f59e0b'],
      ['approved', 'Đã phê duyệt', 'Approved', '#10b981'],
      ['effective', 'Có hiệu lực', 'Effective', '#8b5cf6'],
      ['obsolete', 'Lỗi thời', 'Obsolete', '#64748b'],
    ],
    transitions: [
      ['draft', 'in_review', 'submit_review', 'Gửi xem xét', 'Submit Review'],
      ['in_review', 'pending_approval', 'request_approval', 'Yêu cầu phê duyệt', 'Request Approval'],
      ['pending_approval', 'approved', 'approve', 'Phê duyệt', 'Approve'],
      ['approved', 'effective', 'release', 'Phát hành', 'Release'],
      ['effective', 'obsolete', 'obsolete', 'Lỗi thời', 'Obsolete'],
    ],
    upstreamTriggers: ['engineering_change_notice_approved'],
    downstreamEffects: ['training_assignment', 'traveler_template_update'],
  },
  {
    workflowId: 'wf_training_qualification',
    name: 'Đào tạo và chứng nhận',
    nameEn: 'Training and Qualification',
    entity: 'training',
    standard: 'AS9100D §7.2',
    states: [
      ['assigned', 'Đã giao', 'Assigned', '#3b82f6'],
      ['in_progress', 'Đang thực hiện', 'In Progress', '#f59e0b'],
      ['completed', 'Hoàn thành', 'Completed', '#8b5cf6'],
      ['qualified', 'Đủ điều kiện', 'Qualified', '#10b981'],
      ['expired', 'Hết hạn', 'Expired', '#ef4444'],
    ],
    transitions: [
      ['assigned', 'in_progress', 'start', 'Bắt đầu', 'Start'],
      ['in_progress', 'completed', 'complete', 'Hoàn thành', 'Complete'],
      ['completed', 'qualified', 'qualify', 'Xác nhận năng lực', 'Qualify'],
      ['qualified', 'expired', 'expire', 'Hết hạn', 'Expire'],
    ],
    upstreamTriggers: ['document_release', 'capa_training_required'],
    downstreamEffects: ['operator_authorization_update'],
  },
  {
    workflowId: 'wf_shipment_release',
    name: 'Phát hành giao hàng',
    nameEn: 'Shipment Release',
    entity: 'shipment_release',
    standard: 'AS9100D / internal',
    states: [
      ['blocked', 'Bị chặn', 'Blocked', '#ef4444'],
      ['ready', 'Sẵn sàng', 'Ready', '#3b82f6'],
      ['released', 'Đã phát hành', 'Released', '#10b981'],
      ['dispatched', 'Đã xuất kho', 'Dispatched', '#8b5cf6'],
      ['delivered', 'Đã giao', 'Delivered', '#10b981'],
    ],
    transitions: [
      ['blocked', 'ready', 'clear_hold', 'Xóa chặn', 'Clear Hold'],
      ['ready', 'released', 'release', 'Phát hành', 'Release'],
      ['released', 'dispatched', 'dispatch', 'Xuất kho', 'Dispatch'],
      ['dispatched', 'delivered', 'deliver', 'Giao hàng', 'Deliver'],
    ],
    upstreamTriggers: ['fai_approved', 'packing_complete'],
    downstreamEffects: ['invoice_create', 'customer_otd_update'],
  },
  {
    workflowId: 'wf_tool_life',
    name: 'Theo dõi tuổi thọ dao',
    nameEn: 'Tool Life Management',
    entity: 'tool',
    standard: 'MES best practice',
    states: [
      ['new', 'Mới', 'New', '#3b82f6'],
      ['qualified', 'Đủ điều kiện', 'Qualified', '#10b981'],
      ['in_use', 'Đang sử dụng', 'In Use', '#8b5cf6'],
      ['worn', 'Mòn', 'Worn', '#f59e0b'],
      ['replace', 'Cần thay', 'Replace', '#ef4444'],
      ['scrapped', 'Loại bỏ', 'Scrapped', '#64748b'],
    ],
    transitions: [
      ['new', 'qualified', 'qualify', 'Xác nhận', 'Qualify'],
      ['qualified', 'in_use', 'issue', 'Xuất dùng', 'Issue'],
      ['in_use', 'worn', 'wear', 'Ghi nhận mòn', 'Wear'],
      ['worn', 'replace', 'replace', 'Thay dao', 'Replace'],
      ['replace', 'scrapped', 'scrap', 'Loại bỏ', 'Scrap'],
    ],
    upstreamTriggers: ['machine_setup'],
    downstreamEffects: ['offset_history_capture', 'wo_hold_if_expired'],
  },
];

export const relationSpecs = [
  ['quote', 'quote_id', 'sales_order', 'quote_id', 'one_to_many', 'Báo giá → Đơn hàng bán'],
  ['sales_order', 'so_id', 'job_order', 'sales_order_id', 'one_to_many', 'SO → JO'],
  ['job_order', 'jo_id', 'work_order', 'job_order_id', 'one_to_many', 'JO → WO'],
  ['work_order', 'wo_id', 'work_order_operation', 'work_order_id', 'one_to_many', 'WO → Công đoạn WO'],
  ['work_order', 'wo_id', 'work_order_material', 'work_order_id', 'one_to_many', 'WO → Vật liệu WO'],
  ['work_order', 'wo_id', 'work_order_labor', 'work_order_id', 'one_to_many', 'WO → Nhân công WO'],
  ['work_order_operation', 'operation_id', 'lot', 'current_operation_id', 'one_to_many', 'Công đoạn → Lô WIP'],
  ['lot', 'lot_id', 'inspection_lot', 'lot_id', 'one_to_many', 'Lô → Lô kiểm tra'],
  ['inspection_lot', 'inspection_lot_id', 'ncr', 'inspection_lot_id', 'one_to_many', 'Inspection → NCR'],
  ['ncr', 'ncr_id', 'capa', 'source_ncr_id', 'one_to_many', 'NCR → CAPA'],
  ['capa', 'capa_id', 'evidence', 'parent_record_id', 'one_to_many', 'CAPA → Bằng chứng'],
  ['purchase_order', 'po_id', 'goods_receipt', 'purchase_order_id', 'one_to_many', 'PO → Phiếu nhập'],
  ['goods_receipt', 'gr_id', 'receiving_inspection', 'goods_receipt_id', 'one_to_many', 'Phiếu nhập → Kiểm tra đầu vào'],
  ['receiving_inspection', 'inspection_id', 'ncr', 'receiving_inspection_id', 'one_to_many', 'Kiểm tra đầu vào → NCR'],
  ['item', 'item_id', 'bom_header', 'item_id', 'one_to_many', 'Item → BOM'],
  ['item_revision', 'item_revision_id', 'bom_header', 'item_revision_id', 'one_to_many', 'Item Revision → BOM'],
  ['item', 'item_id', 'routing_header', 'item_id', 'one_to_many', 'Item → Routing'],
  ['routing_header', 'routing_id', 'routing_operation', 'routing_id', 'one_to_many', 'Routing → Công đoạn routing'],
  ['routing_header', 'routing_id', 'work_order', 'routing_id', 'one_to_many', 'Routing → WO'],
  ['bom_header', 'bom_id', 'work_order', 'bom_id', 'one_to_many', 'BOM → WO'],
  ['fai', 'fai_id', 'item_revision', 'item_revision_id', 'many_to_one', 'FAI → Item Revision'],
  ['fai', 'fai_id', 'doc_master', 'fai_id', 'one_to_many', 'FAI → Gói tài liệu'],
  ['fmea', 'fmea_id', 'control_plan', 'fmea_id', 'one_to_many', 'FMEA → Control Plan'],
  ['control_plan', 'control_plan_id', 'inspection_plan', 'control_plan_id', 'one_to_many', 'Control Plan → Inspection Plan'],
  ['inspection_plan', 'inspection_plan_id', 'spc_chart', 'inspection_plan_id', 'one_to_many', 'Inspection Plan → SPC'],
  ['supplier', 'supplier_id', 'asl_entry', 'supplier_id', 'one_to_many', 'Supplier → ASL'],
  ['supplier', 'supplier_id', 'supplier_scorecard', 'supplier_id', 'one_to_many', 'Supplier → Scorecard'],
  ['supplier_scorecard', 'scorecard_id', 'scar', 'scorecard_id', 'one_to_many', 'Scorecard → SCAR'],
  ['quote', 'quote_id', 'sales_order', 'source_quote_id', 'one_to_one', 'Quote → SO conversion'],
  ['calibration_record', 'calibration_id', 'equipment', 'equipment_id', 'many_to_one', 'Hiệu chuẩn → Thiết bị'],
  ['equipment', 'equipment_id', 'measurement_record', 'equipment_id', 'one_to_many', 'Thiết bị → Kết quả đo'],
  ['measurement_record', 'measurement_id', 'spc_chart', 'measurement_id', 'one_to_many', 'Đo lường → SPC'],
  ['sales_order', 'so_id', 'shipment_release', 'sales_order_id', 'one_to_many', 'SO → Phát hành giao hàng'],
  ['shipment_release', 'shipment_release_id', 'evidence', 'shipment_release_id', 'one_to_many', 'Phát hành giao hàng → Bằng chứng'],
  ['document', 'doc_id', 'training_assignment', 'doc_id', 'one_to_many', 'Tài liệu → Đào tạo'],
  ['training_assignment', 'training_id', 'user_profile', 'user_id', 'many_to_one', 'Đào tạo → Người dùng'],
  ['integration_monitor', 'integration_id', 'audit_log', 'integration_id', 'one_to_many', 'Tích hợp → Nhật ký kiểm soát'],
  ['special_process', 'special_process_id', 'purchase_order', 'special_process_id', 'one_to_many', 'Công đoạn đặc biệt → PO ngoài công'],
  ['supplier', 'supplier_id', 'special_process', 'supplier_id', 'one_to_many', 'Supplier → Công đoạn đặc biệt'],
  ['work_order_operation', 'operation_id', 'special_process', 'operation_id', 'one_to_many', 'Công đoạn → Công đoạn đặc biệt'],
  ['work_order', 'wo_id', 'fai', 'work_order_id', 'one_to_many', 'WO → FAI'],
  ['work_order', 'wo_id', 'ncr', 'work_order_id', 'one_to_many', 'WO → NCR'],
  ['work_order_material', 'lot_id', 'lot', 'lot_id', 'many_to_one', 'Vật liệu WO → Lô'],
  ['lot', 'parent_lot_id', 'lot', 'lot_id', 'many_to_one', 'Lô cha → Lô con'],
  ['lot', 'lot_id', 'evidence', 'lot_id', 'one_to_many', 'Lô → Bằng chứng'],
  ['work_order_operation', 'operation_id', 'machine_setup', 'operation_id', 'one_to_one', 'Công đoạn → Setup máy'],
  ['machine_setup', 'setup_id', 'tool_management', 'setup_id', 'one_to_many', 'Setup máy → Dao cụ'],
  ['tool_management', 'tool_id', 'evidence', 'tool_id', 'one_to_many', 'Dao cụ → Bằng chứng'],
  ['customer_complaint', 'complaint_id', 'ncr', 'customer_complaint_id', 'one_to_many', 'Khiếu nại → NCR'],
  ['customer_complaint', 'complaint_id', 'capa', 'customer_complaint_id', 'one_to_many', 'Khiếu nại → CAPA'],
  ['ecn', 'ecn_id', 'item_revision', 'ecn_id', 'one_to_many', 'ECN → Item Revision'],
  ['ecn', 'ecn_id', 'bom_header', 'ecn_id', 'one_to_many', 'ECN → BOM'],
  ['ecn', 'ecn_id', 'routing_header', 'ecn_id', 'one_to_many', 'ECN → Routing'],
  ['supplier_audit', 'audit_id', 'audit_finding', 'supplier_audit_id', 'one_to_many', 'Đánh giá NCC → Điểm không phù hợp'],
  ['audit_finding', 'finding_id', 'capa', 'audit_finding_id', 'one_to_many', 'Điểm đánh giá → CAPA'],
  ['audit_finding', 'finding_id', 'scar', 'audit_finding_id', 'one_to_many', 'Điểm đánh giá → SCAR'],
  ['ppap', 'ppap_id', 'fai', 'ppap_id', 'one_to_many', 'PPAP → FAI'],
  ['ppap', 'ppap_id', 'control_plan', 'ppap_id', 'one_to_many', 'PPAP → Control Plan'],
  ['ppap', 'ppap_id', 'evidence', 'ppap_id', 'one_to_many', 'PPAP → Bằng chứng'],
  ['ncr', 'ncr_id', 'deviation', 'ncr_id', 'one_to_many', 'NCR → Sai lệch / miễn trừ'],
  ['deviation', 'deviation_id', 'shipment_release', 'deviation_id', 'one_to_many', 'Miễn trừ → Phát hành giao hàng'],
  ['supplier', 'supplier_id', 'receiving_inspection', 'supplier_id', 'one_to_many', 'Supplier → Kiểm tra đầu vào'],
  ['supplier', 'supplier_id', 'goods_receipt', 'supplier_id', 'one_to_many', 'Supplier → Phiếu nhập'],
  ['sales_order', 'so_id', 'quote', 'sales_order_id', 'many_to_one', 'SO → Báo giá gốc'],
  ['document', 'doc_id', 'evidence', 'doc_id', 'one_to_many', 'Tài liệu → Bằng chứng'],
  ['user_profile', 'user_id', 'digital_signature', 'user_id', 'one_to_many', 'Người dùng → Chữ ký số'],
  ['retention_policy', 'policy_id', 'evidence', 'retention_policy_id', 'one_to_many', 'Chính sách lưu giữ → Bằng chứng'],
];
