#!/usr/bin/env python3
"""
Create Excel with ALL remaining English words and Vietnamese translations.
Threshold: 1+ occurrence. Provide translations for ALL words.
"""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

# Vietnamese words without diacritics
VIETNAMESE = {
    'kinh', 'nguy', 'trung', 'sung', 'trang', 'treo', 'nhau', 'thuc',
    'bien', 'nhat', 'luong', 'bang', 'dung', 'theo', 'trong', 'thay',
    'giao', 'quan', 'minh', 'ngay', 'gian', 'nhanh', 'danh', 'truy',
    'khai', 'sang', 'sinh', 'then', 'tham', 'khao', 'trinh', 'dich',
    'cung', 'phat', 'hanh', 'hien', 'tieu', 'chuan', 'pham', 'nham',
    'phuc', 'doan', 'tang', 'giam', 'hieu', 'chua', 'chinh', 'chap',
    'nhan', 'thong', 'dong', 'trai', 'phai', 'tren', 'duoi', 'giua',
    'ngoai', 'truoc', 'dien', 'lang', 'nghe', 'tinh', 'toan', 'hoan',
    'thanh', 'cong', 'viec', 'hang', 'khach', 'xuat', 'nhap', 'chot',
    'kiem', 'soat', 'cach', 'phan', 'tich', 'muc', 'lieu', 'dieu',
    'khien', 'huong', 'nhieu', 'giai', 'quyet', 'dinh', 'tuong',
    'ung', 'khoi', 'chay', 'chuyen', 'tiep', 'xong', 'thuoc', 'loai',
    'rieng', 'chung', 'nhom', 'thoi', 'hach', 'doanh', 'nghiep',
    'phong', 'nghi', 'quyen', 'luot', 'cuoi', 'mien', 'nghiem',
    'luyen', 'chan', 'phep', 'nuoc', 'vien', 'chuc', 'truong', 'doc',
    'lanh', 'pho', 'phoi', 'tong', 'nang', 'suat', 'chat', 'chieu',
    'khung', 'khoan', 'mang', 'luoi', 'vong', 'quanh', 'quay', 'chon',
    'tang', 'cuong', 'nghia', 'phap', 'lien', 'quang', 'lich', 'hoach',
    'luy', 'nhung', 'duoc', 'khong', 'nhac', 'vang', 'tien', 'cang',
    'rang', 'nguoi', 'them', 'xung', 'ranh', 'mong', 'song', 'rung',
    'khay', 'phay', 'thang', 'panme', 'bavia', 'escal', 'quen',
    'khoanh', 'tranh', 'bieu',
    # common Vietnamese abbreviations
    'cntt',
}

# Comprehensive English -> Vietnamese dictionary for QMS/manufacturing
DICT = {
    # ── Status / Labels ──
    'HOLD': 'TẠM GIỮ',
    'BLOCK': 'CHẶN',
    'BLOCKED': 'ĐÃ CHẶN',
    'RELEASE': 'PHÁT HÀNH',
    'RELEASED': 'ĐÃ PHÁT HÀNH',
    'REJECT': 'TỪ CHỐI',
    'TRAINING': 'ĐÀO TẠO',

    # ── High frequency terms ──
    'action': 'hành động',
    'actions': 'hành động',
    'change': 'thay đổi',
    'changes': 'thay đổi',
    'risk': 'rủi ro',
    'risks': 'rủi ro',
    'report': 'báo cáo',
    'reports': 'báo cáo',
    'family': 'nhóm sản phẩm',
    'check': 'kiểm tra',
    'baseline': 'mốc chuẩn',
    'packet': 'gói hồ sơ',
    'shipment': 'lô giao hàng',
    'package': 'gói hàng',
    'route': 'lộ trình gia công',
    'decision': 'quyết định',
    'heat': 'mẻ nấu (heat)',
    'line': 'dòng / chuyền',
    'folder': 'thư mục',
    'cost': 'chi phí',
    'access': 'truy cập',
    'escape': 'thoát / bỏ qua',
    'impact': 'tác động',
    'first': 'đầu tiên',
    'dispatch': 'điều phối xuất hàng',
    'capability': 'năng lực / khả năng',
    'closure': 'kết thúc / đóng',
    'gating': 'kiểm soát cổng',
    'reaction': 'phản ứng / ứng phó',
    'master': 'chủ / gốc',
    'processor': 'người xử lý',
    'wrong': 'sai',
    'mismatch': 'không khớp',
    'trigger': 'kích hoạt',
    'drift': 'trôi / sai lệch',
    'rubric': 'tiêu chí đánh giá',
    'deputy': 'phó',
    'freeze': 'đóng băng',
    'performance': 'hiệu suất',
    'life': 'tuổi thọ / vòng đời',
    'snapshot': 'ảnh chụp trạng thái',
    'governance': 'quản trị',
    'workbook': 'sổ tay thực hành',
    'workbooks': 'sổ tay thực hành',
    'request': 'yêu cầu',
    'routing': 'lộ trình gia công',
    'update': 'cập nhật',
    'safety': 'an toàn',
    'dossier': 'hồ sơ',
    'library': 'thư viện',
    'prove': 'chứng minh',
    'condition': 'điều kiện',
    'critical': 'quan trọng / nghiêm trọng',
    'rate': 'tỷ lệ',
    'trace': 'truy vết',
    'mapping': 'sơ đồ ánh xạ',
    'board': 'bảng',
    'downtime': 'thời gian ngừng máy',
    'skill': 'kỹ năng',
    'cleanliness': 'vệ sinh / sạch sẽ',
    'blueprint': 'bản thiết kế',
    'vacuum': 'chân không',
    'discipline': 'kỷ luật / chuyên ngành',
    'event': 'sự kiện',
    'metadata': 'siêu dữ liệu',
    'planning': 'lập kế hoạch',
    'finish': 'hoàn thiện',
    'finishing': 'hoàn thiện bề mặt',
    'receipt': 'phiếu nhận / biên nhận',
    'rules': 'quy tắc',
    'location': 'vị trí',
    'recovery': 'khôi phục / thu hồi',
    'communication': 'truyền đạt / giao tiếp',
    'method': 'phương pháp',
    'trend': 'xu hướng',
    'zone': 'khu vực',
    'completeness': 'tính đầy đủ',
    'clarification': 'làm rõ',
    'naming': 'đặt tên',
    'window': 'cửa sổ / khung thời gian',
    'work': 'công việc',
    'suspect': 'nghi ngờ',
    'defect': 'khuyết tật',
    'bottleneck': 'nút thắt / điểm nghẽn',
    'share': 'chia sẻ',
    'notes': 'ghi chú',
    'cadence': 'nhịp độ / chu kỳ họp',
    'piece': 'chi tiết / sản phẩm',
    'criteria': 'tiêu chí',
    'margin': 'biên lợi nhuận',
    'crash': 'sự cố nghiêm trọng',
    'controlled': 'được kiểm soát',
    'trainer': 'người đào tạo',
    'cascade': 'lan truyền / phân tầng',
    'invoice': 'hóa đơn',
    'finding': 'phát hiện',
    'study': 'nghiên cứu',
    'integrity': 'tính toàn vẹn',
    'expiry': 'hết hạn',
    'support': 'hỗ trợ',
    'sampling': 'lấy mẫu',
    'clearance': 'thông quan / giải phóng',
    'capacity': 'công suất',
    'payroll': 'bảng lương',
    'deburr': 'mài bavia',
    'refresh': 'làm mới',
    'seal': 'niêm phong',
    'logistics': 'hậu cần',
    'costing': 'tính giá thành',
    'model': 'mô hình',
    'point': 'điểm',
    'reject': 'từ chối',
    'reference': 'tham chiếu',
    'open': 'mở',
    'exception': 'ngoại lệ',
    'exceptions': 'ngoại lệ',
    'dictionary': 'từ điển',
    'strategy': 'chiến lược',
    'coverage': 'phạm vi bao phủ',
    'leak': 'rò rỉ',
    'product': 'sản phẩm',
    'vendor': 'nhà cung cấp',
    'sign': 'ký',
    'handbook': 'sổ tay',
    'coaching': 'huấn luyện',
    'contingency': 'dự phòng',
    'handling': 'xử lý / vận chuyển',
    'escalated': 'đã báo cáo vượt cấp',
    'escalate': 'báo cáo vượt cấp',
    'escalates': 'báo cáo vượt cấp',
    'escalation': 'báo cáo vượt cấp',
    'assumption': 'giả định',
    'assumptions': 'giả định',
    'response': 'phản hồi',
    'chip': 'phoi (chip)',
    'entry': 'mục nhập',
    'split': 'tách / chia',
    'accuracy': 'độ chính xác',
    'tolerance': 'dung sai',
    'block': 'chặn / khóa',
    'breakdown': 'sự cố hỏng máy',
    'build': 'xây dựng',
    'meeting': 'cuộc họp',
    'serial': 'số sê-ri',
    'history': 'lịch sử',
    'repeat': 'lặp lại',
    'repeated': 'lặp lại',
    'packing': 'đóng gói',
    'zero': 'không / bằng không',
    'anodize': 'xi mạ anốt (anodize)',
    'transfer': 'chuyển giao',
    'order': 'đơn hàng',
    'claim': 'khiếu nại / yêu cầu bồi thường',
    'mixed': 'hỗn hợp / lẫn lộn',
    'restart': 'khởi động lại',
    'competency': 'năng lực',
    'ladder': 'bậc thang năng lực',
    'certification': 'chứng nhận',
    'leader': 'trưởng nhóm',
    'reconciliation': 'đối soát',
    'rollback': 'hoàn tác / quay lại',
    'cleaning': 'làm sạch',
    'boundary': 'ranh giới',
    'labor': 'nhân công',
    'sample': 'mẫu',
    'external': 'bên ngoài',
    'minutes': 'biên bản họp',
    'break': 'ngắt / nghỉ',
    'bonus': 'thưởng',
    'special': 'đặc biệt',
    'attendance': 'chuyên cần / điểm danh',
    'major': 'lớn / nghiêm trọng',
    'accept': 'chấp nhận',
    'quantity': 'số lượng',
    'overdue': 'quá hạn',
    'service': 'dịch vụ',
    'burr': 'bavia',
    'completion': 'hoàn thành',
    'changeover': 'chuyển đổi (changeover)',
    'based': 'dựa trên',
    'timestamp': 'dấu thời gian',
    'trail': 'vết / nhật ký thay đổi',
    'queue': 'hàng đợi',
    'handover': 'bàn giao',
    'scenario': 'tình huống',
    'stock': 'tồn kho',
    'inventory': 'hàng tồn kho',
    'specific': 'cụ thể',
    'result': 'kết quả',
    'grade': 'cấp / hạng',
    'treat': 'xử lý',
    'variance': 'chênh lệch / phương sai',
    'estimate': 'ước tính',
    'docs': 'tài liệu',
    'preservation': 'bảo quản',
    'archive': 'lưu trữ',
    'technical': 'kỹ thuật',
    'machining': 'gia công cơ khí',
    'payment': 'thanh toán',
    'actual': 'thực tế',
    'deadline': 'hạn chót',
    'loop': 'vòng lặp',
    'affected': 'bị ảnh hưởng',
    'state': 'trạng thái',
    'edge': 'cạnh / mép',
    'continuity': 'tính liên tục',
    'limit': 'giới hạn',
    'sensitive': 'nhạy cảm',
    'pallet': 'pallet',
    'surface': 'bề mặt',
    'probe': 'đầu dò (probe)',
    'clause': 'điều khoản',
    'clauses': 'điều khoản',
    'audit': 'đánh giá',
    'shop': 'xưởng',
    'live': 'vận hành thực',
    'interface': 'giao diện',
    'alarm': 'cảnh báo',
    'ticket': 'phiếu yêu cầu',
    'required': 'bắt buộc',
    'agenda': 'chương trình họp',
    'information': 'thông tin',
    'certificate': 'chứng chỉ / giấy chứng nhận',
    'execution': 'thực thi',
    'guest': 'khách',
    'known': 'đã biết',
    'notice': 'thông báo',
    'common': 'chung / phổ biến',
    'jobs': 'công việc / đơn hàng',
    'fallback': 'phương án dự phòng',
    'blocker': 'vấn đề chặn',
    'shortage': 'thiếu hụt',
    'unit': 'đơn vị',
    'characteristic': 'đặc tính',
    'reason': 'lý do',
    'cutover': 'chuyển giao hệ thống',
    'orientation': 'định hướng / đào tạo hội nhập',
    'wear': 'mài mòn',
    'documented': 'được lập thành tài liệu',
    'mode': 'chế độ',
    'insert': 'mảnh dao (insert)',
    'account': 'tài khoản',
    'segregation': 'cách ly',
    'partial': 'một phần',
    'lesson': 'bài học',
    'lessons': 'bài học',
    'backfill': 'bổ sung / thay thế',
    'permit': 'giấy phép',
    'revalidation': 'tái xác nhận hiệu lực',
    'instruction': 'hướng dẫn',
    'plating': 'mạ',
    'lock': 'khóa',
    'datums': 'mốc chuẩn (datums)',
    'datum': 'mốc chuẩn (datum)',
    'guide': 'hướng dẫn',
    'format': 'định dạng',
    'schedule': 'lịch trình',
    'area': 'khu vực',
    'allowance': 'dung sai cho phép',
    'restore': 'khôi phục',
    'failure': 'hỏng / lỗi',
    'configuration': 'cấu hình',
    'missing': 'thiếu',
    'summary': 'tóm tắt',
    'daily': 'hàng ngày',
    'abnormality': 'bất thường',
    'gauge': 'dưỡng đo / đồng hồ đo',
    'uncertainty': 'độ không đảm bảo đo',
    'stability': 'độ ổn định',
    'position': 'vị trí / chức vụ',
    'commit': 'cam kết',
    'incoming': 'đầu vào / nhận hàng',
    'near': 'gần / suýt',
    'override': 'ghi đè / bỏ qua',
    'rights': 'quyền',
    'spindle': 'trục chính (spindle)',
    'axis': 'trục',
    'aging': 'lão hóa / cũ',
    'pilot': 'thí điểm',
    'damage': 'hư hỏng',
    'correction': 'sửa chữa / hiệu chính',
    'marking': 'đánh dấu',
    'qualification': 'đánh giá năng lực / trình độ',
    'driver': 'nguyên nhân / động lực',
    'feasibility': 'tính khả thi',
    'priority': 'ưu tiên',
    'gowning': 'mặc đồ bảo hộ (gowning)',
    'staging': 'khu vực chuẩn bị / sắp xếp',
    'restricted': 'hạn chế',
    'emergency': 'khẩn cấp',
    'single': 'đơn lẻ',
    'dispute': 'tranh chấp',
    'internal': 'nội bộ',
    'commercial': 'thương mại',
    'proof': 'bằng chứng',
    'number': 'số',
    'concept': 'khái niệm',
    'storage': 'lưu kho / lưu trữ',
    'tracking': 'theo dõi',
    'classification': 'phân loại',
    'desiccant': 'chất hút ẩm',
    'schema': 'sơ đồ cấu trúc',
    'permissions': 'quyền truy cập',
    'task': 'nhiệm vụ',
    'contract': 'hợp đồng',
    'business': 'kinh doanh',
    'breach': 'vi phạm',
    'overhead': 'chi phí gián tiếp',
    'mentor': 'người hướng dẫn',
    'cosmetic': 'ngoại quan / bề ngoài',
    'clamp': 'kẹp / gá kẹp',
    'publish': 'công bố / phát hành',
    'auditor': 'đánh giá viên',
    'learned': 'rút kinh nghiệm',
    'resource': 'nguồn lực',
    'local': 'nội bộ / tại chỗ',
    'expedite': 'đẩy nhanh tiến độ',
    'severity': 'mức nghiêm trọng',
    'exposure': 'mức độ tiếp xúc / phơi nhiễm',
    'backlog': 'công việc tồn đọng',
    'sequence': 'trình tự',
    'shopfloor': 'mặt bằng xưởng',
    'sealing': 'niêm phong / bịt kín',
    'subcontract': 'gia công ngoài',
    'article': 'sản phẩm / bài viết',
    'functional': 'chức năng',
    'quick': 'nhanh',
    'manual': 'sổ tay / thủ công',
    'genealogy': 'phả hệ truy xuất',
    'people': 'con người',
    'environment': 'môi trường',
    'sweep': 'quét / dọn dẹp',
    'carton': 'thùng carton',
    'abnormal': 'bất thường',
    'content': 'nội dung',
    'mini': 'nhỏ / thu gọn',
    'closeout': 'kết thúc / đóng hồ sơ',
    'credit': 'tín dụng / ghi có',
    'quarantine': 'cách ly / biệt trữ',
    'bias': 'sai lệch hệ thống',
    'checksum': 'tổng kiểm tra',
    'knowledge': 'kiến thức',
    'volume': 'khối lượng',
    'conformity': 'sự phù hợp',
    'improvement': 'cải tiến',
    'hardness': 'độ cứng',
    'thread': 'ren',
    'tests': 'kiểm nghiệm',
    'coolant': 'dung dịch làm nguội',
    'lite': 'rút gọn',
    'sharing': 'chia sẻ',
    'container': 'thùng chứa',
    'purge': 'thanh lọc / loại bỏ',
    'guard': 'bảo vệ / tấm chắn',
    'human': 'con người',
    'delay': 'chậm trễ',
    'permission': 'quyền / sự cho phép',
    'cause': 'nguyên nhân',
    'downstream': 'công đoạn sau',
    'flowdown': 'truyền đạt yêu cầu',
    'alignment': 'căn chỉnh / liên kết',
    'certs': 'chứng chỉ',
    'spot': 'điểm / tại chỗ',
    'confirmation': 'xác nhận',
    'adherence': 'tuân thủ',
    'slot': 'khe / vị trí',
    'labels': 'nhãn',
    'bagging': 'đóng túi',
    'holder': 'cán dao / đầu gá',
    'statement': 'báo cáo / tuyên bố',
    'threshold': 'ngưỡng',
    'dataset': 'bộ dữ liệu',
    'thickness': 'độ dày',
    'confirm': 'xác nhận',
    'deployment': 'triển khai',
    'contractor': 'nhà thầu',
    'health': 'sức khỏe',
    'restriction': 'hạn chế',
    'weekly': 'hàng tuần',
    'authorization': 'ủy quyền',
    'promise': 'cam kết',
    'attribute': 'thuộc tính',
    'supply': 'cung ứng',
    'mill': 'phay',
    'counterfeit': 'hàng giả / hàng nhái',
    'department': 'phòng ban',
    'pocket': 'hốc / túi',
    'factors': 'yếu tố',
    'awareness': 'nhận thức',
    'issues': 'vấn đề',
    'corrective': 'khắc phục',
    'scorecard': 'bảng điểm',
    'trade': 'nghề / thương mại',
    'tower': 'tháp / cột',
    'safe': 'an toàn',
    'authorized': 'được ủy quyền',
    'frequency': 'tần suất',
    'identity': 'nhận dạng',
    'proposal': 'đề xuất',
    'room': 'phòng',
    'segregate': 'cách ly',
    'trial': 'thử nghiệm',
    'linearity': 'độ tuyến tính',
    'profile': 'hồ sơ / biên dạng',
    'requalification': 'tái đánh giá năng lực',
    'approve': 'phê duyệt',
    'read': 'đọc',
    'subgroup': 'nhóm con',
    'title': 'tiêu đề',
    'quotation': 'báo giá',
    'cross': 'chéo',
    'cleanroom': 'phòng sạch',
    'contact': 'liên hệ',
    'security': 'bảo mật',
    'handover': 'bàn giao',
    'endpoint': 'điểm cuối',
    'asset': 'tài sản',
    'thinking': 'tư duy',
    'booking': 'đặt lịch / ghi nhận',
    'treatment': 'xử lý',
    'bucket': 'nhóm / phân loại',
    'interval': 'khoảng thời gian',
    'pattern': 'mẫu / quy luật',
    'pipeline': 'quy trình / luồng công việc',
    'gaming': 'gian lận / lạm dụng',
    'tray': 'khay',
    'loss': 'tổn thất',
    'resequence': 'sắp xếp lại',
    'feature': 'đặc điểm / tính năng',
    'bank': 'ngân hàng',
    'links': 'liên kết',
    'freight': 'cước vận chuyển',
    'carrier': 'đơn vị vận chuyển',
    'controls': 'kiểm soát',
    'alternate': 'thay thế / phương án khác',
    'conditional': 'có điều kiện',
    'photo': 'ảnh chụp',
    'inner': 'bên trong',
    'declare': 'khai báo',
    'overlay': 'lớp phủ',
    'hazard': 'mối nguy',
    'cash': 'tiền mặt',
    'substitute': 'thay thế',
    'router': 'bộ định tuyến / lộ trình',
    'remnant': 'vật liệu thừa',
    'guardband': 'dải bảo vệ (guardband)',
    'monitoring': 'giám sát',
    'reporting': 'báo cáo',
    'offboarding': 'thôi việc / rời công ty',
    'barcode': 'mã vạch',
    'recipe': 'công thức / chương trình gia công',
    'inch': 'inch',
    'mirror': 'phản chiếu / sao chép',
    'outsourcing': 'thuê ngoài',
    'intent': 'mục đích / ý định',
    'deploy': 'triển khai',
    'privileged': 'có đặc quyền',
    'basis': 'cơ sở',
    'spare': 'phụ tùng',
    'definition': 'định nghĩa',
    'match': 'khớp / phù hợp',
    'taxonomy': 'phân loại hệ thống',
    'objective': 'mục tiêu',
    'leakage': 'rò rỉ',
    'triage': 'phân loại ưu tiên',
    'integration': 'tích hợp',
    'analysis': 'phân tích',
    'watch': 'theo dõi / cảnh giác',
    'population': 'tập hợp / dân số',
    'overtime': 'tăng ca',
    'coordination': 'phối hợp',
    'self': 'tự',
    'context': 'bối cảnh',
    'feed': 'bước tiến (feed)',
    'particle': 'hạt / phần tử',
    'bundle': 'gói / bó',
    'housekeeping': 'vệ sinh công nghiệp (5S)',
    'quarterly': 'hàng quý',
    'preventive': 'phòng ngừa',
    'revoke': 'thu hồi / hủy bỏ',
    'ownership': 'quyền sở hữu',
    'forecast': 'dự báo',
    'mark': 'đánh dấu',
    'center': 'trung tâm',
    'pricing': 'định giá',
    'rollout': 'triển khai',
    'passivation': 'thụ động hóa (passivation)',
    'unsafe': 'không an toàn',
    'leadership': 'lãnh đạo',
    'adjustment': 'điều chỉnh',
    'terms': 'điều khoản',
    'linkage': 'liên kết',
    'overwrite': 'ghi đè',
    'availability': 'khả dụng / sẵn sàng',
    'repair': 'sửa chữa',
    'linked': 'liên kết',
    'automation': 'tự động hóa',
    'coating': 'lớp phủ / mạ',
    'scheme': 'sơ đồ / kế hoạch',
    'waiver': 'miễn trừ',
    'series': 'chuỗi / loạt',
    'duplicate': 'trùng lặp',
    'temporary': 'tạm thời',
    'turning': 'tiện',
    'length': 'chiều dài',
    'items': 'mục / hạng mục',
    'function': 'chức năng',
    'outer': 'bên ngoài',
    'intake': 'tiếp nhận',
    'environmental': 'môi trường',
    'cutoff': 'cắt / ngưỡng cắt',
    'timeline': 'dòng thời gian',
    'equivalent': 'tương đương',
    'utilization': 'tỷ lệ sử dụng',
    'steps': 'các bước',
    'masking': 'che phủ (masking)',
    'switching': 'chuyển đổi',
    'learning': 'học tập',
    'recurrence': 'tái phát',
    'capture': 'ghi nhận',
    'fields': 'trường dữ liệu',
    'timeliness': 'đúng hạn',
    'commitment': 'cam kết',
    'declaration': 'khai báo',
    'temper': 'ram (temper)',
    'train': 'đào tạo',
    'yield': 'tỷ lệ đạt',
    'induction': 'đào tạo hội nhập',
    'legal': 'pháp lý',
    'stack': 'chồng / xếp',
    'setting': 'cài đặt',
    'effective': 'hiệu lực / hiệu quả',
    'truth': 'sự thật',
    'posting': 'ghi sổ / đăng',
    'structure': 'cấu trúc',
    'screenshot': 'ảnh chụp màn hình',
    'replacement': 'thay thế',
    'compatibility': 'tương thích',
    'price': 'giá',
    'labeling': 'dán nhãn',
    'shadow': 'đứng cạnh học việc',
    'balance': 'cân bằng / số dư',
    'foam': 'xốp / bọt',
    'notification': 'thông báo',
    'retrieval': 'truy xuất',
    'hardware': 'phần cứng',
    'carry': 'mang / chuyển',
    'rinse': 'rửa',
    'cover': 'bao phủ / che',
    'wetted': 'tiếp xúc chất lỏng',
    'validator': 'người xác nhận',
    'measure': 'đo lường',
    'parameter': 'thông số',
    'exclusions': 'loại trừ',
    'monthly': 'hàng tháng',
    'supplied': 'được cung cấp',
    'dock': 'bến xuất nhập hàng',
    'indicator': 'chỉ số',
    'station': 'trạm / vị trí làm việc',
    'soft': 'mềm',
    'plug': 'nút bịt',
    'reprint': 'in lại',
    'kitting': 'chuẩn bị bộ linh kiện',
    'tree': 'cây / sơ đồ cây',
    'right': 'quyền / đúng',
    'config': 'cấu hình',
    'reconcile': 'đối soát',
    'signal': 'tín hiệu',
    'pressure': 'áp suất',
    'released': 'đã phát hành',
    'manpower': 'nhân lực',
    'pickup': 'lấy hàng',
    'double': 'kép / gấp đôi',
    'scratch': 'trầy xước',
    'offsets': 'bù trừ (offset)',
    'behavior': 'hành vi',
    'glass': 'kính / thủy tinh',
    'witness': 'chứng kiến',
    'range': 'phạm vi / dải',
    'compatible': 'tương thích',
    'outgassing': 'thoát khí (outgassing)',
    'charter': 'điều lệ / quy chế',
    'example': 'ví dụ',
    'after': 'sau',
    'good': 'tốt / đạt',
    'property': 'thuộc tính / tài sản',
    'over': 'trên / vượt quá',
    'under': 'dưới',
    'only': 'chỉ / duy nhất',
    'through': 'xuyên suốt',
    'about': 'về',
    'before': 'trước',

    # ── Roles ──
    'Planning': 'Kế hoạch',
    'Purchasing': 'Mua hàng',
    'Supply': 'Cung ứng',
    'Chain': 'Chuỗi',
    'Management': 'Quản lý',
    'Department': 'Phòng ban',
    'Service': 'Dịch vụ',
    'Sales': 'Kinh doanh',
    'Cash': 'Tiền mặt',
    'Estimator': 'Người định giá',
    'Estimating': 'Ước tính / Định giá',
    'Shipping': 'Giao vận',
    'Receiving': 'Nhận hàng',
    'Technician': 'Kỹ thuật viên',
    'Programmer': 'Lập trình viên (CNC)',
    'Competency': 'Năng lực',
    'Competencies': 'Năng lực',
    'Breakdown': 'Sự cố hỏng máy',
    'Metrology': 'Đo lường',
    'Scenario': 'Tình huống',
    'Planner': 'Người lập kế hoạch',
    'Rubric': 'Tiêu chí đánh giá',
    'Logistics': 'Hậu cần',
    'Dispatch': 'Điều phối',
    'Skill': 'Kỹ năng',
    'Skills': 'Kỹ năng',
    'Performance': 'Hiệu suất',
    'Safety': 'An toàn',
    'Master': 'Gốc / Chủ',
    'Change': 'Thay đổi',
    'Risk': 'Rủi ro',
    'Action': 'Hành động',
    'Report': 'Báo cáo',
    'First': 'Đầu tiên',
    'Access': 'Truy cập',
    'Impact': 'Tác động',
    'Gating': 'Kiểm soát cổng',
    'Knowledge': 'Kiến thức',
    'Dictionary': 'Từ điển',
    'Daily': 'Hàng ngày',
    'Trainer': 'Người đào tạo',
    'Trainee': 'Học viên',
    'Handbook': 'Sổ tay',
    'Buyer': 'Nhân viên mua hàng',
    'Controlled': 'Được kiểm soát',
    'Tracking': 'Theo dõi',
    'Downtime': 'Thời gian ngừng máy',
    'Cost': 'Chi phí',
    'Executive': 'Điều hành',
    'Trigger': 'Kích hoạt',
    'Position': 'Vị trí / Chức vụ',
    'Communication': 'Truyền đạt',
    'Deputy': 'Phó',
    'Restricted': 'Hạn chế',
    'Order': 'Đơn hàng',
    'Digital': 'Số hóa',
    'People': 'Con người',
    'Payroll': 'Bảng lương',
    'Clerk': 'Nhân viên văn phòng',
    'Primary': 'Chính / Sơ cấp',
    'Dossiers': 'Hồ sơ',
    'Dossier': 'Hồ sơ',
    'Officer': 'Cán bộ / Nhân viên',
    'Packing': 'Đóng gói',
    'Lean': 'Tinh gọn (Lean)',
    'Model': 'Mô hình',
    'Invoice': 'Hóa đơn',
    'Decision': 'Quyết định',
    'Cascade': 'Phân tầng',
    'Routing': 'Lộ trình gia công',
    'Blocked': 'Đã chặn',
    'Bonus': 'Thưởng',
    'Quick': 'Nhanh',
    'Secondary': 'Thứ cấp / Phụ',
    'Zone': 'Khu vực',
    'Operating': 'Vận hành',
    'Labor': 'Nhân công',
    'Practitioner': 'Người thực hành',
    'Update': 'Cập nhật',
    'Mission': 'Sứ mệnh',
    'Responsibilities': 'Trách nhiệm',
    'Blueprint': 'Bản thiết kế',
    'Foundation': 'Nền tảng',
    'Minutes': 'Biên bản họp',
    'Instruction': 'Hướng dẫn',
    'Coordinator': 'Điều phối viên',
    'Frontline': 'Tuyến đầu',
    'Response': 'Phản hồi',
    'Setting': 'Cài đặt',
    'Configuration': 'Cấu hình',
    'Block': 'Chặn',
    'Archive': 'Lưu trữ',
    'Delta': 'Chênh lệch',
    'Deployment': 'Triển khai',
    'Improvement': 'Cải tiến',
    'Storekeeper': 'Thủ kho',
    'Severity': 'Mức nghiêm trọng',
    'Closure': 'Kết thúc',
    'Major': 'Lớn / Nghiêm trọng',
    'Shipment': 'Lô giao hàng',
    'Request': 'Yêu cầu',
    'Line': 'Dòng / Chuyền',
    'Packet': 'Gói hồ sơ',
    'Freeze': 'Đóng băng',
    'Mindset': 'Tư duy',
    'Repeat': 'Lặp lại',
    'Library': 'Thư viện',
    'Work': 'Công việc',
    'Cleaning': 'Làm sạch',
    'Certification': 'Chứng nhận',
    'Deburr': 'Mài bavia',
    'Reconciliation': 'Đối soát',
    'Board': 'Bảng',
    'Costing': 'Tính giá thành',
    'Boundary': 'Ranh giới',
    'Assessment': 'Đánh giá',
    'Snapshot': 'Ảnh chụp trạng thái',
    'Folder': 'Thư mục',
    'Leadership': 'Lãnh đạo',
    'Receipt': 'Phiếu nhận',
    'Naming': 'Đặt tên',
    'Refresh': 'Làm mới',
    'Reaction': 'Phản ứng',
    'Commercial': 'Thương mại',
    'Surface': 'Bề mặt',
    'Thinking': 'Tư duy',
    'Cadence': 'Nhịp độ',
    'Workbook': 'Sổ tay thực hành',
    'Internal': 'Nội bộ',
    'Technical': 'Kỹ thuật',
    'Critical': 'Quan trọng',
    'Notice': 'Thông báo',
    'Common': 'Chung',
    'Changeover': 'Chuyển đổi (changeover)',
    'Administrator': 'Quản trị viên',
    'Governance': 'Quản trị',
    'Leader': 'Trưởng nhóm',
    'Escalate': 'Báo cáo vượt cấp',
    'Escal': 'Báo cáo vượt cấp',
    'Event': 'Sự kiện',
    'Emergency': 'Khẩn cấp',
    'Conditional': 'Có điều kiện',
    'Choice': 'Lựa chọn',
    'Within': 'Trong phạm vi',
    'Industry': 'Ngành công nghiệp',
    'Package': 'Gói hàng',
    'Processor': 'Người xử lý',
    'Method': 'Phương pháp',
    'Finding': 'Phát hiện',
    'Versioning': 'Quản lý phiên bản',
    'Call': 'Cuộc gọi',
    'Auditor': 'Đánh giá viên',
    'Entry': 'Mục nhập',
    'Workplace': 'Nơi làm việc',
    'Ishikawa': 'Ishikawa',
    'Margin': 'Biên lợi nhuận',
    'Discipline': 'Kỷ luật',
    'Advanced': 'Nâng cao',
    'Storage': 'Lưu kho',
    'Datum': 'Mốc chuẩn (datum)',
    'Transaction': 'Giao dịch',
    'Lists': 'Danh sách',
    'Head': 'Trưởng / Đầu',
    'Single': 'Đơn lẻ',
    'Health': 'Sức khỏe',
    'Mapping': 'Sơ đồ ánh xạ',
    'Operational': 'Vận hành',
    'Heads': 'Trưởng bộ phận',
    'Classification': 'Phân loại',
    'Enterprise': 'Doanh nghiệp',
    'Wrong': 'Sai',
    'Mixed': 'Hỗn hợp',
    'Second': 'Thứ hai / Giây',
    'Close': 'Đóng',
    'Business': 'Kinh doanh',
    'Payments': 'Thanh toán',
    'Tests': 'Kiểm nghiệm',
    'Rules': 'Quy tắc',
    'Science': 'Khoa học',
    'Sampling': 'Lấy mẫu',
    'Guest': 'Khách',
    'Completeness': 'Tính đầy đủ',
    'Functional': 'Chức năng',
    'Packs': 'Gói',
    'Product': 'Sản phẩm',
    'Industrial': 'Công nghiệp',
    'Prioritization': 'Ưu tiên hóa',
    'Interpretation': 'Diễn giải',
    'Translation': 'Dịch thuật',
    'Morale': 'Tinh thần',
    'Manual': 'Sổ tay',
    'Priority': 'Ưu tiên',
    'Tolerance': 'Dung sai',
    'Check': 'Kiểm tra',
    'Monitoring': 'Giám sát',
    'Worked': 'Đã thực hiện',
    'Confidential': 'Bảo mật',
    'Recovery': 'Khôi phục',
    'Continual': 'Liên tục',
    'Subcontract': 'Gia công ngoài',
    'Environment': 'Môi trường',
    'Cutover': 'Chuyển giao hệ thống',
    'Required': 'Bắt buộc',
    'Prepare': 'Chuẩn bị',
    'Reject': 'Từ chối',
    'Follow': 'Theo dõi',
    'Analysis': 'Phân tích',
    'Kinetic': 'Kinetic (Epicor)',
    'Pilot': 'Thí điểm',
    'Audit': 'Đánh giá',
    'Asset': 'Tài sản',
    'Core': 'Cốt lõi',
    'Finishing': 'Hoàn thiện',
    'Problem': 'Vấn đề',
    'Pareto': 'Pareto',
    'Framework': 'Khung / Khuôn khổ',
    'Baseline': 'Mốc chuẩn',
    'Guide': 'Hướng dẫn',
    'Capability': 'Khả năng',
    'Expert': 'Chuyên gia',
    'General': 'Tổng / Chung',
    'Rate': 'Tỷ lệ',
    'Inventory': 'Hàng tồn kho',
    'External': 'Bên ngoài',
    'Meeting': 'Cuộc họp',
    'Coordination': 'Phối hợp',
    'Editors': 'Biên tập viên',
    'Attendance': 'Chuyên cần',
    'Handover': 'Bàn giao',
    'Solving': 'Giải quyết',
    'Treatment': 'Xử lý',
    'Clarification': 'Làm rõ',
    'Estimate': 'Ước tính',
    'Accountant': 'Kế toán',
    'Lesson': 'Bài học',
    'Driven': 'Định hướng bởi',
    'Usage': 'Sử dụng',
    'Certificate': 'Chứng chỉ',
    'Build': 'Xây dựng',
    'Variance': 'Chênh lệch',
    'Right': 'Quyền / Đúng',
    'Full': 'Đầy đủ',
    'Open': 'Mở',
    'Result': 'Kết quả',
    'Route': 'Lộ trình',
    'Location': 'Vị trí',
    'Escape': 'Thoát',
    'Return': 'Trả lại',
    'Partial': 'Một phần',
    'Authorized': 'Được ủy quyền',
    'Probation': 'Thử việc',
    'Hygiene': 'Vệ sinh',
    'Purview': 'Phạm vi quản lý',
    'Waste': 'Lãng phí',
    'Prove': 'Chứng minh',
    'Important': 'Quan trọng',
    'Steps': 'Các bước',
    'Analyze': 'Phân tích',
    'Notes': 'Ghi chú',
    'Post': 'Đăng / Ghi sổ',
    'User': 'Người dùng',
    'Trend': 'Xu hướng',
    'Quarterly': 'Hàng quý',
    'Hazard': 'Mối nguy',
    'Suspend': 'Tạm ngưng',
    'Minor': 'Nhỏ / Không nghiêm trọng',
    'Capacity': 'Công suất',
    'Cleanliness': 'Vệ sinh',
    'Peer': 'Đồng nghiệp / Ngang cấp',
    'Verified': 'Đã xác minh',
    'Assessor': 'Người đánh giá',
    'Docs': 'Tài liệu',
    'Publish': 'Công bố',
    'Owners': 'Chủ sở hữu',
    'Exception': 'Ngoại lệ',
    'After': 'Sau',
    'Mentor': 'Người hướng dẫn',
    'Apply': 'Áp dụng',
    'Heat': 'Mẻ nấu (heat)',
    'Admins': 'Quản trị viên',
    'Deep': 'Chuyên sâu',
    'Reference': 'Tham chiếu',
    'Workbooks': 'Sổ tay',

    # Kaizen & Japanese terms
    'Kaizen': 'Kaizen',
    'kaizen': 'kaizen',
    'gemba': 'gemba (thực địa)',
    'poka': 'poka (chống sai)',

    # Abbreviations - keep English
    'SCAR': 'SCAR',
    'PDCA': 'PDCA',
    'FIFO': 'FIFO',
    'FEFO': 'FEFO',
    'LOTO': 'LOTO',
    'SMED': 'SMED',
    'ALCOA': 'ALCOA',
    'ASTM': 'ASTM',
    'ASME': 'ASME',
    'PROC': 'PROC',
    'PROD': 'PROD',
    'COMP': 'COMP',
    'ENGM': 'ENGM',
    'SEMI': 'SEMI',
    'RMAP': 'RMAP',
    'EVID': 'EVID',
    'YYYY': 'YYYY',
    'YYYYMMDD': 'YYYYMMDD',
    'QCDSM': 'QCDSM',
    'SBAR': 'SBAR',
    'BLACK': 'BLACK',
    'CNTT': 'CNTT',
    'Incoterms': 'Incoterms',
    'Pareto': 'Pareto',
    'Ishikawa': 'Ishikawa',

    # ── Additional translations: Manufacturing / CNC specific ──
    'offset': 'bù trừ (offset)',
    'yoke': 'giá đỡ (yoke)',
    'fixture': 'đồ gá',
    'fixturing': 'gá kẹp',
    'collet': 'ống kẹp (collet)',
    'chuck': 'mâm cặp (chuck)',
    'bore': 'lỗ khoan',
    'chamfer': 'vát mép',
    'torque': 'mô-men xoắn',
    'runout': 'độ đảo (runout)',
    'toolbox': 'hộp dụng cụ',
    'workcenter': 'trung tâm gia công',
    'drilling': 'khoan',
    'grinding': 'mài',
    'tapping': 'tarô / taro ren',
    'assembly': 'lắp ráp',
    'radius': 'bán kính',
    'diameter': 'đường kính',
    'dimension': 'kích thước',
    'rotary': 'quay',
    'collision': 'va chạm',
    'tailstock': 'ụ sau (tailstock)',
    'chatter': 'rung (chatter)',
    'distortion': 'biến dạng',
    'hole': 'lỗ',
    'cavity': 'hốc / lòng khuôn',
    'stain': 'vết bẩn / ố',
    'dent': 'lõm / móp',
    'residue': 'cặn / dư lượng',
    'purity': 'độ tinh khiết',
    'helium': 'heli',
    'bake': 'nung / sấy',
    'alloy': 'hợp kim',
    'polymer': 'polymer',
    'insulator': 'vật liệu cách điện',
    'corrosive': 'ăn mòn',
    'ultrasonic': 'siêu âm',
    'precision': 'chính xác / độ chính xác',
    'geometry': 'hình học',
    'speed': 'tốc độ',
    'depth': 'chiều sâu',
    'weight': 'trọng lượng',
    'caliper': 'thước cặp',
    'micrometer': 'panme / thước đo vi lượng',
    'gage': 'dưỡng đo (gage)',
    'preset': 'cài đặt trước',
    'shim': 'miếng chêm (shim)',
    'liner': 'lót / ống lót',
    'manifold': 'ống góp / đa tạp',
    'connector': 'đầu nối',
    'rack': 'giá đỡ / khung',
    'crate': 'thùng gỗ',
    'envelope': 'bao bì / phong bì',
    'shelf': 'kệ',
    'crib': 'kho dụng cụ (tool crib)',
    'consumable': 'vật tư tiêu hao',

    # ── Additional translations: Quality / Inspection ──
    'repeatability': 'độ lặp lại',
    'reproducibility': 'độ tái lập',
    'sensitivity': 'độ nhạy',
    'confidence': 'độ tin cậy',
    'characteristics': 'đặc tính',
    'specification': 'quy cách kỹ thuật',
    'nonconformity': 'sự không phù hợp',
    'nonconformance': 'sự không phù hợp',
    'discrepancy': 'sai khác',
    'disposition': 'xử lý / quyết định xử lý',
    'concession': 'nhượng bộ',
    'containment': 'ngăn chặn',
    'guardbanding': 'áp dụng dải bảo vệ',

    # ── Additional translations: Roles / People ──
    'Chief': 'Trưởng / Giám đốc',
    'Staff': 'Nhân viên',
    'Employee': 'Nhân viên',
    'employee': 'nhân viên',
    'Managers': 'Quản lý',
    'Dispatcher': 'Nhân viên điều phối',
    'Personnel': 'Nhân sự',
    'Organization': 'Tổ chức',
    'appraiser': 'người thẩm định',
    'senior': 'cao cấp',
    'headcount': 'số nhân sự',
    'staffing': 'bố trí nhân sự',
    'succession': 'kế nhiệm',
    'onboarding': 'hội nhập nhân viên mới',
    'coach': 'huấn luyện viên',
    'proctor': 'người giám sát thi',
    'visitor': 'khách tham quan',
    'trainer': 'người đào tạo',

    # ── Additional translations: Business / Finance ──
    'debit': 'ghi nợ',
    'accrual': 'dồn tích / tích lũy',
    'premium': 'phí bảo hiểm / cao cấp',
    'chargeback': 'hoàn phí / bồi hoàn',
    'billing': 'lập hóa đơn',
    'journal': 'sổ nhật ký kế toán',
    'accounting': 'kế toán',
    'accounts': 'tài khoản',
    'ledger': 'sổ cái',
    'financial': 'tài chính',
    'agreement': 'thỏa thuận',
    'warranty': 'bảo hành',
    'sourcing': 'tìm nguồn cung',
    'procurement': 'mua sắm',
    'outsourced': 'thuê ngoài',
    'purchase': 'mua hàng',
    'budget': 'ngân sách',

    # ── Additional translations: IT / System ──
    'folders': 'thư mục',
    'files': 'tập tin',
    'dashboards': 'bảng điều khiển',
    'dashboard': 'bảng điều khiển',
    'settings': 'cài đặt',
    'backup': 'sao lưu',
    'repository': 'kho lưu trữ',
    'software': 'phần mềm',
    'device': 'thiết bị',
    'platform': 'nền tảng',
    'desktop': 'máy tính bàn',
    'network': 'mạng',
    'mailbox': 'hộp thư',
    'message': 'tin nhắn / thông điệp',
    'application': 'ứng dụng',
    'screen': 'màn hình',
    'kiosk': 'ki-ốt',
    'tenant': 'tổ chức thuê (tenant)',
    'architecture': 'kiến trúc',
    'skeleton': 'khung sườn',
    'lookup': 'tra cứu',
    'query': 'truy vấn',
    'access': 'truy cập',

    # ── Additional translations: Process / Action words ──
    'close': 'đóng',
    'return': 'trả lại',
    'down': 'xuống / ngừng',
    'fast': 'nhanh',
    'miss': 'thiếu / bỏ sót',
    'finish': 'hoàn thành',
    'shipping': 'giao vận',
    'receiving': 'nhận hàng',
    'chain': 'chuỗi',
    'management': 'quản lý',
    'error': 'lỗi',
    'post': 'ghi sổ / đăng',
    'anti': 'chống',
    'packs': 'gói',
    'away': 'cách xa / rời',
    'need': 'cần',
    'hours': 'giờ',
    'turn': 'lượt / quay',
    'points': 'điểm',
    'high': 'cao',
    'last': 'cuối cùng',
    'full': 'đầy đủ',
    'user': 'người dùng',
    'turnaround': 'thời gian quay vòng',
    'workaround': 'giải pháp tạm',
    'priorities': 'ưu tiên',
    'movement': 'di chuyển / dịch chuyển',
    'recertification': 'tái chứng nhận',
    'turnover': 'doanh thu / tỷ lệ nghỉ việc',
    'protection': 'bảo vệ',
    'usable': 'có thể sử dụng',
    'validity': 'hiệu lực',
    'codes': 'mã',
    'interlock': 'khóa liên động',
    'provisioning': 'cung cấp / cấp phát',
    'catalog': 'danh mục',
    'move': 'di chuyển',
    'choice': 'lựa chọn',
    'zones': 'khu vực',
    'apply': 'áp dụng',
    'stream': 'luồng',
    'acknowledgement': 'xác nhận / biên nhận',
    'acknowledgment': 'xác nhận / biên nhận',
    'investigation': 'điều tra',
    'logging': 'ghi nhật ký',
    'selection': 'lựa chọn',
    'project': 'dự án',
    'logistic': 'hậu cần',
    'short': 'ngắn / thiếu',
    'award': 'trao giải / khen thưởng',
    'identification': 'nhận dạng',
    'outbound': 'xuất đi',
    'water': 'nước',
    'wastes': 'lãng phí',
    'lists': 'danh sách',
    'utility': 'tiện ích',
    'triggers': 'kích hoạt',
    'lost': 'mất / thất lạc',
    'impacted': 'bị ảnh hưởng',
    'lane': 'làn / tuyến',
    'digital': 'số hóa',
    'probation': 'thử việc',
    'used': 'đã sử dụng',
    'photos': 'ảnh chụp',
    'late': 'muộn / trễ',
    'call': 'cuộc gọi',
    'face': 'mặt / bề mặt',
    'floor': 'sàn / tầng',
    'libraries': 'thư viện',
    'leading': 'dẫn đầu / chỉ số dẫn',
    'working': 'làm việc',
    'conflict': 'xung đột',
    'lifecycle': 'vòng đời',
    'reopen': 'mở lại',
    'period': 'giai đoạn / kỳ',
    'month': 'tháng',
    'anomaly': 'bất thường',
    'certified': 'đã chứng nhận',
    'intended': 'dự kiến / có chủ đích',
    'satisfaction': 'sự hài lòng',
    'substitution': 'thay thế',
    'gates': 'cổng',
    'semiconductor': 'bán dẫn',
    'variation': 'biến thiên',
    'root': 'gốc / căn nguyên',
    'activation': 'kích hoạt',
    'free': 'miễn phí / tự do',
    'auto': 'tự động',
    'thresholds': 'ngưỡng',
    'reseal': 'niêm phong lại',
    'hard': 'cứng / khó',
    'side': 'cạnh / mặt bên',
    'versioning': 'quản lý phiên bản',
    'base': 'cơ sở / nền',
    'mask': 'che / mặt nạ',
    'overflow': 'tràn',
    'unique': 'duy nhất',
    'creation': 'tạo mới',
    'outage': 'mất dịch vụ / ngưng hoạt động',
    'found': 'phát hiện',
    'results': 'kết quả',
    'requests': 'yêu cầu',
    'notify': 'thông báo',
    'calendar': 'lịch',
    'urgent': 'khẩn cấp',
    'assessor': 'người đánh giá',
    'parts': 'chi tiết / linh kiện',
    'repack': 'đóng gói lại',
    'current': 'hiện tại',
    'solution': 'giải pháp',
    'inspect': 'kiểm tra',
    'estimating': 'ước tính / định giá',
    'attachment': 'đính kèm / tài liệu đính kèm',
    'chemistry': 'thành phần hóa học',
    'child': 'con / phụ thuộc',
    'parent': 'cha / gốc',
    'core': 'cốt lõi',
    'groups': 'nhóm',
    'manufacturing': 'sản xuất',
    'fatigue': 'mỏi (fatigue)',
    'chemical': 'hóa chất',
    'basics': 'cơ bản',
    'needs': 'nhu cầu',
    'constraints': 'ràng buộc',
    'duties': 'nhiệm vụ',
    'collection': 'thu thập',
    'related': 'liên quan',
    'statutory': 'luật định',
    'reschedule': 'lên lịch lại',
    'overload': 'quá tải',
    'driven': 'định hướng bởi',
    'allocation': 'phân bổ',
    'zoning': 'phân vùng',
    'talk': 'trao đổi',
    'framework': 'khung / khuôn khổ',
    'verified': 'đã xác minh',
    'classes': 'lớp / phân loại',
    'extract': 'trích xuất',
    'warning': 'cảnh báo',
    'channel': 'kênh',
    'cleanup': 'dọn dẹp',
    'walk': 'đi kiểm tra (gemba walk)',
    'managed': 'được quản lý',
    'tools': 'dụng cụ',
    'orchestration': 'điều phối',
    'needed': 'cần thiết',
    'objectives': 'mục tiêu',
    'updated': 'đã cập nhật',
    'factor': 'yếu tố',
    'supersede': 'thay thế / bãi bỏ',
    'implementation': 'triển khai',
    'shared': 'dùng chung',
    'operational': 'vận hành',
    'updates': 'cập nhật',
    'timekeeping': 'chấm công',
    'supporting': 'hỗ trợ',
    'aerospace': 'hàng không vũ trụ',
    'medical': 'y tế',
    'resolution': 'giải quyết / độ phân giải',
    'certificates': 'chứng chỉ',
    'breakage': 'hư hỏng / gãy vỡ',
    'term': 'thuật ngữ / kỳ hạn',
    'write': 'viết / ghi',
    'effect': 'hiệu ứng / tác dụng',
    'confirmed': 'đã xác nhận',
    'second': 'thứ hai / giây',
    'tightened': 'siết chặt / thắt chặt',
    'flag': 'đánh dấu / cờ',
    'accreditation': 'công nhận',
    'limits': 'giới hạn',
    'users': 'người dùng',
    'mass': 'khối lượng',
    'decisions': 'quyết định',
    'signals': 'tín hiệu',
    'planned': 'đã lên kế hoạch',
    'standardization': 'chuẩn hóa',
    'changed': 'đã thay đổi',
    'evaluation': 'đánh giá',
    'upstream': 'công đoạn trước',
    'thermal': 'nhiệt',
    'blocked': 'bị chặn',
    'guideline': 'hướng dẫn',
    'problem': 'vấn đề',
    'complex': 'phức tạp',
    'uncontrolled': 'không kiểm soát',
    'withdrawal': 'rút / thu hồi',
    'eligibility': 'đủ điều kiện',
    'minor': 'nhỏ / không nghiêm trọng',
    'placeholder': 'giữ chỗ',
    'visibility': 'khả năng nhìn thấy / minh bạch',
    'concern': 'lo ngại / vấn đề',
    'controller': 'bộ điều khiển / kiểm soát viên',
    'unresolved': 'chưa giải quyết',
    'callout': 'ghi chú / chỉ dẫn trên bản vẽ',
    'normal': 'bình thường',
    'dossiers': 'hồ sơ',
    'administration': 'quản trị / hành chính',
    'mandatory': 'bắt buộc',
    'patch': 'bản vá / sửa chữa',
    'systems': 'hệ thống',
    'overlap': 'chồng chéo',
    'shipments': 'lô giao hàng',
    'workmanship': 'tay nghề',
    'manufacturability': 'khả năng sản xuất',
    'delta': 'chênh lệch',
    'reduced': 'giảm',
    'responsiveness': 'khả năng phản hồi',
    'outcome': 'kết quả',
    'random': 'ngẫu nhiên',
    'custody': 'giám hộ / quản lý',
    'excursion': 'vượt ngưỡng',
    'dual': 'kép',
    'sealed': 'đã niêm phong',
    'validate': 'xác nhận hiệu lực',
    'lagging': 'chỉ số trễ',
    'retry': 'thử lại',
    'structural': 'cấu trúc',
    'drivers': 'nguyên nhân / động lực',
    'highlight': 'nổi bật / đánh dấu',
    'implement': 'triển khai',
    'connection': 'kết nối',
    'documentation': 'tài liệu',
    'leaders': 'lãnh đạo',
    'reviewed': 'đã rà soát',
    'failed': 'thất bại / không đạt',
    'rush': 'gấp / khẩn',
    'independent': 'độc lập',
    'assignment': 'phân công',
    'basic': 'cơ bản',
    'reinforcement': 'củng cố',
    'fact': 'thực tế',
    'comment': 'nhận xét',
    'segment': 'phân khúc',
    'invoicing': 'lập hóa đơn',
    'culture': 'văn hóa',
    'make': 'tạo / sản xuất',
    'resume': 'tiếp tục',
    'reliability': 'độ tin cậy',
    'workholding': 'gá kẹp chi tiết',
    'expected': 'dự kiến',
    'climate': 'môi trường / bầu không khí',
    'formula': 'công thức',
    'session': 'phiên / buổi',
    'best': 'tốt nhất',
    'practice': 'thực hành',
    'briefing': 'họp ngắn / phổ biến',
    'wording': 'cách diễn đạt',
    'directed': 'chỉ đạo',
    'barrier': 'rào cản',
    'bill': 'hóa đơn / bảng kê',
    'memo': 'bản ghi nhớ',
    'constraint': 'ràng buộc',
    'scope': 'phạm vi',
    'standard': 'tiêu chuẩn',
    'procedure': 'thủ tục',
    'drawing': 'bản vẽ',
    'requirement': 'yêu cầu',
    'approval': 'phê duyệt',
    'release': 'phát hành',
    'review': 'rà soát',
    'inspection': 'kiểm tra',
    'evidence': 'bằng chứng',
    'compliance': 'tuân thủ',
    'calibration': 'hiệu chuẩn',
    'training': 'đào tạo',
    'competence': 'năng lực',
    'revision': 'phiên bản',
    'operation': 'vận hành',
    'document': 'tài liệu',
    'record': 'hồ sơ',
    'process': 'quy trình',
    'production': 'sản xuất',
    'quality': 'chất lượng',
    'customer': 'khách hàng',
    'supplier': 'nhà cung cấp',
    'material': 'nguyên vật liệu',
    'equipment': 'thiết bị',
    'maintenance': 'bảo trì',
    'warehouse': 'kho',
    'delivery': 'giao hàng',
    'packaging': 'đóng gói',
    'measurement': 'đo lường',
    'workshop': 'xưởng',
    'form': 'biểu mẫu',
    'checklist': 'bảng kiểm',
    'log': 'nhật ký',
    'register': 'sổ theo dõi',
    'complaint': 'khiếu nại',
    'incident': 'sự cố',
    'tooling': 'dao cụ',
    'scrap': 'phế liệu',
    'rework': 'sửa hàng',
    'hold': 'tạm giữ',
    'lot': 'lô hàng',
    'batch': 'lô hàng',

    # ── Additional translations: Dreyfus model ──
    'Novice': 'Tập sự',
    'Competent': 'Đủ năng lực',
    'Proficient': 'Thành thạo',
    'Dreyfus': 'Dreyfus',

    # ── Additional translations: Lean / Kaizen ──
    'Andon': 'Andon (đèn cảnh báo)',
    'waste': 'lãng phí',
    'bottleneck': 'nút thắt / điểm nghẽn',
    'scorecard': 'bảng điểm',

    # ── Additional translations: Training / Learning ──
    'certification': 'chứng nhận',
    'qualification': 'đánh giá năng lực',
    'rubric': 'tiêu chí đánh giá',
    'curriculum': 'chương trình đào tạo',
    'program': 'chương trình',

    # ── Additional translations: General QMS ──
    'cascading': 'phân tầng',
    'handoff': 'bàn giao',
    'readiness': 'sẵn sàng',
    'effectiveness': 'hiệu lực',
    'milestone': 'mốc quan trọng',
    'risk': 'rủi ro',
    'impact': 'tác động',
    'decision': 'quyết định',
    'action': 'hành động',
    'reaction': 'phản ứng',
    'deviation': 'sai lệch',

    # ── Additional translations: Common words in QMS text ──
    'with': 'với',
    'from': 'từ',
    'when': 'khi',
    'between': 'giữa',
    'during': 'trong suốt',
    'within': 'trong phạm vi',
    'above': 'trên',
    'below': 'dưới',
    'each': 'mỗi',
    'every': 'mỗi / mọi',
    'also': 'cũng',
    'even': 'thậm chí',
    'just': 'chỉ',
    'still': 'vẫn',
    'into': 'vào',

    # ── Codes / Abbreviations - keep as-is ──
    'SSCC': 'SSCC',
    'JOBCODE': 'JOBCODE',
    'NCRID': 'NCRID',
    'NCRLog': 'NCRLog',
    'QCHoldLog': 'QCHoldLog',
    'WIPTracker': 'WIPTracker',
    'WIPStage': 'WIPStage',
    'TECHNICIAN': 'KỸ THUẬT VIÊN',
    'OPERATOR': 'NGƯỜI VẬN HÀNH',
    'INSPECTOR': 'NGƯỜI KIỂM TRA',
    'PROGRAMMER': 'LẬP TRÌNH VIÊN',
    'ACCOUNTANT': 'KẾ TOÁN',
    'SPECIALIST': 'CHUYÊN VIÊN',
    'FAIR': 'FAIR',
    'RBAC': 'RBAC',
    'MTTR': 'MTTR',
    'AUTH': 'AUTH',
    'BHXH': 'BHXH',
    'BHYT': 'BHYT',
    'BHTN': 'BHTN',
    'PCCC': 'PCCC',
    'PTFE': 'PTFE',
    'PEEK': 'PEEK',
    'AMBER': 'AMBER',
    'ISSUED': 'ĐÃ PHÁT HÀNH',
    'REWORK': 'SỬA HÀNG',
    'OBSOLETE': 'LỖI THỜI',
    'PRODUCTION': 'SẢN XUẤT',
    'PROG': 'PROG',
    'EXEC': 'EXEC',
    'YYYYQ': 'YYYYQ',

    # ── Statistics / Analysis ──
    'Median': 'Trung vị',
    'median': 'trung vị',
    'Tick': 'Dấu tích',
    'tick': 'dấu tích',
    'Minimum': 'Tối thiểu',
    'minimum': 'tối thiểu',
    'Likelihood': 'Khả năng xảy ra',
    'likelihood': 'khả năng xảy ra',
    'Detectability': 'Khả năng phát hiện',
    'detectability': 'khả năng phát hiện',
    'Stratification': 'Phân tầng',
    'stratification': 'phân tầng',
    'Efficiency': 'Hiệu suất',
    'efficiency': 'hiệu suất',
    'latency': 'độ trễ',
    'timebox': 'khung thời gian giới hạn',

    # ── Process verbs ──
    'escalte': 'báo cáo vượt cấp',
    'probing': 'đo bằng đầu dò',
    'privilege': 'quyền hạn',
    'Create': 'Tạo',
    'create': 'tạo',
    'Evaluate': 'Đánh giá',
    'evaluate': 'đánh giá',
    'Contain': 'Ngăn chặn',
    'contain': 'ngăn chặn / chứa',
    'Validated': 'Đã xác nhận hiệu lực',
    'validated': 'đã xác nhận hiệu lực',
    'Contribute': 'Đóng góp',
    'contribute': 'đóng góp',
    'Prepare': 'Chuẩn bị',
    'prepare': 'chuẩn bị',
    'Issuing': 'Phát hành',
    'issuing': 'phát hành',
    'Hunt': 'Tìm kiếm',
    'hunt': 'tìm kiếm',
    'Upsert': 'Cập nhật/Thêm mới',
    'withdraw': 'rút / thu hồi',
    'proofing': 'kiểm chứng / soát lỗi',
    'multitask': 'đa nhiệm',
    'kick': 'khởi động',
    'slide': 'trình chiếu / trượt',
    'look': 'xem / tra cứu',

    # ── Manufacturing ──
    'metrology': 'đo lường',
    'purchasing': 'mua hàng',
    'Plant': 'Nhà máy',
    'plant': 'nhà máy',
    'Company': 'Công ty',
    'company': 'công ty',
    'ring': 'vòng / khuyên',
    'Metal': 'Kim loại',
    'metal': 'kim loại',
    'Alloy': 'Hợp kim',
    'alloy': 'hợp kim',
    'chamber': 'buồng / khoang',
    'Fishbone': 'Xương cá (Fishbone)',
    'fishbone': 'xương cá (fishbone)',
    'warm': 'ấm / làm nóng trước',
    'shock': 'va đập / sốc',
    'plate': 'tấm / bản',
    'shoe': 'đế / gối đỡ',
    'basket': 'rổ / giỏ',
    'moisture': 'độ ẩm',
    'shielding': 'che chắn',
    'detector': 'đầu dò / bộ phát hiện',
    'grain': 'hạt / thớ',
    'nozzle': 'vòi phun',
    'tape': 'băng dính / băng keo',
    'flatness': 'độ phẳng',
    'turret': 'đầu dao (turret)',
    'taro': 'tarô (taro ren)',
    'kinematic': 'động học',
    'collet': 'ống kẹp (collet)',
    'tank': 'bồn / thùng chứa',
    'component': 'linh kiện / bộ phận',
    'bearing': 'ổ bi / vòng bi',
    'stylus': 'đầu đo (stylus)',
    'variable': 'biến số / biến thiên',
    'ballooning': 'đánh số balloon',

    # ── Quality / Audit ──
    'Layered': 'Phân tầng',
    'layered': 'phân tầng',
    'Disruption': 'Gián đoạn',
    'disruption': 'gián đoạn',
    'matrices': 'ma trận',
    'Nonconforming': 'Không phù hợp',
    'nonconforming': 'không phù hợp',
    'criticality': 'mức độ quan trọng',
    'violation': 'vi phạm',
    'symptom': 'triệu chứng / dấu hiệu',
    'recurrence': 'tái phát',
    'chronic': 'mãn tính / kéo dài',
    'screening': 'sàng lọc',
    'inspectability': 'khả năng kiểm tra',
    'redundancy': 'dự phòng / thừa',
    'detection': 'phát hiện',
    'excursion': 'vượt ngưỡng',
    'custody': 'giám hộ / quản lý',

    # ── Business ──
    'Opportunity': 'Cơ hội',
    'opportunity': 'cơ hội',
    'Opportunities': 'Cơ hội',
    'Professional': 'Chuyên nghiệp',
    'professional': 'chuyên nghiệp',
    'Recruitment': 'Tuyển dụng',
    'recruitment': 'tuyển dụng',
    'savings': 'tiết kiệm',
    'offer': 'chào hàng / đề nghị',
    'progress': 'tiến độ',
    'provider': 'nhà cung cấp dịch vụ',
    'providers': 'nhà cung cấp dịch vụ',
    'consumption': 'tiêu thụ',
    'charge': 'chi phí / phí',
    'quoted': 'đã báo giá',
    'pivot': 'trục / chuyển hướng',
    'uptime': 'thời gian hoạt động',
    'helpdesk': 'bộ phận hỗ trợ',
    'currency': 'tiền tệ',
    'discount': 'chiết khấu',
    'gross': 'tổng / gộp',
    'reserve': 'dự trữ / dự phòng',
    'forwarder': 'đơn vị giao nhận',
    'Timesheet': 'Bảng chấm công',
    'timesheet': 'bảng chấm công',
    'Expired': 'Đã hết hạn',
    'expired': 'đã hết hạn',

    # ── IT / System ──
    'Interfaces': 'Giao diện',
    'interfaces': 'giao diện',
    'Background': 'Nền',
    'background': 'nền',
    'Tracker': 'Công cụ theo dõi',
    'tracker': 'công cụ theo dõi',
    'Templates': 'Mẫu',
    'templates': 'mẫu',
    'Hyperlink': 'Siêu liên kết',
    'hyperlink': 'siêu liên kết',
    'modules': 'mô-đun',
    'token': 'mã thông báo (token)',
    'cursor': 'con trỏ',
    'merge': 'gộp / hợp nhất',
    'subfolders': 'thư mục con',
    'standup': 'họp đứng / họp nhanh',
    'playbook': 'sách hướng dẫn',
    'runbook': 'sổ tay vận hành',
    'Runbook': 'Sổ tay vận hành',
    'checkpoint': 'điểm kiểm tra',
    'hierarchy': 'phân cấp',
    'watermark': 'dấu chìm / hình chìm',
    'clusters': 'nhóm / cụm',
    'cluster': 'nhóm / cụm',
    'orphan': 'không có chủ / mồ côi',
    'idempotent': 'tính bất biến (idempotent)',
    'hash': 'mã băm (hash)',
    'skeleton': 'khung sườn',

    # ── People / Organization ──
    'Organizational': 'Tổ chức',
    'organizational': 'tổ chức',
    'Dispatcher': 'Nhân viên điều phối',
    'Filing': 'Lưu hồ sơ',
    'filing': 'lưu hồ sơ',
    'Valid': 'Hợp lệ',
    'valid': 'hợp lệ',
    'traveller': 'phiếu công đoạn (traveller)',
    'Description': 'Mô tả',
    'description': 'mô tả',
    'Culture': 'Văn hóa',
    'culture': 'văn hóa',
    'Working': 'Làm việc',
    'working': 'làm việc',
    'Objectives': 'Mục tiêu',
    'objectives': 'mục tiêu',
    'Purchase': 'Mua hàng',
    'purchase': 'mua hàng',
    'Year': 'Năm',
    'year': 'năm',
    'Novice': 'Tập sự',
    'Competent': 'Đủ năng lực',
    'Proficient': 'Thành thạo',
    'Anyone': 'Bất kỳ ai',
    'Remember': 'Ghi nhớ',
    'Understand': 'Hiểu',
    'Layer': 'Lớp / Tầng',
    'layer': 'lớp / tầng',
    'secondary': 'thứ cấp',
    'stale': 'cũ / lỗi thời',
    'head': 'trưởng / đầu',
    'enterprise': 'doanh nghiệp',
    'ngang': 'ngang',
    'calib': 'hiệu chuẩn',
    'estimator': 'người định giá',

    # ── General common words ──
    'conditions': 'điều kiện',
    'checks': 'kiểm tra',
    'sites': 'địa điểm / site',
    'None': 'Không có',
    'none': 'không có',
    'thumb': 'ngón cái / quy tắc nhanh',
    'least': 'ít nhất',
    'Where': 'Ở đâu / Nơi nào',
    'where': 'ở đâu / nơi nào',
    'What': 'Gì / Cái gì',
    'what': 'gì / cái gì',
    'Hour': 'Giờ',
    'hour': 'giờ',
    'Convention': 'Quy ước',
    'convention': 'quy ước',
    'English': 'Tiếng Anh',
    'cheat': 'tóm tắt nhanh (cheat sheet)',
    'Voided': 'Đã hủy',
    'voided': 'đã hủy',
    'Shipped': 'Đã giao hàng',
    'shipped': 'đã giao hàng',
    'Contemporaneous': 'Đồng thời / Cùng thời điểm',
    'digit': 'chữ số',
    'Vespel': 'Vespel',
    'refs': 'tham chiếu',
    'prep': 'chuẩn bị',
    'left': 'trái / còn lại',
    'events': 'sự kiện',
    'default': 'mặc định',
    'Default': 'Mặc định',
    'stick': 'dính / que',
    'liner': 'lót / ống lót',
    'frame': 'khung',
    'connector': 'đầu nối',
    'Andon': 'Andon (đèn cảnh báo)',
    'SSee': 'SSee',

    # ── Actions / Status ──
    'Failed': 'Thất bại',
    'completed': 'đã hoàn thành',
    'duplicates': 'trùng lặp',
    'alerts': 'cảnh báo',
    'commitments': 'cam kết',
    'consumables': 'vật tư tiêu hao',
    'complexity': 'độ phức tạp',
    'interested': 'quan tâm',
    'parties': 'bên liên quan',
    'Interested': 'Quan tâm',
    'returned': 'đã trả lại',
    'tight': 'chặt / sát',
    'counts': 'số đếm',
    'relabel': 'dán nhãn lại',
    'guests': 'khách',
    'snapshots': 'ảnh chụp trạng thái',
    'native': 'bản địa / gốc',
    'broken': 'hỏng / gãy',
    'relocation': 'di dời',
    'separation': 'phân tách',
    'operating': 'vận hành',
    'Legible': 'Rõ ràng / Dễ đọc',
    'legible': 'rõ ràng / dễ đọc',
    'fits': 'phù hợp',
    'Question': 'Câu hỏi',
    'question': 'câu hỏi',
    'solving': 'giải quyết',
    'organization': 'tổ chức',
    'enforcement': 'thực thi / cưỡng chế',
    'programming': 'lập trình',
    'reuse': 'tái sử dụng',
    'latest': 'mới nhất',
    'missed': 'bỏ lỡ',
    'credential': 'thông tin xác thực',
    'reconciliations': 'đối soát',
    'drop': 'thả / giảm',
    'confidentiality': 'bảo mật',
    'revocation': 'thu hồi / hủy bỏ',
    'dependency': 'phụ thuộc',
    'misuse': 'lạm dụng',
    'track': 'theo dõi',
    'multi': 'đa',
    'aligned': 'liên kết / phù hợp',
    'inform': 'thông báo',
    'loading': 'nạp / tải',
    'balancing': 'cân bằng',
    'Meetings': 'Cuộc họp',
    'applicable': 'áp dụng',
    'measuring': 'đo lường',
    'wait': 'chờ',
    'coding': 'mã hóa / lập trình',
    'remove': 'loại bỏ',
    'guarding': 'bảo vệ / che chắn',
    'sensor': 'cảm biến',
    'saving': 'lưu / tiết kiệm',
    'insight': 'thông tin chi tiết',
    'Kickoff': 'Khởi động',
    'kickoff': 'khởi động',
    'closing': 'đóng / kết thúc',
    'expediting': 'đẩy nhanh tiến độ',
    'plans': 'kế hoạch',
    'rationale': 'cơ sở lý luận',
    'relevance': 'tính liên quan',
    'previous': 'trước đó',
    'same': 'giống / cùng',
    'recipient': 'người nhận',
    'defense': 'phòng thủ / bảo vệ',
    'pointer': 'con trỏ / gợi ý',
    'strategic': 'chiến lược',
    'signed': 'đã ký',
    'edges': 'cạnh / mép',
    'revalidate': 'tái xác nhận',
    'remaining': 'còn lại',
    'reservation': 'đặt trước',
    'anonymous': 'ẩn danh',
    'sister': 'chị em / liên kết',
    'types': 'loại',
    'maker': 'người tạo / nhà sản xuất',
    'exit': 'thoát / ra',
    'scale': 'quy mô / thang đo',
    'removal': 'loại bỏ',

    # ── Low frequency but important ──
    'activity': 'hoạt động',
    'expectation': 'kỳ vọng',
    'references': 'tham chiếu',
    'flags': 'đánh dấu',
    'reduction': 'giảm',
    'troubleshooting': 'xử lý sự cố',
    'managers': 'quản lý',
    'without': 'không có',
    'space': 'không gian',
    'evacuation': 'sơ tán',
    'accreditation': 'công nhận',
    'accounting': 'kế toán',
    'staffing': 'bố trí nhân sự',
    'standardization': 'chuẩn hóa',
    'succession': 'kế nhiệm',
    'documentation': 'tài liệu',
    'implementation': 'triển khai',
    'manufacturing': 'sản xuất',
    'Zalo': 'Zalo',

    # ── Final batch ──

    'eofe': 'eofe',
    'recert': 'tái chứng nhận',
    'memberships': 'tư cách thành viên',
    'functions': 'chức năng',
    'joint': 'liên kết / mối nối',
    'Issue': 'Vấn đề / Phát hành',
    'issue': 'vấn đề / phát hành',
    'acid': 'axit',
    'carbide': 'cacbua / hợp kim cứng',
    'Available': 'Khả dụng',
    'available': 'khả dụng',
    'Attributable': 'Có thể quy cho',
    'Original': 'Gốc / Ban đầu',
    'original': 'gốc / ban đầu',
    'Accurate': 'Chính xác',
    'accurate': 'chính xác',
    'Situation': 'Tình huống',
    'situation': 'tình huống',
    'Rebalance': 'Cân bằng lại',
    'rebalance': 'cân bằng lại',
    'composite': 'tổng hợp / composite',
    'Programs': 'Chương trình',
    'programs': 'chương trình',
    'Hidden': 'Ẩn',
    'hidden': 'ẩn',
    'handbooks': 'sổ tay',
    'pages': 'trang',
    'policies': 'chính sách',
    'isolation': 'cách ly',
    'fire': 'cháy / hỏa hoạn',
    'walkdown': 'đi kiểm tra thực tế',
    'personnel': 'nhân sự',
    'instability': 'bất ổn định',
    'domain': 'lĩnh vực / miền',
    'success': 'thành công',
    'suspicious': 'đáng ngờ',
    'hygiene': 'vệ sinh',
    'revenue': 'doanh thu',
    'relevant': 'liên quan',
    'issued': 'đã phát hành',
    'until': 'cho đến khi',
    'processing': 'xử lý',
    'Applicable': 'Áp dụng',
    'isolation': 'cách ly',
    'inspection': 'kiểm tra',
    'CUSTOM': 'TÙY CHỈNH',
    'vars': 'biến số',
    'calc': 'tính toán',

}

def main():
    with open('tools/remaining_english_words.txt', 'r', encoding='utf-8') as f:
        lines = f.readlines()

    words = []
    for line in lines:
        parts = line.strip().split('\t')
        if len(parts) == 2:
            word, count = parts[0], int(parts[1])
            if len(word) >= 4 and word.isascii() and word.isalpha():
                if word.lower() in VIETNAMESE:
                    continue
                # Skip CamelCase code terms (JobNum, PartNum, etc.)
                import re
                if re.match(r'^[a-z]+[A-Z]', word) or re.match(r'^[A-Z][a-z]+[A-Z]', word):
                    continue
                words.append((word, count))

    print(f"Filtered: {len(words)} English words")

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = 'Tu tieng Anh con sot'

    hfont = Font(name='Arial', bold=True, size=11, color='FFFFFF')
    hfill = PatternFill('solid', fgColor='2F5496')
    halign = Alignment(horizontal='center', vertical='center', wrap_text=True)
    cfont = Font(name='Arial', size=10)
    calign = Alignment(vertical='center', wrap_text=True)
    yes_fill = PatternFill('solid', fgColor='C6EFCE')
    no_fill = PatternFill('solid', fgColor='FFC7CE')
    empty_fill = PatternFill('solid', fgColor='FFEB9C')
    tb = Border(left=Side(style='thin'), right=Side(style='thin'),
                top=Side(style='thin'), bottom=Side(style='thin'))

    headers = ['STT', 'Từ tiếng Anh', 'Số lần', 'Bản dịch tiếng Việt', 'Dịch (Yes/No)', 'Ghi chú']
    for col, h in enumerate(headers, 1):
        c = ws.cell(row=1, column=col, value=h)
        c.font = hfont; c.fill = hfill; c.alignment = halign; c.border = tb

    for i, (word, count) in enumerate(words, 2):
        vi = DICT.get(word, DICT.get(word.lower(), ''))
        # Determine Yes/No
        if vi and vi == word:
            yn = 'No'  # abbreviation kept as-is
        elif vi:
            yn = 'Yes'
        else:
            yn = ''

        ws.cell(row=i, column=1, value=i-1).font = cfont
        ws.cell(row=i, column=1).alignment = Alignment(horizontal='center', vertical='center')
        ws.cell(row=i, column=1).border = tb

        ws.cell(row=i, column=2, value=word).font = cfont
        ws.cell(row=i, column=2).alignment = calign
        ws.cell(row=i, column=2).border = tb

        c = ws.cell(row=i, column=3, value=count)
        c.font = cfont; c.alignment = Alignment(horizontal='center', vertical='center'); c.border = tb

        ws.cell(row=i, column=4, value=vi).font = cfont
        ws.cell(row=i, column=4).alignment = calign
        ws.cell(row=i, column=4).border = tb

        c = ws.cell(row=i, column=5, value=yn)
        c.font = cfont; c.alignment = Alignment(horizontal='center', vertical='center'); c.border = tb
        if yn == 'Yes':
            c.fill = yes_fill
        elif yn == 'No':
            c.fill = no_fill
        else:
            c.fill = empty_fill

        ws.cell(row=i, column=6, value='').font = cfont
        ws.cell(row=i, column=6).alignment = calign
        ws.cell(row=i, column=6).border = tb

    ws.column_dimensions['A'].width = 6
    ws.column_dimensions['B'].width = 30
    ws.column_dimensions['C'].width = 10
    ws.column_dimensions['D'].width = 38
    ws.column_dimensions['E'].width = 14
    ws.column_dimensions['F'].width = 40
    ws.freeze_panes = 'A2'
    ws.auto_filter.ref = f'A1:F{ws.max_row}'

    out = 'tools/remaining-english-words.xlsx'
    wb.save(out)

    has_vi = sum(1 for w, c in words if DICT.get(w, DICT.get(w.lower(), '')))
    no_vi = len(words) - has_vi
    print(f"Saved: {out}")
    print(f"  Total: {len(words)}")
    print(f"  Đã có bản dịch: {has_vi}")
    print(f"  Chưa có bản dịch (vàng): {no_vi}")

if __name__ == '__main__':
    main()
