import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const jsonFile = path.join(root, '11-Glossary', 'dict-data.json');
const jsFile = path.join(root, '11-Glossary', 'dict-data.js');

const updates = [
  {
    term: 'A3/PDCA',
    meaning: 'A3 / Plan-Do-Check-Act',
    vi: 'A3/PDCA - Phiếu giải quyết vấn đề và vòng lặp cải tiến',
    def: 'Phương pháp giải quyết vấn đề có cấu trúc, dùng một trang A3 để chốt hiện trạng, mục tiêu, nguyên nhân gốc, đối sách, kế hoạch thực hiện, kiểm chứng và chuẩn hóa. Tại HESEM, dùng khi case cải tiến vượt mức xử lý nhanh hoặc cần theo dõi chính thức.',
    ctx: 'QA/QMS, Engineering, Production và process owner dùng trong SOP-903, Kaizen, CAPA và cải tiến liên phòng ban để giữ mốc gốc, owner, deadline, dữ liệu trước/sau và quyết định chuẩn hóa.',
    rec: 'FRM-653 A3/PDCA; action log; lesson learned register; KPI before/after evidence; SOP/WI/FORM được cập nhật sau khi chuẩn hóa',
    cat: 'ISO/QMS',
  },
  {
    term: 'Cash Trigger',
    meaning: 'Cash Trigger',
    vi: 'Sự kiện kích hoạt lập hóa đơn',
    def: 'Sự kiện bàn giao từ vận hành sang Finance để mở yêu cầu xuất hóa đơn và theo dõi công nợ, chỉ được kích hoạt khi lô giao hàng đã được release hợp lệ và chứng từ bắt buộc đã đầy đủ.',
    ctx: 'Shipping, QA, CS và Finance dùng tại cuối luồng RFQ-to-cash để chuyển từ trạng thái giao hàng hoàn tất sang trạng thái lập hóa đơn, theo dõi AR và close hồ sơ đơn hàng.',
    rec: 'FRM-821 invoice request; ship release pack; CoC/CoFC; shipment confirmation; job completion checklist; job dossier close record',
    cat: 'Finance',
  },
  {
    term: 'CNC-IMS-HUB',
    meaning: 'CNC IMS Hub',
    vi: 'Site M365/SharePoint trung tâm cho QMS và hồ sơ CNC',
    def: 'Tên site M365/SharePoint trung tâm dùng để lưu list, library, workflow, approval history, job dossier và record QMS theo cấu trúc kiểm soát. Đây là điểm neo của nhiều đường dẫn SSOT trong tài liệu HESEM.',
    ctx: 'QMS, IT, Engineering, Operations và Quality dùng khi tham chiếu đường dẫn lưu hồ sơ, list vận hành, flow approval và job dossier trong hệ thống số.',
    rec: 'M365 CNC-IMS-HUB site; SharePoint Lists; QMS-Records libraries; Job-Dossiers folders; approval history; automation run logs',
    cat: 'IT/Systems',
  },
  {
    term: 'Conditional Pass',
    meaning: 'Conditional Pass',
    vi: 'Đạt có điều kiện',
    def: 'Trạng thái được phép chạy tiếp có điều kiện khi sai lệch hoặc mức độ chắc chắn đã được khoanh vùng, không ảnh hưởng an toàn/chức năng/chứng nhận, và đã áp thêm control bổ sung cùng thẩm quyền chấp thuận.',
    ctx: 'Quality, Engineering và Production dùng trong first piece/FAI, gate release, containment và decision review khi cần cho phép tiếp tục có kiểm soát thay vì release hoàn toàn.',
    rec: 'FAI/first-piece record; approval note; temporary control plan; 100% inspection plan nếu áp dụng; hold/release decision log',
    cat: 'Quality',
  },
  {
    term: 'CS',
    meaning: 'Customer Service',
    vi: 'Chăm sóc khách hàng',
    def: 'Mã viết tắt cho bộ phận Customer Service, chủ trì tiếp nhận RFQ/PO, làm rõ yêu cầu, điều phối giao tiếp khách hàng và theo dõi cam kết đơn hàng.',
    ctx: 'Xuất hiện trong matrix, RACI, handoff và SOP-201 để chỉ owner giao diện khách hàng và chủ trì các mốc G0-G2/G5 liên quan đến commit và thông tin đơn hàng.',
    rec: 'RFQ register; contract review checklist; kickoff checklist; customer communication log; job dossier',
    cat: 'General',
  },
  {
    term: 'Delta FAI',
    meaning: 'Delta First Article Inspection',
    vi: 'FAI theo phần thay đổi',
    def: 'FAI chỉ đánh giá các đặc tính bị ảnh hưởng bởi thay đổi, cộng thêm các đặc tính chuẩn gá/zero, giao diện datum và CTQ liên quan. Chỉ hợp lệ khi change impact đã được chốt bằng tài liệu.',
    ctx: 'Quality và Engineering dùng khi job có thay đổi có phạm vi rõ ràng về revision, program, datum, tooling, source hoặc phương pháp đo, nhưng không cần revalidate toàn bộ part.',
    rec: 'FAI delta report; change impact record; ballooned drawing/characteristic list; inspection program release; approval decision log',
    cat: 'Quality',
  },
  {
    term: 'E2E',
    meaning: 'End-to-End',
    vi: 'Đầu-cuối toàn bộ chuỗi',
    def: 'Viết tắt cho End-to-End, chỉ một luồng công việc được nhìn xuyên suốt từ đầu vào đầu tiên đến đầu ra cuối cùng, không cắt ranh giới theo từng bộ phận riêng lẻ.',
    ctx: 'Dùng trong process mapping, training, UAT và order execution khi HESEM cần quản trị một chuỗi liên thông như RFQ-to-ship, job dossier lifecycle hoặc approval workflow từ đầu đến cuối.',
    rec: 'Process map; gate records; workflow run log; UAT record; job dossier timeline',
    cat: 'Operations/Planning',
  },
  {
    term: 'ENG',
    meaning: 'Engineering',
    vi: 'Kỹ thuật / Engineering',
    def: 'Mã viết tắt cho function Engineering, bao gồm DFM, process engineering, CAM/NC, release kỹ thuật và change impact kỹ thuật.',
    ctx: 'Xuất hiện trong matrix, gate ownership, escalation và meeting boards để chỉ owner kỹ thuật chịu trách nhiệm baseline package, program, setup standards và change impact.',
    rec: 'Engineering release pack; setup sheet; NC release; change package; technical review log',
    cat: 'General',
  },
  {
    term: 'Evidence Pack',
    meaning: 'Evidence Pack',
    vi: 'Bộ bằng chứng',
    def: 'Tập hợp bằng chứng đã được sắp theo cấu trúc và liên kết chuẩn để chứng minh một gate, một quyết định hoặc một sự kiện đã được thực hiện đúng yêu cầu. Evidence pack phải đúng revision, truy được nguồn và không được là file rời rạc không kiểm soát.',
    ctx: 'Dùng trong audit, FAI, NCR/CAPA, complaint, ship release, risk review, DCR và job dossier khi cần chứng minh tính đầy đủ, tính hợp lệ và khả năng truy xuất của hồ sơ.',
    rec: 'Job dossier; audit evidence pack; FAI package; NCR/CAPA package; ship release pack; approval history; SSOT links',
    cat: 'ISO/QMS',
  },
  {
    term: 'Flow-down',
    meaning: 'Flow-down',
    vi: 'Truyền yêu cầu xuống các bên liên quan',
    def: 'Việc truyền đầy đủ và đúng ngữ cảnh các yêu cầu của khách hàng, bản vẽ, chất lượng, truy xuất, packaging, statutory/regulatory hoặc special requirement xuống Engineering, Planning, Production, QA, kho và nhà cung cấp.',
    ctx: 'Dùng trong contract review, kickoff, outsource, supplier control và contingency cho các job có yêu cầu flow-down cao như aerospace, defense, clean/vacuum hoặc special process.',
    rec: 'Contract review checklist; purchase order notes; traveler/job packet; supplier package; outsource pack; job dossier',
    cat: 'ISO/QMS',
  },
  {
    term: 'Full FAI',
    meaning: 'Full First Article Inspection',
    vi: 'FAI đầy đủ toàn phần',
    def: 'FAI đo/kiểm toàn bộ đặc tính hoặc toàn bộ đặc tính bắt buộc theo yêu cầu khách hàng, ballooned drawing và control plan cho part/revision mới hoặc khi rủi ro buộc phải xác nhận lại toàn diện.',
    ctx: 'Quality và Engineering dùng cho part mới, revision mới, thay đổi có ảnh hưởng rộng, requirement khách hàng hoặc trường hợp không đủ căn cứ để chỉ dùng delta FAI.',
    rec: 'FAI full report; ballooned drawing; characteristic list; CMM/dimensional report; approved sources evidence; inspection plan/control plan',
    cat: 'Quality',
  },
  {
    term: 'HESEM-QMS-SSOT',
    meaning: 'HESEM QMS Single Source of Truth',
    vi: 'Nhà kho dữ liệu chuẩn HESEM QMS',
    def: 'Nhận diện nội bộ dùng để chỉ đường dẫn hoặc điểm đến chính thức trên M365/SharePoint nơi record, checklist scan, approval và evidence được lưu như nguồn tham chiếu chuẩn. Khi tài liệu ghi M365/SharePoint -> HESEM-QMS-SSOT, người dùng phải đặt hồ sơ vào kho chuẩn thay vì lưu tạm ở email, desktop hoặc chat.',
    ctx: 'Dùng trong system guides, contingency, go-live và training ops để chỉ nơi lưu record chuẩn khi mô tả luồng hồ sơ số, scan upload chuyển tiếp hoặc checklist tạm thời.',
    rec: 'SharePoint/M365 controlled libraries; scan-upload transition records; job dossiers; approval logs; audit drill logs',
    cat: 'IT/Systems',
  },
  {
    term: 'HOLD/GO',
    meaning: 'Hold / Go decision',
    vi: 'Quyết định giữ hoặc cho đi tiếp',
    def: 'Trạng thái quyết định vận hành tại gate: HOLD là tạm dừng có kiểm soát cho đến khi đủ điều kiện; GO là được phép chuyển bước hoặc release sau khi MRR, thẩm quyền và bằng chứng đã đầy đủ.',
    ctx: 'Dùng trong first piece, ship release, material receiving, job dossier completeness, training drill và control tower khi cần ra quyết định nhanh nhưng vẫn phải có bằng chứng.',
    rec: 'Gate checklist; hold tag/reason code; release sign-off; MRR links; action log',
    cat: 'Operations/Planning',
  },
  {
    term: 'Inspection Program Release',
    meaning: 'Inspection Program Release',
    vi: 'Phát hành chương trình đo/kiểm',
    def: 'Trạng thái xác nhận chương trình đo/CMM hoặc template đo đã đúng part-rev-datum, đúng phương pháp đo và được phép dùng cho quyết định accept/reject.',
    ctx: 'QC, Metrology và Quality Engineer dùng trước first piece, FAI, final inspection và các công đoạn cần chương trình đo để ngăn việc đo sai revision, sai datum hoặc sai phương pháp.',
    rec: 'FRM-305 Inspection Program Release Checklist; CMM/inspection program file; program revision record; dimensional/FAI report',
    cat: 'Quality',
  },
  {
    term: 'Job Dossier',
    meaning: 'Job Dossier',
    vi: 'Hồ sơ sống của đơn hàng/job',
    def: 'Bộ hồ sơ sống của một đơn hàng/job, gom toàn bộ bằng chứng thương mại, kỹ thuật, chất lượng, giao hàng và tài chính từ RFQ đến ship/invoice theo cấu trúc chuẩn và link SSOT.',
    ctx: 'CS, Planning, Engineering, QA, Shipping và Finance dùng để mở, cập nhật, khóa và truy xuất hồ sơ theo sự kiện G0-G5, audit, complaint, NCR/CAPA và close job.',
    rec: 'FRM-205/206 index; RFQ/contract review records; baseline package; FAI/inspection records; ship release pack; invoice request; lessons learned',
    cat: 'ISO/QMS',
  },
  {
    term: 'Job Packet',
    meaning: 'Job Packet',
    vi: 'Gói tài liệu tác nghiệp tại điểm dùng',
    def: 'Bộ tài liệu và thông tin tác nghiệp tại điểm dùng cho một job/op, thường gồm traveler, part-rev, setup sheet, tool list, gate status, QPL, lot/material và hướng dẫn bắt buộc để xây dựng readiness trước khi chạy.',
    ctx: 'Planning, Setup, Operator, QC và Warehouse dùng tại máy, kiosk, khu đo và công đoạn giao/nhận để xác nhận job đang dùng đúng data và đủ điều kiện release.',
    rec: 'Traveler/job tracking sheet; setup sheet; tool list; gate checklist; material lot record; QPL note; first-piece/FAI trigger references',
    cat: 'Operations/Planning',
  },
  {
    term: 'Last-Known-Good',
    meaning: 'Last-Known-Good',
    vi: 'Mốc xác nhận còn đúng cuối cùng',
    def: 'Mốc cuối cùng có bằng chứng chắc chắn rằng điều kiện setup, revision, program, gage và kết quả đo vẫn còn đúng. Được dùng để khoanh vùng lot nghi ngờ, xác định phạm vi containment và điều tra sai lệch phát hiện muộn.',
    ctx: 'Production, Quality và Engineering dùng sau crash, tool break, alarm, wrong-rev suspicion, OOT gage hoặc bất kỳ sự cố nào có thể làm mất hiệu lực của kết quả release trước đó.',
    rec: 'FRM-511/504 records; machine status log; tool life log; CMM/dimensional reports; NCR/containment records; crash report',
    cat: 'Quality',
  },
  {
    term: 'MHR',
    meaning: 'Machine Hour Rate',
    vi: 'Đơn giá giờ máy',
    def: 'Chi phí 1 giờ máy bán/chargeable hour, không chỉ là 1 giờ đồng hồ. MHR được dùng để tính costing, quotation và đánh giá hiệu quả, bao gồm chi phí sở hữu máy, bảo trì, điện, khấu hao, lao động trực tiếp gắn với máy và overhead phân bổ theo quy tắc đã ban hành.',
    ctx: 'Estimator, Finance và Operations dùng trong báo giá, job costing, margin review và quyết định công suất. Tại HESEM, MHR do Finance/OPS ban hành; Estimator không tự ý đổi rate.',
    rec: 'Costing sheet; approved rate table; quotation package; margin review; Finance/OPS issue record',
    cat: 'Finance',
  },
  {
    term: 'MRR (Minimum Required Records)',
    meaning: 'Minimum Required Records',
    vi: 'Bộ hồ sơ tối thiểu bắt buộc',
    def: 'Tập hợp record tối thiểu phải có trước khi release một control gate, thường gồm form, log, file đo, link SSOT, chữ ký/phê duyệt, revision marker và bằng chứng ảnh hưởng thay đổi. Thiếu MRR thì mặc định HOLD.',
    ctx: 'Dùng trong FAI, ship release, job dossier completeness, system operations và training drill khi cần quy định rõ gate nào được mở và gate nào phải giữ lại do thiếu bằng chứng.',
    rec: 'Gate checklist; approved forms/logs; metrology files; approval signatures; SSOT links; change impact evidence',
    cat: 'ISO/QMS',
  },
  {
    term: 'OPS',
    meaning: 'Operations',
    vi: 'Vận hành / Operations',
    def: 'Mã viết tắt cho function Operations, bao gồm điều hành sản xuất, điều độ, xử lý blocker hiện trường, giữ nhịp tier meeting và đảm bảo gate được thực thi đúng nhịp.',
    ctx: 'Xuất hiện trong scoreboards, RACI, meeting action log, costing rule và workflow ownership để chỉ nhóm vận hành chủ trì ra quyết định tại hiện trường.',
    rec: 'Dispatch list; tier meeting log; action log; shift handover; production dashboard',
    cat: 'General',
  },
  {
    term: 'PLA',
    meaning: 'Planning',
    vi: 'Kế hoạch sản xuất',
    def: 'Mã viết tắt cho function Planning, chủ trì planning release, dispatch, sequencing, readiness coordination và theo dõi WIP theo gate và SLA.',
    ctx: 'Xuất hiện trong SOP-201/501, RACI, matrix quyền hạn và dashboard để chỉ nhóm kế hoạch chịu trách nhiệm mở/giữ readiness và cập nhật tình trạng đơn hàng.',
    rec: 'FRM-501 planning release; dispatch list; WIP aging report; job readiness log; escalation records',
    cat: 'Operations/Planning',
  },
  {
    term: 'PUR',
    meaning: 'Purchasing',
    vi: 'Mua hàng / Purchasing',
    def: 'Mã viết tắt cho function Purchasing, chịu trách nhiệm mua vật tư/dịch vụ, flow-down cho nhà cung cấp, theo dõi due date, cert và control với external provider.',
    ctx: 'Xuất hiện trong supplier control, outsource pack, meeting board và escalations để chỉ owner thu mua và tương tác nhà cung cấp trong hệ thống vận hành.',
    rec: 'PO; supplier package; due-date follow-up log; cert/source records; approved supplier references',
    cat: 'General',
  },
  {
    term: 'QPL',
    meaning: 'Quality Package Level',
    vi: 'Mức gói chất lượng',
    def: 'Mức độ yêu cầu chất lượng và hồ sơ bắt buộc của một job, dùng để quyết định độ sâu hồ sơ, độ chặt gate, mức review trước release và mức cưỡng chế đối với FAI, sampling, final release, packaging và giao hàng.',
    ctx: 'CS, QA, Engineering, Planning, Shipping và Quality dùng từ lúc contract review đến final release để xếp mức QPL cho từng job, lot, partial shipment hoặc work transfer.',
    rec: 'ANNEX-603 QPL rules; contract review checklist; control plan/PFMEA-lite; FAI requirements; ship release pack; QPL register',
    cat: 'Quality',
  },
  {
    term: 'Revalidation',
    meaning: 'Revalidation',
    vi: 'Xác nhận lại sau thay đổi/sự cố',
    def: 'Đánh giá và xác nhận lại first piece, FAI, setup, inspection hoặc gate release sau khi có thay đổi hoặc sự cố làm vô hiệu kết quả release trước đó.',
    ctx: 'Quality, Engineering và Production dùng sau đổi máy, đổi đồ gá, đổi tool ảnh hưởng CTQ, sửa chương trình, crash, restart sau HOLD/NCR, maintenance can thiệp geometry hoặc work transfer.',
    rec: 'Change impact record; revalidation checklist; first-piece/FAI evidence; setup and machine status records; approval decision log',
    cat: 'Quality',
  },
  {
    term: 'RFT',
    meaning: 'Right First Time',
    vi: 'Đúng ngay từ lần đầu',
    def: 'Nguyên tắc và chỉ tiêu hoàn thành công việc đúng ngay lần đầu, không phải rework, scrap, mở lại review hoặc chạy lại do lỗi có thể ngăn từ trước. RFT nhấn mạnh chất lượng phải được thiết kế và kiểm soát trong quá trình, không đẩy về cuối chuỗi.',
    ctx: 'Dùng trong đào tạo C03, quality mindset, CTQ control, first-piece/FAI và daily management khi đánh giá hành vi, kỷ luật thực thi và hiệu quả phòng ngừa lỗi tại nguồn.',
    rec: 'FPY metrics; defect/rework records; CTQ inspection records; training evidence; improvement actions khi RFT không đạt',
    cat: 'Quality',
  },
  {
    term: 'SoR',
    meaning: 'System of Record',
    vi: 'Hệ thống ghi nhận chuẩn',
    def: 'Hệ thống được chỉ định là nơi ghi nhận dữ liệu gốc và trạng thái giao dịch chính thức cho một loại nghiệp vụ. Tại HESEM, Epicor thường là SoR cho transaction ERP; M365/SharePoint có thể là SoR cho workflow, approval và evidence ở nơi được quy định.',
    ctx: 'Dùng khi thiết kế boundary giữa ERP, portal, SharePoint, dashboard và file tại điểm dùng để tránh sửa dữ liệu ở sai nơi, tránh tranh cãi về nguồn đúng và đảm bảo backfill/reconcile sau contingency.',
    rec: 'ANNEX-115 interface map; process-specific system map; transaction history; reconciliation log; contingency backfill records',
    cat: 'IT/Systems',
  },
  {
    term: 'STOP/HOLD/BLOCK',
    meaning: 'Stop / Hold / Block status',
    vi: 'Bộ trạng thái dừng-giữ-chặn',
    def: 'Bộ quy tắc fail-fast để phân loại mức độ chặn dòng tác nghiệp. STOP dừng ngay thao tác khi có nguy cơ kỹ thuật/an toàn rõ ràng; HOLD tạm dừng có kiểm soát do thiếu chứng từ, evidence hoặc quyết định; BLOCK là chặn do quyền, hệ thống hoặc quy định không cho phép tiếp tục hay chia sẻ.',
    ctx: 'Dùng trong system ops, training drill, quality gate, receiving, ship release và data governance để ra lệnh phản ứng nhanh nhưng vẫn truy được lý do và owner.',
    rec: 'Reason code; hold tag; incident/action log; approval/escalation record; MRR links; system access record nếu là BLOCK',
    cat: 'Operations/Planning',
  },
  {
    term: 'Trigger Matrix',
    meaning: 'Trigger Matrix',
    vi: 'Ma trận kích hoạt',
    def: 'Ma trận xác định tình huống nào cần first piece, full FAI, delta FAI, capability study, hold hoặc revalidation dựa trên mức thay đổi, mức rủi ro và tác động đến CTQ/datums/source/phương pháp đo.',
    ctx: 'Quality và Engineering dùng trong SOP-302 và related gate review để ra quyết định nhất quán, tránh việc mỗi người tự diễn giải trigger theo cách riêng.',
    rec: 'FAI trigger review; change impact record; control plan; inspection readiness checklist; approval note',
    cat: 'Quality',
  },
  {
    term: 'TWI Job Breakdown',
    meaning: 'Training Within Industry Job Breakdown',
    vi: 'Bảng phân tích công việc theo TWI',
    def: 'Dạng phân tích công việc của TWI tách một công việc thành Step, Key Points và Reasons để trainer có thể huấn luyện nhất quán, nhận đúng điểm dễ sai và giải thích vì sao phải làm đúng.',
    ctx: 'Dùng trong OJT, trainer guide, practice drill và đào tạo tại hiện trường khi HESEM muốn chuẩn hóa hướng dẫn cho công việc có rủi ro cao như setup, dossier, gate release và record discipline.',
    rec: 'OJT checklist; trainer guide; job breakdown sheet; skill matrix; qualification evidence',
    cat: 'HR/Training',
  },
];

const items = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));
const byKey = item => item.term.trim().toLowerCase();
const merged = new Map(items.map(item => [byKey(item), item]));

for (const item of updates) {
  merged.set(byKey(item), item);
}

const clean = Array.from(merged.values()).sort((a, b) =>
  a.term.localeCompare(b.term, 'en', { sensitivity: 'base' }),
);

fs.writeFileSync(jsonFile, JSON.stringify(clean, null, 2) + '\n', 'utf8');
fs.writeFileSync(
  jsFile,
  'window.HESEM_GLOSSARY = ' + JSON.stringify(clean) + ';\nwindow.DICT_DATA = window.HESEM_GLOSSARY;\n',
  'utf8',
);

console.log(`Upserted ${updates.length} curated glossary terms.`);
