<?php

declare(strict_types=1);

$baseDir = __DIR__;
$migrationsDir = $baseDir . '/migrations';
$targetFile = $baseDir . '/schema.sql';

$migrationFiles = glob($migrationsDir . '/*.sql') ?: [];
sort($migrationFiles, SORT_NATURAL | SORT_FLAG_CASE);

if ($migrationFiles === []) {
    fwrite(STDERR, "No migration files found in {$migrationsDir}\n");
    exit(1);
}

$sections = [
    '-- ============================================================================',
    '-- HESEM MOM PORTAL - GENERATED SCHEMA SNAPSHOT',
    '-- Source of truth: database/migrations/*.sql',
    '-- This file is generated by database/build_schema_snapshot.php',
    '-- ============================================================================',
    '',
];

foreach ($migrationFiles as $migrationFile) {
    $name = basename($migrationFile);
    $body = file_get_contents($migrationFile);
    if ($body === false) {
        fwrite(STDERR, "Unable to read migration {$name}\n");
        exit(1);
    }

    $sections[] = '-- >>> BEGIN MIGRATION: ' . $name;
    $sections[] = rtrim($body);
    $sections[] = '-- <<< END MIGRATION: ' . $name;
    $sections[] = '';
}

$snapshot = implode("\n", $sections);
if (file_put_contents($targetFile, $snapshot) === false) {
    fwrite(STDERR, "Unable to write schema snapshot to {$targetFile}\n");
    exit(1);
}

fwrite(STDOUT, "Generated schema snapshot from " . count($migrationFiles) . " migrations.\n");
